import {
  priceSources as wintergartenPriceSources,
  regions,
  renovationModel,
  services as wintergartenServices,
  type PriceItem as WintergartenPriceItem,
  type Service as WintergartenService,
} from "./catalog-wintergarten";

export const priceSources = {
  ...wintergartenPriceSources,
  blauarbeitCarport2026: {
    name: "Blauarbeit - Carport Kosten 2026",
    url: "https://ratgeber.blauarbeit.de/kosten-preise/carport-bauen-kosten",
    checkedAt: "31.08.2026",
  },
  myhammerCarport2026: {
    name: "MyHammer - Carport Kosten",
    url: "https://www.my-hammer.de/bauen-renovieren/preisradar/was-kostet-carport-bauen",
    checkedAt: "31.08.2026",
  },
  myhammerGarage2026: {
    name: "MyHammer - Garage bauen Kosten 2026",
    url: "https://www.my-hammer.de/bauen-renovieren/preisradar/was-kostet-garage-bauen",
    checkedAt: "31.08.2026",
  },
  aroundhomeFertiggarage2026: {
    name: "Aroundhome - Fertiggarage Preise 2026",
    url: "https://www.aroundhome.de/garage/fertiggaragen-preise-preisvergleich/",
    checkedAt: "31.08.2026",
  },
  aroundhomeMassivgarage2026: {
    name: "Aroundhome - Gemauerte Garage Kosten",
    url: "https://www.aroundhome.de/garage/kosten-gemauerte-garage/",
    checkedAt: "31.08.2026",
  },
} as const;

type CarportGarageSourceKey = keyof typeof priceSources;
export type PriceItem = Omit<WintergartenPriceItem, "sourceKey"> & { sourceKey: CarportGarageSourceKey };
export type Service = Omit<WintergartenService, "priceItems"> & { priceItems: PriceItem[] };

const inheritedServices = wintergartenServices as unknown as Service[];

const carportService: Service = {
  slug: "carport",
  title: "Carport Kosten 2026",
  shortTitle: "Carport",
  description: "Aktuelle Richtwerte 2026 für Einzel- und Doppelcarport, Holz- und Aluminiumcarport, Bausatz, Montage, Maßanfertigung, Fundament, Geräteraum und Dach in Deutschland.",
  unit: "Projekt / Stück",
  icon: "⌂",
  priceItems: [
    {
      name: "Carport Bausatz",
      low: 1500,
      high: 5000,
      unit: "pro Projekt",
      note: "Breite Orientierung für einen Carport-Bausatz ohne professionelle Montage und Fundament",
      sourceKey: "blauarbeitCarport2026",
    },
    {
      name: "Einzelcarport Bausatz Flachdach",
      low: 1500,
      high: 3000,
      unit: "pro Projekt",
      sourceKey: "blauarbeitCarport2026",
    },
    {
      name: "Einzelcarport Bausatz Satteldach",
      low: 2500,
      high: 5000,
      unit: "pro Projekt",
      sourceKey: "blauarbeitCarport2026",
    },
    {
      name: "Carport Aufbau durch Fachbetrieb",
      low: 1500,
      high: 3000,
      unit: "pro Projekt",
      note: "Montageleistung zusätzlich zum Bausatz; Fundament separat prüfen",
      sourceKey: "blauarbeitCarport2026",
    },
    {
      name: "Einzelcarport komplett mit Aufbau",
      low: 3000,
      high: 8000,
      unit: "pro Projekt",
      sourceKey: "blauarbeitCarport2026",
    },
    {
      name: "Doppelcarport komplett mit Aufbau",
      low: 5000,
      high: 12000,
      unit: "pro Projekt",
      note: "Je nach Dachform, Holzqualität und Ausstattung; Fundamente können zusätzlich anfallen",
      sourceKey: "blauarbeitCarport2026",
    },
    {
      name: "Carport Maßanfertigung Zimmerer oder Tischler",
      low: 5000,
      high: 10000,
      unit: "pro Projekt",
      note: "Einzelcarport als Maßanfertigung; Doppelcarports und Sonderformen können darüber liegen",
      sourceKey: "blauarbeitCarport2026",
    },
    {
      name: "Carport integrierter Geräteraum Aufpreis",
      low: 1000,
      high: 3000,
      unit: "pro Projekt",
      sourceKey: "blauarbeitCarport2026",
    },
    {
      name: "Carport Fundamente komplett",
      low: 600,
      high: 2000,
      unit: "pro Projekt",
      note: "Typischer Zusatzposten für Punktfundamente; Anzahl der Stützen und Bodenverhältnisse beeinflussen den Preis",
      sourceKey: "blauarbeitCarport2026",
    },
    {
      name: "Carport Punktfundament",
      low: 100,
      high: 250,
      unit: "pro Stück",
      note: "Aushub, Beton und Pfostenanker je Fundamentpunkt als Richtwert",
      sourceKey: "blauarbeitCarport2026",
    },
    {
      name: "Carport Stellfläche Pflaster Schotterrasen oder Betonplatte",
      low: 1000,
      high: 3000,
      unit: "pro Projekt",
      note: "Zusätzlicher Bodenaufbau unter dem Carport je nach Fläche und Ausführung",
      sourceKey: "blauarbeitCarport2026",
    },
    {
      name: "Carport Satteldach Aufpreis",
      low: 500,
      high: 1500,
      unit: "pro Projekt",
      sourceKey: "blauarbeitCarport2026",
    },
    {
      name: "Holzcarport",
      low: 500,
      high: 7500,
      unit: "pro Projekt",
      note: "Breite Material- und Qualitätsbandbreite vom einfachen Holzcarport bis zur hochwertigen Ausführung",
      sourceKey: "myhammerCarport2026",
    },
    {
      name: "Aluminium Einzelcarport",
      low: 1200,
      high: 6000,
      unit: "pro Projekt",
      sourceKey: "myhammerCarport2026",
    },
    {
      name: "Aluminium Doppelcarport",
      low: 3500,
      high: 10000,
      unit: "pro Projekt",
      sourceKey: "myhammerCarport2026",
    },
  ],
};

const garageService: Service = {
  slug: "garage",
  title: "Garage bauen Kosten 2026",
  shortTitle: "Garage",
  description: "Aktuelle Richtwerte 2026 für Einzel- und Doppelgarage, Fertiggarage, Massivgarage, Fundament, Erdarbeiten, Dach, Tor, Elektrik und Montage in Deutschland.",
  unit: "m² / Projekt",
  icon: "▣",
  priceItems: [
    {
      name: "Garage Gesamtprojekt",
      low: 7000,
      high: 30000,
      unit: "pro Projekt",
      note: "Breiter deutscher Richtwert je nach Größe, Material und Bauweise",
      sourceKey: "myhammerGarage2026",
    },
    {
      name: "Einzelgarage",
      low: 7000,
      high: 15000,
      unit: "pro Projekt",
      sourceKey: "myhammerGarage2026",
    },
    {
      name: "Doppelgarage",
      low: 12000,
      high: 30000,
      unit: "pro Projekt",
      sourceKey: "myhammerGarage2026",
    },
    {
      name: "Garage als Anbau",
      low: 10000,
      high: 20000,
      unit: "pro Projekt",
      sourceKey: "myhammerGarage2026",
    },
    {
      name: "Fertiggarage allgemeiner Richtwert",
      low: 5000,
      high: 12000,
      unit: "pro Projekt",
      sourceKey: "myhammerGarage2026",
    },
    {
      name: "Garage Fundament Zusatzkosten",
      low: 2000,
      high: 5000,
      unit: "pro Projekt",
      sourceKey: "myhammerGarage2026",
    },
    {
      name: "Garagentor inklusive Montage",
      low: 1500,
      high: 4000,
      unit: "pro Projekt",
      sourceKey: "myhammerGarage2026",
    },
    {
      name: "Garage Elektroinstallation",
      low: 800,
      high: 2000,
      unit: "pro Projekt",
      sourceKey: "myhammerGarage2026",
    },
    {
      name: "Garage Erdarbeiten",
      low: 30,
      high: 60,
      unit: "pro m²",
      note: "Aushub und Vorbereitung des Baugrundes",
      sourceKey: "myhammerGarage2026",
    },
    {
      name: "Garage Fundamenterstellung",
      low: 50,
      high: 100,
      unit: "pro m²",
      note: "Betonieren und Bewehrung als allgemeiner Bauleistungs-Richtwert",
      sourceKey: "myhammerGarage2026",
    },
    {
      name: "Garage Mauerarbeiten",
      low: 40,
      high: 80,
      unit: "pro m²",
      sourceKey: "myhammerGarage2026",
    },
    {
      name: "Garage Dacharbeiten",
      low: 50,
      high: 150,
      unit: "pro m²",
      sourceKey: "myhammerGarage2026",
    },
    {
      name: "Fertiggarage Einzelgarage",
      low: 4000,
      high: 15000,
      unit: "pro Projekt",
      note: "Typische Fertiggarage für ein Fahrzeug vor Fundament und Montage je nach Anbieter",
      sourceKey: "aroundhomeFertiggarage2026",
    },
    {
      name: "Fertiggarage Doppelgarage",
      low: 8000,
      high: 20000,
      unit: "pro Projekt",
      sourceKey: "aroundhomeFertiggarage2026",
    },
    {
      name: "Fertiggarage Großraumgarage",
      low: 9000,
      high: 25000,
      unit: "pro Projekt",
      sourceKey: "aroundhomeFertiggarage2026",
    },
    {
      name: "Fertiggarage Montage",
      low: 1000,
      high: 6000,
      unit: "pro Projekt",
      note: "Montagekosten je nach Größe und Anbieter",
      sourceKey: "aroundhomeFertiggarage2026",
    },
    {
      name: "Fertiggarage mit Fundament",
      low: 5200,
      high: 34000,
      unit: "pro Projekt",
      sourceKey: "aroundhomeFertiggarage2026",
    },
    {
      name: "Fertiggarage mit Montage und Fundament",
      low: 6200,
      high: 34000,
      unit: "pro Projekt",
      note: "Gesamtrahmen abhängig von Größe, Material und Montageaufwand",
      sourceKey: "aroundhomeFertiggarage2026",
    },
    {
      name: "Holz Fertiggarage 3 x 6 m komplett",
      low: 5900,
      high: 5900,
      unit: "pro Projekt",
      note: "Preisbeispiel inklusive Fundament sowie Lieferung und Montage",
      sourceKey: "aroundhomeFertiggarage2026",
    },
    {
      name: "Stahl Fertiggarage 3 x 6 m komplett",
      low: 6900,
      high: 6900,
      unit: "pro Projekt",
      note: "Preisbeispiel inklusive Fundament sowie Lieferung und Montage",
      sourceKey: "aroundhomeFertiggarage2026",
    },
    {
      name: "Beton Fertiggarage 3 x 6 m komplett",
      low: 10800,
      high: 10800,
      unit: "pro Projekt",
      note: "Preisbeispiel inklusive Fundament sowie Lieferung und Montage",
      sourceKey: "aroundhomeFertiggarage2026",
    },
    {
      name: "Fertiggarage Langgarage 3 x 9 m",
      low: 8000,
      high: 20000,
      unit: "pro Projekt",
      sourceKey: "aroundhomeFertiggarage2026",
    },
    {
      name: "Fertiggarage 6 x 9 m",
      low: 8000,
      high: 25000,
      unit: "pro Projekt",
      sourceKey: "aroundhomeFertiggarage2026",
    },
    {
      name: "Gemauerte Massivgarage",
      low: 20000,
      high: 40000,
      unit: "pro Projekt",
      note: "Inklusive Material- und Arbeitskosten als breiter Richtwert",
      sourceKey: "aroundhomeMassivgarage2026",
    },
    {
      name: "Gemauerte Massivgarage Fachbetrieb",
      low: 800,
      high: 1100,
      unit: "pro m²",
      note: "Inklusive Fundament, Material und Arbeitskosten",
      sourceKey: "aroundhomeMassivgarage2026",
    },
    {
      name: "Gemauerte Massivgarage Selbstbau",
      low: 400,
      high: 600,
      unit: "pro m²",
      sourceKey: "aroundhomeMassivgarage2026",
    },
    {
      name: "Gemauerte Doppelgarage",
      low: 29000,
      high: 40000,
      unit: "pro Projekt",
      note: "Fachmännisch gemauerte Doppelgarage mit etwa 36 m² Grundfläche",
      sourceKey: "aroundhomeMassivgarage2026",
    },
    {
      name: "Massivgarage Bodenplatte Fundament",
      low: 100,
      high: 150,
      unit: "pro m²",
      sourceKey: "aroundhomeMassivgarage2026",
    },
    {
      name: "Garage Bodengutachten",
      low: 500,
      high: 1000,
      unit: "pro Projekt",
      note: "Zusatzkosten, wenn für das Fundament ein Bodengutachten benötigt wird",
      sourceKey: "aroundhomeMassivgarage2026",
    },
    {
      name: "Massivgarage Dach komplett",
      low: 4000,
      high: 8000,
      unit: "pro Projekt",
      note: "Unterkonstruktion, Dachbelag und Entwässerung abhängig von Größe und Dachform",
      sourceKey: "aroundhomeMassivgarage2026",
    },
  ],
};

export const services: Service[] = [...inheritedServices, carportService, garageService];

export { regions, renovationModel };

export function getService(slug: string) {
  return services.find((service) => service.slug === slug);
}

export function getRegion(slug: string) {
  return regions.find((region) => region.slug === slug);
}
