import type { Guide } from "@/lib/guides";

export const elektrikerExpansionGuides: Guide[] = [
  {
    slug: "elektriker-anfahrt-kosten",
    title: "Elektriker Anfahrt Kosten 2026",
    h1: "Elektriker Anfahrt Kosten 2026: Pauschale pro Einsatz",
    description: "Elektriker Anfahrt Kosten 2026: aktueller Richtwert pro Einsatz, Entfernung, Mindestpauschale und Abgrenzung zum Stundensatz.",
    eyebrow: "Elektriker Anfahrt 2026",
    intro: "Neben Arbeitszeit und Material kann ein Elektriker eine separate Anfahrt berechnen. Gerade bei kleinen Aufträgen wirkt sich diese Pauschale spürbar auf den Gesamtpreis aus. Deshalb sollte sie beim Angebotsvergleich separat ausgewiesen werden.",
    keyFact: "Elektriker Anfahrt etwa 30-70 € pro Einsatz",
    sections: [
      { heading: "Was kostet die Anfahrt eines Elektrikers?", paragraphs: ["Für typische zusätzliche Anfahrtskosten führt BauKostenRadar aktuell etwa 30 bis 70 Euro pro Einsatz. Entfernung und Betrieb können den Betrag verändern.", "Die Anfahrt ist nicht mit dem Elektriker-Stundensatz identisch und kann zusätzlich zur Arbeitszeit berechnet werden."], table: { headers: ["Elektriker-Kostenblock", "Richtwert 2026"], rows: [{ cells: ["Elektriker Anfahrt", "30-70 € pro Einsatz"], href: "/kosten/elektriker/leistung/elektriker-anfahrt" }, { cells: ["Elektriker Stundensatz", "siehe aktuelles Preisdetail"], href: "/kosten/elektriker/leistung/elektriker-stundensatz" }] } },
      { heading: "Wovon hängt die Anfahrt ab?", paragraphs: ["Betrieb und Entfernung bestimmen, ob eine feste Pauschale oder eine andere Abrechnung verwendet wird."], bullets: ["Entfernung zum Einsatzort", "betriebliche Anfahrtspauschale", "kleiner Einzelauftrag oder größeres Projekt", "Notdienst beziehungsweise Sonderzeiten", "mehrere Termine für denselben Auftrag"] },
      { heading: "Bei Kleinaufträgen Gesamtpreis vergleichen", paragraphs: ["Bei einer einzelnen Steckdose oder kleinen Reparatur kann die Anfahrt einen großen Anteil der Rechnung ausmachen. Deshalb ist der Gesamtpreis aus Anfahrt, Arbeitszeit und Material aussagekräftiger als nur der Stundenlohn."] },
    ],
    faqs: [
      { question: "Was kostet die Elektriker-Anfahrt?", answer: "BauKostenRadar führt aktuell etwa 30 bis 70 Euro pro Einsatz als typische zusätzliche Anfahrtskosten." },
      { question: "Ist Anfahrt im Stundensatz enthalten?", answer: "Nicht automatisch. Viele Betriebe weisen die Anfahrt separat aus." },
      { question: "Warum ist Anfahrt bei kleinen Arbeiten wichtig?", answer: "Bei kurzen Einsätzen kann die Pauschale einen vergleichsweise großen Teil der Gesamtrechnung ausmachen." },
    ],
    related: [
      { label: "Elektriker Anfahrt Preisdetail", href: "/kosten/elektriker/leistung/elektriker-anfahrt" },
      { label: "Handwerker Stundensätze", href: "/ratgeber/handwerker-stundensaetze" },
      { label: "Steckdose installieren Kosten", href: "/ratgeber/steckdose-installieren-kosten" },
      { label: "Anfahrt berechnen", href: "/rechner/handwerkerkosten?gewerk=elektriker&leistung=elektriker-anfahrt" },
    ],
  },
  {
    slug: "fi-schutzschalter-nachruesten-kosten",
    title: "FI-Schutzschalter nachrüsten Kosten 2026",
    h1: "FI-Schutzschalter nachrüsten: Kosten 2026 pro Stück",
    description: "FI-Schutzschalter nachrüsten Kosten 2026: aktueller Richtwert pro Stück, Verteilerzustand und mögliche Zusatzarbeiten.",
    eyebrow: "FI-Schutzschalter 2026",
    intro: "Ein FI- beziehungsweise RCD-Schutzschalter ist ein wichtiger Bestandteil moderner Elektroinstallationen. Bei älteren Anlagen kann eine Nachrüstung sinnvoll oder im Zuge weiterer Arbeiten erforderlich sein. Der Aufwand hängt vom vorhandenen Verteiler ab.",
    keyFact: "FI-Schutzschalter nachrüsten etwa 150-300 € pro Stück",
    sections: [
      { heading: "Was kostet FI-Schutzschalter nachrüsten?", paragraphs: ["Für die Nachrüstung eines FI-Schutzschalters führt BauKostenRadar aktuell etwa 150 bis 300 Euro pro Stück.", "Wenn der vorhandene Sicherungskasten keinen geeigneten Platz bietet oder technisch erneuert werden muss, entstehen zusätzliche Kosten."], table: { headers: ["Elektroarbeit", "Richtwert 2026"], rows: [{ cells: ["FI-Schutzschalter nachrüsten", "150-300 € pro Stück"], href: "/kosten/elektriker/leistung/fi-schutzschalter-nachruesten" }, { cells: ["Sicherungskasten erneuern", "siehe aktuelles Preisdetail"], href: "/kosten/elektriker/leistung/sicherungskasten-erneuern" }] } },
      { heading: "Welche Zusatzarbeiten können nötig sein?", paragraphs: ["Der Zustand der bestehenden Verteilung ist für den Projektpreis entscheidend."], bullets: ["Platz im Verteiler", "Zustand der Verdrahtung", "Aufteilung vorhandener Stromkreise", "Messung und Prüfung", "Erneuerung weiterer Schutzorgane", "gegebenenfalls neuer Sicherungskasten"] },
      { heading: "Nachrüstung mit Verteilerarbeiten abstimmen", paragraphs: ["Wenn ohnehin ein Sicherungskasten erneuert oder die Elektrik saniert wird, sollte die Schutztechnik als Teil des Gesamtprojekts geplant werden. So werden Arbeiten nicht doppelt kalkuliert."] },
    ],
    faqs: [
      { question: "Was kostet ein FI-Schutzschalter nachrüsten?", answer: "Der aktuelle BauKostenRadar-Richtwert liegt bei etwa 150 bis 300 Euro pro Stück." },
      { question: "Muss der Sicherungskasten erneuert werden?", answer: "Nicht immer. Das hängt von Zustand, Platz und technischer Eignung des vorhandenen Verteilers ab." },
      { question: "Ist Prüfung enthalten?", answer: "Der konkrete Leistungsumfang muss im Angebot stehen; Mess- und Prüfleistungen sollten ausdrücklich geklärt werden." },
    ],
    related: [
      { label: "FI Preisdetail", href: "/kosten/elektriker/leistung/fi-schutzschalter-nachruesten" },
      { label: "Sicherungskasten erneuern Kosten", href: "/ratgeber/sicherungskasten-erneuern-kosten" },
      { label: "Elektrik Altbau erneuern", href: "/ratgeber/elektrik-erneuern-altbau" },
      { label: "FI-Nachrüstung berechnen", href: "/rechner/handwerkerkosten?gewerk=elektriker&leistung=fi-schutzschalter-nachruesten" },
    ],
  },
  {
    slug: "elektroinstallation-neubau-kosten-pro-qm",
    title: "Elektroinstallation Neubau Kosten pro m² 2026",
    h1: "Elektroinstallation im Neubau: Kosten 2026 pro m² Wohnfläche",
    description: "Elektroinstallation Neubau Kosten 2026 pro m² Wohnfläche: aktueller Richtwert, Ausstattungsniveau, Verteiler, Leitungen und Smart Home.",
    eyebrow: "Elektroinstallation Neubau 2026",
    intro: "Im Neubau lässt sich die Elektroinstallation von Anfang an nach Raumplanung, Steckdosenbedarf, Beleuchtung, Netzwerk und späterer Technik auslegen. Die Zahl der Stromkreise und das Ausstattungsniveau beeinflussen den Quadratmeterpreis deutlich.",
    keyFact: "Elektroinstallation Neubau etwa 80-150 €/m² Wohnfläche",
    sections: [
      { heading: "Was kostet Elektroinstallation im Neubau 2026?", paragraphs: ["Für eine komplette Elektroinstallation im Neubau führt BauKostenRadar aktuell etwa 80 bis 150 Euro pro Quadratmeter Wohnfläche.", "Der Richtwert umfasst eine flächenbezogene Orientierung. Sehr hohe Ausstattungsstandards, Smart Home oder umfangreiche Netzwerk- und Ladeinfrastruktur können das Budget erhöhen."], table: { headers: ["Elektroprojekt", "Richtwert 2026"], rows: [{ cells: ["Elektroinstallation Neubau", "80-150 €/m² Wohnfläche"], href: "/kosten/elektriker/leistung/elektroinstallation-neubau" }] } },
      { heading: "Was gehört in die Neubauplanung?", paragraphs: ["Die Zahl und Lage der Anschlüsse sollte vor Rohinstallation möglichst vollständig feststehen."], bullets: ["Stromkreise und Unterverteilung", "Steckdosen und Lichtauslässe", "Netzwerk und Kommunikation", "Küche und starke Verbraucher", "Wallbox-Vorbereitung", "PV, Speicher und Smart Home"] },
      { heading: "Neubau und Altbau nicht direkt gleichsetzen", paragraphs: ["Bei einer Altbausanierung entstehen zusätzlich Rückbau, schwierige Leitungswege und Wiederherstellungsarbeiten. Deshalb sollten Neubau-Quadratmeterpreise nicht unverändert auf Bestandsgebäude übertragen werden."] },
    ],
    faqs: [
      { question: "Was kostet Elektroinstallation im Neubau pro m²?", answer: "BauKostenRadar führt aktuell etwa 80 bis 150 Euro pro Quadratmeter Wohnfläche." },
      { question: "Ist Smart Home enthalten?", answer: "Nicht automatisch. Umfangreiche Smart-Home-Ausstattung kann als eigener Projektblock hinzukommen." },
      { question: "Kann ich den Wert auf Altbau anwenden?", answer: "Nicht direkt. Altbauprojekte haben andere Kostenblöcke für Rückbau, Leitungswege und Wiederherstellung." },
    ],
    related: [
      { label: "Neubau-Elektro Preisdetail", href: "/kosten/elektriker/leistung/elektroinstallation-neubau" },
      { label: "Elektro-Neuinstallation Kosten", href: "/ratgeber/elektro-neuinstallation-kosten" },
      { label: "Smart Home Kosten", href: "/ratgeber/smart-home-einrichtung-kosten" },
      { label: "Neubau-Elektrik berechnen", href: "/rechner/handwerkerkosten?gewerk=elektriker&leistung=elektroinstallation-neubau" },
    ],
  },
  {
    slug: "smart-home-einrichtung-kosten",
    title: "Smart Home Einrichtung Kosten 2026",
    h1: "Smart Home Einrichtung Kosten 2026: Elektro-Projekt richtig kalkulieren",
    description: "Smart Home Einrichtung Kosten 2026: aktueller Projekt-Richtwert, Umfang, Sensoren, Aktoren, Steuerung und Elektroinstallation.",
    eyebrow: "Smart Home 2026",
    intro: "Smart Home kann von wenigen vernetzten Funktionen bis zu einer umfassenden Gebäudeautomation reichen. Der Preis hängt deshalb stärker vom Funktionsumfang als von einer einzelnen Gerätezahl ab.",
    keyFact: "Smart Home Einrichtung etwa 500-3.000 € pro Projekt als Basis-Richtwert",
    sections: [
      { heading: "Was kostet Smart Home Einrichtung 2026?", paragraphs: ["Für eine typische Smart-Home-Einrichtung führt BauKostenRadar aktuell etwa 500 bis 3.000 Euro pro Projekt.", "Größere kabelgebundene Systeme, viele Aktoren oder umfangreiche Automationen können oberhalb dieser Orientierung liegen."], table: { headers: ["Elektroprojekt", "Richtwert 2026"], rows: [{ cells: ["Smart Home Einrichtung", "500-3.000 € pro Projekt"], href: "/kosten/elektriker/leistung/smart-home-einrichtung" }] } },
      { heading: "Welche Funktionen verändern das Budget?", paragraphs: ["Ein klarer Funktionskatalog macht Angebote vergleichbar."], bullets: ["Lichtsteuerung", "Rollläden und Beschattung", "Heizung und Raumtemperatur", "Sensoren", "Energiemanagement", "Zutritt und Sicherheit", "Visualisierung und App-Steuerung"] },
      { heading: "Smart Home im Neubau früh planen", paragraphs: ["Bei einem Neubau lassen sich Leitungen, Verteiler und Platzreserven von Anfang an berücksichtigen. Nachträgliche Änderungen im Bestand können zusätzlichen Installationsaufwand verursachen."] },
    ],
    faqs: [
      { question: "Was kostet Smart Home Einrichtung?", answer: "Als Basis-Richtwert führt BauKostenRadar aktuell etwa 500 bis 3.000 Euro pro Projekt." },
      { question: "Sind Geräte enthalten?", answer: "Der konkrete Lieferumfang variiert stark. Angebote sollten Hardware, Installation und Konfiguration getrennt oder eindeutig als Paket ausweisen." },
      { question: "Kann Smart Home deutlich teurer werden?", answer: "Ja. Umfangreiche Gebäudeautomation mit vielen Funktionen kann den Basis-Richtwert deutlich überschreiten." },
    ],
    related: [
      { label: "Smart Home Preisdetail", href: "/kosten/elektriker/leistung/smart-home-einrichtung" },
      { label: "Elektroinstallation Neubau", href: "/ratgeber/elektroinstallation-neubau-kosten-pro-qm" },
      { label: "Elektrik erneuern Kosten", href: "/ratgeber/elektrik-erneuern-altbau" },
      { label: "Smart Home berechnen", href: "/rechner/handwerkerkosten?gewerk=elektriker&leistung=smart-home-einrichtung" },
    ],
  },
  {
    slug: "wallbox-installieren-kosten",
    title: "Wallbox installieren Kosten 2026",
    h1: "E-Auto Wallbox installieren: Kosten 2026 pro Projekt",
    description: "Wallbox installieren Kosten 2026: aktueller Projekt-Richtwert, Leitungsweg, Absicherung, Zählerschrank und mögliche Zusatzarbeiten.",
    eyebrow: "Wallbox Installation 2026",
    intro: "Die Wallbox selbst ist nur ein Teil des Ladeprojekts. Leitungsweg, Absicherung, vorhandener Zählerschrank und gewünschte Ladeleistung bestimmen den Installationsaufwand. Deshalb ist ein kompletter Projektpreis aussagekräftiger als nur der Gerätepreis.",
    keyFact: "E-Auto Wallbox installieren etwa 1.200-2.500 € pro Projekt",
    sections: [
      { heading: "Was kostet Wallbox installieren 2026?", paragraphs: ["Für eine typische Wallbox-Installation führt BauKostenRadar aktuell etwa 1.200 bis 2.500 Euro pro Projekt.", "Lange Kabelwege, Erdarbeiten, ein ungeeigneter Zählerschrank oder zusätzliche Lastmanagement-Technik können Mehrkosten verursachen."], table: { headers: ["Elektroprojekt", "Richtwert 2026"], rows: [{ cells: ["E-Auto Wallbox installieren", "1.200-2.500 € pro Projekt"], href: "/kosten/elektriker/leistung/e-auto-wallbox-installieren" }] } },
      { heading: "Welche Arbeiten beeinflussen den Preis?", paragraphs: ["Vor der Montage sollte die vorhandene Elektroanlage geprüft und der Leitungsweg geplant werden."], bullets: ["Entfernung zwischen Verteiler und Stellplatz", "Kabelquerschnitt und Ladeleistung", "Absicherung und Schutztechnik", "Zählerschrank", "Wanddurchführungen oder Erdarbeiten", "Lastmanagement und Energiemanagement"] },
      { heading: "Wallbox mit PV und Smart Home abstimmen", paragraphs: ["Wer Photovoltaik, Batteriespeicher oder Energiemanagement nutzt, kann die Ladeinfrastruktur in das Gesamtsystem einbinden. Dafür können zusätzliche Mess- und Steuerkomponenten nötig werden."] },
    ],
    faqs: [
      { question: "Was kostet eine Wallbox-Installation?", answer: "Der aktuelle BauKostenRadar-Richtwert liegt bei etwa 1.200 bis 2.500 Euro pro Projekt." },
      { question: "Ist die Wallbox selbst enthalten?", answer: "Der konkrete Lieferumfang kann je Angebot variieren. Gerät und Installation sollten eindeutig ausgewiesen werden." },
      { question: "Was macht die Installation teurer?", answer: "Lange Leitungswege, Erdarbeiten, Verteileranpassungen und zusätzliche Steuertechnik können den Preis erhöhen." },
    ],
    related: [
      { label: "Wallbox Preisdetail", href: "/kosten/elektriker/leistung/e-auto-wallbox-installieren" },
      { label: "Sicherungskasten erneuern Kosten", href: "/ratgeber/sicherungskasten-erneuern-kosten" },
      { label: "Photovoltaik Kosten", href: "/ratgeber/photovoltaik-kosten-2026" },
      { label: "Wallbox berechnen", href: "/rechner/handwerkerkosten?gewerk=elektriker&leistung=e-auto-wallbox-installieren" },
    ],
  },
];
