import type { Guide, GuideTable } from "@/lib/guides";

type QuinaryGuideConfig = {
  slug: string;
  title: string;
  h1: string;
  description: string;
  eyebrow: string;
  intro: string;
  keyFact: string;
  priceHeading: string;
  priceParagraphs: string[];
  table?: GuideTable;
  factors: string[];
  compareHeading: string;
  compareParagraphs: string[];
  faqs: Array<{ question: string; answer: string }>;
  serviceSlug: string;
  itemSlug: string;
  itemLabel: string;
  serviceLabel: string;
  parentSlug: string;
  parentLabel: string;
  relatedExtra?: Array<{ label: string; href: string }>;
};

function createGuide(config: QuinaryGuideConfig): Guide {
  return {
    slug: config.slug,
    title: config.title,
    h1: config.h1,
    description: config.description,
    eyebrow: config.eyebrow,
    intro: config.intro,
    keyFact: config.keyFact,
    sections: [
      {
        heading: config.priceHeading,
        paragraphs: config.priceParagraphs,
        ...(config.table ? { table: config.table } : {}),
      },
      {
        heading: "Welche Faktoren beeinflussen die Kosten?",
        paragraphs: ["Der Richtwert ist eine Budgetorientierung. Der konkrete Preis hängt vom Bestand, Material, Leistungsumfang und der Baustellensituation ab."],
        bullets: config.factors,
      },
      {
        heading: config.compareHeading,
        paragraphs: config.compareParagraphs,
      },
    ],
    faqs: config.faqs,
    related: [
      { label: `${config.itemLabel} Preisdetail`, href: `/kosten/${config.serviceSlug}/leistung/${config.itemSlug}` },
      { label: config.parentLabel, href: `/ratgeber/${config.parentSlug}` },
      { label: `${config.serviceLabel} Kosten`, href: `/kosten/${config.serviceSlug}` },
      ...(config.relatedExtra ?? []),
      { label: "Handwerkerkosten-Rechner", href: `/rechner/handwerkerkosten?gewerk=${config.serviceSlug}&leistung=${config.itemSlug}` },
    ],
  };
}

const configs: QuinaryGuideConfig[] = [
  {
    slug: "bad-komplett-verfliesen-kosten",
    title: "Bad komplett verfliesen Kosten 2026",
    h1: "Bad komplett verfliesen Kosten 2026: Richtwert pro Bad",
    description: "Bad komplett verfliesen Kosten 2026: BauKostenRadar-Richtwert für typische Fliesenarbeiten im Bad, Formate, Untergrund, Abdichtung und Angebotsvergleich.",
    eyebrow: "Badfliesen 2026",
    intro: "Eine Komplettverfliesung umfasst viele kleine Flächen, Kanten und Anschlüsse. Die Quadratmeterzahl allein erklärt den Preis deshalb schlechter als bei einem großen, geraden Boden.",
    keyFact: "Komplettverfliesung eines typischen Bads etwa 2.500-5.500 € für die Fliesenarbeiten in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet ein Bad komplett zu verfliesen?",
    priceParagraphs: [
      "BauKostenRadar führt für die Komplettverfliesung eines typischen Bads etwa 2.500 bis 5.500 Euro pauschal für die Fliesenarbeiten. Der Wert ist keine Komplettbadsanierung.",
      "Fliesenmaterial, Rückbau alter Beläge, Untergrundausgleich und Verbundabdichtung müssen im konkreten Angebot eindeutig als enthalten oder zusätzlich ausgewiesen sein.",
    ],
    factors: ["Fliesenformat und Verlegemuster", "Wand- und Bodenfläche", "Nischen, Ablagen und Vorwände", "Untergrundvorbereitung", "Abdichtung im Nassbereich", "Silikonfugen und Abschlussprofile"],
    compareHeading: "Fliesenpaket und komplette Badsanierung trennen",
    compareParagraphs: ["Sanitärinstallation, neue Objekte und Elektroarbeiten gehören nicht automatisch zur Fliesenposition. Angebote sind nur vergleichbar, wenn der Fliesen-Leistungsumfang separat erkennbar ist.", "Für das Gesamtprojekt sollte zusätzlich der Ratgeber zur kompletten Badsanierung genutzt werden."],
    faqs: [
      { question: "Was kostet Bad komplett verfliesen 2026?", answer: "BauKostenRadar führt etwa 2.500 bis 5.500 Euro pauschal für typische Fliesenarbeiten als Richtwert." },
      { question: "Sind neue Sanitärobjekte enthalten?", answer: "Nein. Die Preisposition beschreibt Fliesenarbeiten und nicht die komplette Sanitärinstallation." },
      { question: "Ist die Abdichtung enthalten?", answer: "Das muss im konkreten Angebot geprüft werden. BauKostenRadar führt Verbundabdichtung zusätzlich als eigene Preisposition." },
    ],
    serviceSlug: "badsanierung", itemSlug: "komplettverfliesung-bad", itemLabel: "Komplettverfliesung Bad", serviceLabel: "Badsanierung", parentSlug: "bad-komplett-sanieren-kosten", parentLabel: "Bad komplett sanieren Kosten",
    relatedExtra: [{ label: "Bad abdichten Kosten", href: "/ratgeber/bad-abdichten-kosten-pro-qm" }],
  },
  {
    slug: "bad-abdichten-kosten-pro-qm",
    title: "Bad abdichten Kosten pro m² 2026",
    h1: "Bad abdichten Kosten 2026: Verbundabdichtung pro m²",
    description: "Bad abdichten Kosten 2026 pro m²: BauKostenRadar-Richtwerte für Verbundabdichtung im Nassbereich, Untergrund, Dichtbänder und Angebotsvergleich.",
    eyebrow: "Badabdichtung 2026",
    intro: "Unter Fliesen in beanspruchten Nassbereichen schützt eine fachgerechte Verbundabdichtung den Baukörper vor Feuchtigkeit. Detailanschlüsse an Ecken, Rohrdurchführungen und Dusche sind für den Aufwand entscheidend.",
    keyFact: "Verbundabdichtung im Nassbereich etwa 25-45 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Verbundabdichtung im Bad pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Verbundabdichtung im Nassbereich etwa 25 bis 45 Euro pro Quadratmeter. Für 20 m² abzudichtende Fläche ergibt sich eine Budgetorientierung von ungefähr 500 bis 900 Euro.", "Die abzudichtende Fläche ist nicht identisch mit der Grundfläche des Bads. Dusche, Wände und weitere beanspruchte Bereiche können die relevante Fläche erhöhen."],
    table: { headers: ["Abdichtungsfläche", "Budgetorientierung"], rows: [
      { cells: ["10 m²", "250-450 €"] },
      { cells: ["20 m²", "500-900 €"] },
      { cells: ["30 m²", "750-1.350 €"] },
    ] },
    factors: ["Abdichtungsfläche", "Ecken und Wand-Boden-Anschlüsse", "Rohrdurchführungen", "Duschbereich und Nischen", "Untergrund und Grundierung", "Systemkomponenten und Dichtbänder"],
    compareHeading: "Abdichtung nicht im Fliesenpreis verstecken",
    compareParagraphs: ["Bei Fliesenangeboten sollte die Abdichtung als eigene Position oder eindeutig enthaltener Leistungsblock erkennbar sein. So lassen sich Angebote mit unterschiedlichem Aufbau besser vergleichen.", "Der eigentliche Fliesenbelag und die Verlegearbeit sind separate Kostenblöcke."],
    faqs: [
      { question: "Was kostet Bad abdichten pro m² 2026?", answer: "BauKostenRadar führt etwa 25 bis 45 Euro pro Quadratmeter für Verbundabdichtung als Richtwert." },
      { question: "Was kosten 20 m² Abdichtung?", answer: "Mit der Richtwertspanne ergeben sich ungefähr 500 bis 900 Euro als Budgetorientierung." },
      { question: "Ist die Badgrundfläche gleich der Abdichtungsfläche?", answer: "Nein. Je nach Dusche und Wandflächen kann die abzudichtende Fläche deutlich größer als die reine Bodenfläche sein." },
    ],
    serviceSlug: "badsanierung", itemSlug: "verbundabdichtung-nassbereich", itemLabel: "Verbundabdichtung Nassbereich", serviceLabel: "Badsanierung", parentSlug: "bad-komplett-sanieren-kosten", parentLabel: "Bad komplett sanieren Kosten",
    relatedExtra: [{ label: "Bad komplett verfliesen Kosten", href: "/ratgeber/bad-komplett-verfliesen-kosten" }],
  },
  {
    slug: "elektro-neuinstallation-kosten",
    title: "Elektro-Neuinstallation Kosten 2026",
    h1: "Elektro-Neuinstallation Kosten 2026: Komplettpaket richtig kalkulieren",
    description: "Elektro-Neuinstallation Kosten 2026: BauKostenRadar-Richtwert pro Projekt, Stromkreise, Sicherungskasten, Steckdosen, Leitungswege und Angebotsvergleich.",
    eyebrow: "Elektroinstallation 2026",
    intro: "Eine komplette Elektro-Neuinstallation ist ein Projektpreis und nicht mit einzelnen Steckdosen oder einem reinen Stundensatz vergleichbar. Anzahl der Stromkreise, Ausstattung und Gebäudestruktur bestimmen die Kalkulation.",
    keyFact: "Komplett-Neuinstallation Elektrik etwa 8.000-15.000 € pro Projekt in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet eine komplette Elektro-Neuinstallation?",
    priceParagraphs: ["BauKostenRadar führt für eine Komplett-Neuinstallation etwa 8.000 bis 15.000 Euro pro Projekt als Richtwert. Die Datenposition ist bewusst projektbezogen und wird nicht pauschal mit Wohnfläche multipliziert.", "Ein konkretes Angebot sollte Leitungen, Unterverteilung, Schalterprogramm, Steckdosen, Prüfungen und Dokumentation ausreichend beschreiben."],
    factors: ["Gebäudegröße und Anzahl Räume", "Anzahl Stromkreise", "Steckdosen und Lichtauslässe", "Sicherungskasten und Schutztechnik", "Unterputz- oder Aufputzführung", "Netzwerk, Smart Home und Sonderausstattung"],
    compareHeading: "Neuinstallation und Altbau-Erneuerung unterscheiden",
    compareParagraphs: ["Bei einer Neuinstallation sind Leitungswege häufig anders zugänglich als in einem bewohnten Altbau. Stemmarbeiten, Bestand und Wiederherstellung können die Kosten einer Altbau-Erneuerung anders verteilen.", "Vergleichen Sie deshalb nicht nur den Gesamtpreis, sondern auch die Zahl der Stromkreise und enthaltenen Ausstattungspositionen."],
    faqs: [
      { question: "Was kostet Elektro-Neuinstallation 2026?", answer: "BauKostenRadar führt etwa 8.000 bis 15.000 Euro pro Projekt als Richtwert." },
      { question: "Kann man den Richtwert pro m² rechnen?", answer: "Die zugrunde liegende BauKostenRadar-Preisposition ist ein Projektpreis. Eine pauschale Multiplikation mit Wohnfläche wäre daher nicht sachgerecht." },
      { question: "Sind Steckdosen und Sicherungskasten enthalten?", answer: "Bei einer Komplett-Neuinstallation gehören solche Komponenten typischerweise zum Projekt, der genaue Umfang muss aber im Angebot ausdrücklich beschrieben sein." },
    ],
    serviceSlug: "elektriker", itemSlug: "komplett-neuinstallation", itemLabel: "Komplett-Neuinstallation", serviceLabel: "Elektrik", parentSlug: "elektrik-erneuern-altbau", parentLabel: "Elektrik erneuern Kosten",
    relatedExtra: [{ label: "Sicherungskasten erneuern Kosten", href: "/ratgeber/sicherungskasten-erneuern-kosten" }, { label: "Steckdose installieren Kosten", href: "/ratgeber/steckdose-installieren-kosten" }],
  },
  {
    slug: "dachsanierung-aufsparrendaemmung-kosten-pro-qm",
    title: "Dachsanierung mit Aufsparrendämmung Kosten pro m² 2026",
    h1: "Dachsanierung mit Aufsparrendämmung Kosten 2026",
    description: "Dachsanierung mit Aufsparrendämmung Kosten 2026 pro m²: BauKostenRadar-Richtwerte für das kombinierte Dachpaket, Gerüst, Eindeckung und Angebotsvergleich.",
    eyebrow: "Dach + Dämmung 2026",
    intro: "Wird eine Aufsparrendämmung im Zuge der Dachsanierung eingebaut, entsteht ein größeres Leistungspaket als bei einer reinen Dämmmaßnahme von innen. Eindeckung, Dachaufbau und Anschlüsse werden gemeinsam relevant.",
    keyFact: "Dachsanierung inklusive Aufsparrendämmung etwa 250-450 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Dachsanierung inklusive Aufsparrendämmung pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Dachsanierung inklusive Aufsparrendämmung etwa 250 bis 450 Euro pro Quadratmeter. Für 150 m² Dachfläche ergibt sich daraus eine erste Orientierung von ungefähr 37.500 bis 67.500 Euro.", "Gerüst, Zustand des Dachstuhls, Eindeckungsmaterial und Detailanschlüsse können den konkreten Umfang verändern. Die Position ist nicht mit einer reinen Aufsparrendämmung ohne vollständige Dachsanierung gleichzusetzen."],
    table: { headers: ["Dachfläche", "Budgetorientierung"], rows: [
      { cells: ["100 m²", "25.000-45.000 €"] },
      { cells: ["150 m²", "37.500-67.500 €"] },
      { cells: ["200 m²", "50.000-90.000 €"] },
    ] },
    factors: ["Dachfläche und Geometrie", "Zustand von Lattung und Dachstuhl", "Dämmstärke und System", "Neueindeckung und Dachziegel", "Gauben, Fenster und Anschlüsse", "Gerüst und Baustellenzugang"],
    compareHeading: "Komplettpaket nicht mit reiner Dämmung verwechseln",
    compareParagraphs: ["BauKostenRadar führt zusätzlich eine separate Preisposition für reine Aufsparrendämmung. Der kombinierte Sanierungswert ist höher, weil weitere Dacharbeiten dazugehören.", "Angebote sollten Dämmung, Unterdeckbahn, Lattung, Eindeckung, Spenglerarbeiten und Gerüst eindeutig trennen oder als vollständiges Paket beschreiben."],
    faqs: [
      { question: "Was kostet Dachsanierung mit Aufsparrendämmung pro m² 2026?", answer: "BauKostenRadar führt etwa 250 bis 450 Euro pro Quadratmeter als Richtwert." },
      { question: "Was kosten 150 m² Dach?", answer: "Mit der Richtwertspanne ergeben sich ungefähr 37.500 bis 67.500 Euro als Budgetorientierung." },
      { question: "Ist das dieselbe Position wie reine Aufsparrendämmung?", answer: "Nein. Diese Position beschreibt eine Dachsanierung inklusive Aufsparrendämmung und damit einen breiteren Leistungsumfang." },
    ],
    serviceSlug: "dachsanierung", itemSlug: "dachsanierung-inkl-aufsparrendaemmung", itemLabel: "Dachsanierung inkl. Aufsparrendämmung", serviceLabel: "Dachsanierung", parentSlug: "dach-sanieren-kosten-pro-qm", parentLabel: "Dach sanieren Kosten pro m²",
    relatedExtra: [{ label: "Reine Aufsparrendämmung Kosten", href: "/ratgeber/aufsparrendaemmung-kosten-pro-qm" }, { label: "Dach neu eindecken Kosten", href: "/ratgeber/dach-neu-eindecken-kosten-pro-qm" }],
  },
  {
    slug: "photovoltaik-5-kwp-kosten",
    title: "Photovoltaik 5 kWp Kosten 2026",
    h1: "Photovoltaik 5 kWp Kosten 2026: Startpreis richtig einordnen",
    description: "Photovoltaik 5 kWp Kosten 2026: BauKostenRadar-Startpreis aus der Datenquelle, Installation, Komponenten, Dachaufwand und Vergleich mit 10 kWp.",
    eyebrow: "PV 5 kWp 2026",
    intro: "Eine 5-kWp-Anlage kann für kleinere Dachflächen oder niedrigeren Strombedarf interessant sein. Die BauKostenRadar-Datenbasis enthält für diese Größe einen Startpreis statt einer belastbaren Preisspanne, daher wird kein künstlicher Korridor daraus abgeleitet.",
    keyFact: "PV-Anlage 5 kWp inklusive Installation: 8.634 € Startpreis laut hinterlegter Quelle",
    priceHeading: "Was kostet eine 5-kWp-Photovoltaikanlage?",
    priceParagraphs: ["Für eine PV-Anlage mit 5 kWp inklusive Installation ist in der BauKostenRadar-Datenbasis ein Startpreis von 8.634 Euro hinterlegt. Weil die Quelle keinen oberen Richtwert liefert, stellt BauKostenRadar diesen Wert bewusst nicht als typische Marktspanne dar.", "Für die tatsächliche Angebotsbewertung sind Module, Wechselrichter, Montagesystem, Gerüst, Elektroarbeiten, Anmeldung und ein möglicher Speicher entscheidend."],
    factors: ["Modul- und Wechselrichterklasse", "Dachform und Belegbarkeit", "Gerüst und Absturzsicherung", "Zählerschrank und Elektrik", "Leitungswege", "Optionaler Stromspeicher"],
    compareHeading: "5 kWp nicht nur am Gesamtpreis messen",
    compareParagraphs: ["Kleinere Anlagen haben häufig höhere Fixkosten pro kWp. Deshalb sollte neben dem Gesamtpreis auch der enthaltene Leistungsumfang betrachtet werden.", "Für 10 und 15 kWp führt BauKostenRadar separate Richtwertseiten mit anderen Datenpositionen."],
    faqs: [
      { question: "Was kostet Photovoltaik 5 kWp 2026?", answer: "Die BauKostenRadar-Datenbasis enthält einen Startpreis von 8.634 Euro inklusive Installation. Daraus wird bewusst keine künstliche Preisspanne abgeleitet." },
      { question: "Ist ein Stromspeicher enthalten?", answer: "Die 5-kWp-Preisposition nennt eine Anlage inklusive Installation. Ein Speicher ist nicht ausdrücklich Bestandteil und sollte separat geprüft werden." },
      { question: "Warum gibt es keine obere Preisspanne?", answer: "Die hinterlegte Quelle nennt für diese Größe einen Startpreis. BauKostenRadar ergänzt keinen nicht belegten oberen Wert." },
    ],
    serviceSlug: "photovoltaik", itemSlug: "pv-anlage-5-kwp-inkl-installation", itemLabel: "PV-Anlage 5 kWp inkl. Installation", serviceLabel: "Photovoltaik", parentSlug: "photovoltaik-kosten-2026", parentLabel: "Photovoltaik Kosten 2026",
    relatedExtra: [{ label: "Photovoltaik 10 kWp Kosten", href: "/ratgeber/photovoltaik-10-kwp-kosten" }, { label: "Photovoltaik 15 kWp Kosten", href: "/ratgeber/photovoltaik-15-kwp-kosten" }],
  },
  {
    slug: "fassade-streichen-kosten-pro-qm",
    title: "Fassade streichen Kosten pro m² 2026",
    h1: "Fassade streichen Kosten 2026: inklusive Vorarbeiten",
    description: "Fassade streichen Kosten 2026 pro m²: BauKostenRadar-Richtwerte inklusive Vorarbeiten, Untergrund, Gerüst, Anstrichsystem und Angebotsvergleich.",
    eyebrow: "Fassadenanstrich 2026",
    intro: "Ein Fassadenanstrich besteht nicht nur aus Farbe. Reinigung, Ausbesserung, Grundierung und Abkleben können einen wesentlichen Teil der Arbeit ausmachen.",
    keyFact: "Fassade streichen inklusive Vorarbeiten etwa 30-60 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Fassade streichen pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Fassade streichen inklusive Vorarbeiten etwa 30 bis 60 Euro pro Quadratmeter. Bei 150 m² Fassadenfläche entspricht das ungefähr 4.500 bis 9.000 Euro als Budgetorientierung.", "Ein Gerüst kann abhängig vom Angebot ein separater Kostenblock sein. Bei starken Rissen oder schadhaften Putzflächen reicht ein normaler Anstrich nicht aus."],
    table: { headers: ["Fassadenfläche", "Budgetorientierung"], rows: [
      { cells: ["100 m²", "3.000-6.000 €"] },
      { cells: ["150 m²", "4.500-9.000 €"] },
      { cells: ["200 m²", "6.000-12.000 €"] },
    ] },
    factors: ["Untergrundzustand", "Reinigung und Grundierung", "Riss- und Putzreparaturen", "Anzahl Anstriche", "Farb- und Beschichtungssystem", "Gerüst und Gebäudehöhe"],
    compareHeading: "Anstrich, Risssanierung und Neuputz unterscheiden",
    compareParagraphs: ["Ein intakter Putz mit neuem Anstrich ist ein anderer Leistungsumfang als eine Fassadensanierung mit Rissreparatur oder vollständigem Neuputz.", "Gerüst und Vorarbeiten sollten in jedem Angebot klar erkennbar sein, damit der Quadratmeterpreis sinnvoll verglichen werden kann."],
    faqs: [
      { question: "Was kostet Fassade streichen pro m² 2026?", answer: "BauKostenRadar führt etwa 30 bis 60 Euro pro Quadratmeter inklusive Vorarbeiten als Richtwert." },
      { question: "Was kosten 150 m² Fassade streichen?", answer: "Mit der Richtwertspanne ergeben sich ungefähr 4.500 bis 9.000 Euro als Budgetorientierung." },
      { question: "Ist ein Gerüst enthalten?", answer: "Nicht automatisch. Gerüstkosten sollten im konkreten Angebot ausdrücklich geprüft werden." },
    ],
    serviceSlug: "fassade", itemSlug: "fassade-streichen-inkl-vorarbeiten", itemLabel: "Fassade streichen inkl. Vorarbeiten", serviceLabel: "Fassade", parentSlug: "fassade-sanieren-kosten", parentLabel: "Fassade sanieren Kosten",
    relatedExtra: [{ label: "Fassadenrisse sanieren Kosten", href: "/ratgeber/fassadenrisse-sanieren-kosten-pro-qm" }, { label: "Gerüst Kosten", href: "/ratgeber/geruest-kosten-pro-qm" }],
  },
  {
    slug: "klinkerfassade-kosten-pro-qm",
    title: "Klinkerfassade Kosten pro m² 2026",
    h1: "Klinkerfassade Kosten 2026: Verblendung und Mauerwerk vergleichen",
    description: "Klinkerfassade Kosten 2026 pro m²: BauKostenRadar-Richtwerte für Fassaden-Verblendung und Klinker-Verblendmauerwerk, Aufbau und Angebotsvergleich.",
    eyebrow: "Klinker 2026",
    intro: "Bei Klinkerpreisen muss unterschieden werden, ob eine Fassaden-Verblendung als kompletter Fassadenaufbau oder ein Mauerwerks-Preisdetail gemeint ist. BauKostenRadar führt dafür zwei unterschiedliche Datenpositionen.",
    keyFact: "Klinker-Verblendung Fassade etwa 120-280 €/m²; Klinker-Verblendmauerwerk etwa 90-160 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet eine Klinkerfassade pro m²?",
    priceParagraphs: ["Für die Fassaden-Preisposition Klinker-Verblendung führt BauKostenRadar etwa 120 bis 280 Euro pro Quadratmeter. Im Maurer-Katalog liegt Klinker-Verblendmauerwerk bei etwa 90 bis 160 Euro pro Quadratmeter.", "Die Werte sind nicht austauschbar: Leistungsumfang, Unterkonstruktion, Dämmung, Fugen und Gerüst müssen im konkreten Angebot geprüft werden."],
    table: { headers: ["Preisposition", "Richtwert"], rows: [
      { cells: ["Klinker-Verblendung Fassade", "120-280 €/m²"] },
      { cells: ["Klinker-Verblendmauerwerk", "90-160 €/m²"] },
    ] },
    factors: ["Klinker- oder Riemchenmaterial", "Untergrund und Wandaufbau", "Dämmung und Luftschicht", "Fugenbild und Verfugung", "Fensterlaibungen und Ecken", "Gerüst und Gebäudehöhe"],
    compareHeading: "Nur gleiche Klinker-Aufbauten vergleichen",
    compareParagraphs: ["Ein Mauerwerksrichtwert kann einen anderen Aufbau abdecken als eine vollständige Fassaden-Verblendung. Der niedrigere Quadratmeterpreis ist daher nicht automatisch das günstigere Gesamtprojekt.", "Fordern Sie eine klare Beschreibung von Material, Dämmung, Unterkonstruktion, Fugen und Nebenarbeiten."],
    faqs: [
      { question: "Was kostet eine Klinkerfassade pro m² 2026?", answer: "BauKostenRadar führt für Klinker-Verblendung an der Fassade etwa 120 bis 280 Euro pro Quadratmeter. Eine separate Maurer-Position für Verblendmauerwerk liegt bei 90 bis 160 Euro." },
      { question: "Warum gibt es zwei Klinker-Richtwerte?", answer: "Die hinterlegten Datenpositionen beschreiben unterschiedliche Leistungsumfänge. Deshalb werden sie nicht zu einer künstlichen gemeinsamen Spanne vermischt." },
      { question: "Ist Dämmung enthalten?", answer: "Das hängt von der jeweiligen Leistungsbeschreibung ab. Dämmung und Unterkonstruktion müssen im konkreten Angebot geprüft werden." },
    ],
    serviceSlug: "fassade", itemSlug: "klinker-verblendung", itemLabel: "Klinker-Verblendung", serviceLabel: "Fassade", parentSlug: "fassade-sanieren-kosten", parentLabel: "Fassade sanieren Kosten",
    relatedExtra: [{ label: "Maurer Klinker-Verblendmauerwerk Preisdetail", href: "/kosten/maurer/leistung/klinker-verblendmauerwerk" }],
  },
  {
    slug: "zementestrich-kosten-pro-qm",
    title: "Zementestrich Kosten pro m² 2026",
    h1: "Zementestrich Kosten 2026: kompletter Aufbau pro m²",
    description: "Zementestrich Kosten 2026 pro m²: BauKostenRadar-Richtwerte für kompletten Aufbau mit Dämmung, Randstreifen und Einbau sowie Angebotsvergleich.",
    eyebrow: "Zementestrich 2026",
    intro: "Zementestrich ist ein verbreiteter Bodenaufbau und kann auch in feuchtebeanspruchten Bereichen eingesetzt werden. Für den Preisvergleich ist wichtig, welche Schichten im Quadratmeterpreis enthalten sind.",
    keyFact: "Zementestrich komplett etwa 25-50 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Zementestrich komplett pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Zementestrich komplett etwa 25 bis 50 Euro pro Quadratmeter. Die hinterlegte Position beschreibt einen kompletten Aufbau mit Dämmung, Randstreifen und Einbau.", "Für 100 m² ergibt sich eine Budgetorientierung von ungefähr 2.500 bis 5.000 Euro. Besondere Estrichdicken, Untergrundausgleich oder Zusatzanforderungen können den Preis verändern."],
    table: { headers: ["Estrichfläche", "Budgetorientierung"], rows: [
      { cells: ["50 m²", "1.250-2.500 €"] },
      { cells: ["100 m²", "2.500-5.000 €"] },
      { cells: ["150 m²", "3.750-7.500 €"] },
    ] },
    factors: ["Estrichdicke", "Dämmung und Randstreifen", "Untergrundzustand", "Fußbodenheizung", "Pump- und Förderweg", "Flächengröße"],
    compareHeading: "Zementestrich mit gleichem Aufbau vergleichen",
    compareParagraphs: ["Ein reiner Estrich-Einbau ohne Dämmung ist nicht direkt mit der BauKostenRadar-Komplettposition vergleichbar. Prüfen Sie deshalb alle Schichten des Bodenaufbaus.", "Für Anhydrit-, Trocken- und Gussasphaltestrich gibt es eigene Richtwertseiten."],
    faqs: [
      { question: "Was kostet Zementestrich pro m² 2026?", answer: "BauKostenRadar führt für den kompletten Aufbau etwa 25 bis 50 Euro pro Quadratmeter als Richtwert." },
      { question: "Was kosten 100 m² Zementestrich?", answer: "Mit der Richtwertspanne ergeben sich ungefähr 2.500 bis 5.000 Euro als Budgetorientierung." },
      { question: "Ist Dämmung enthalten?", answer: "Ja, die hinterlegte BauKostenRadar-Preisposition ist als kompletter Aufbau mit Dämmung, Randstreifen und Einbau beschrieben." },
    ],
    serviceSlug: "estrich", itemSlug: "zementestrich-komplett", itemLabel: "Zementestrich komplett", serviceLabel: "Estrich", parentSlug: "estrich-100-qm-kosten", parentLabel: "Estrich 100 m² Kosten",
    relatedExtra: [{ label: "Anhydritestrich Kosten", href: "/ratgeber/anhydritestrich-kosten-pro-qm" }],
  },
  {
    slug: "kalksandstein-mauerwerk-kosten-pro-qm",
    title: "Kalksandstein Mauerwerk Kosten pro m² 2026",
    h1: "Kalksandstein Mauerwerk Kosten 2026: Richtwert pro m²",
    description: "Kalksandstein Mauerwerk Kosten 2026 pro m²: BauKostenRadar-Richtwerte, Wanddicke, Material, Öffnungen, Baustellenlogistik und Angebotsvergleich.",
    eyebrow: "Kalksandstein 2026",
    intro: "Kalksandstein bietet hohe Rohdichte und guten Schallschutz. Bei der Kostenplanung sind Wanddicke, Steinformat und Zahl der Öffnungen wichtiger als ein isolierter Materialpreis.",
    keyFact: "Kalksandstein-Mauerwerk etwa 60-100 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Kalksandstein-Mauerwerk pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Kalksandstein-Mauerwerk etwa 60 bis 100 Euro pro Quadratmeter. Für 50 m² Wandfläche ergibt sich eine Orientierung von ungefähr 3.000 bis 5.000 Euro.", "Putz, Dämmung, Stürze oder besondere statische Anforderungen können je nach Projekt zusätzliche Kostenblöcke sein."],
    table: { headers: ["Wandfläche", "Budgetorientierung"], rows: [
      { cells: ["20 m²", "1.200-2.000 €"] },
      { cells: ["50 m²", "3.000-5.000 €"] },
      { cells: ["100 m²", "6.000-10.000 €"] },
    ] },
    factors: ["Wanddicke und Steinformat", "Tragend oder nichttragend", "Tür- und Fensteröffnungen", "Stürze und Anschlüsse", "Materialtransport", "Putz und Folgearbeiten"],
    compareHeading: "Mauerwerksarten nicht nur über €/m² wählen",
    compareParagraphs: ["Poroton, Porenbeton und Kalksandstein unterscheiden sich technisch. Ein Preisvergleich sollte deshalb Wandaufbau, Schallschutz, Wärmeschutz und Folgearbeiten berücksichtigen.", "Für eine allgemeine fertige Wand führt BauKostenRadar zusätzlich einen breiteren Maurer-Richtwert."],
    faqs: [
      { question: "Was kostet Kalksandstein-Mauerwerk pro m² 2026?", answer: "BauKostenRadar führt etwa 60 bis 100 Euro pro Quadratmeter als Richtwert." },
      { question: "Was kosten 50 m² Kalksandstein-Mauerwerk?", answer: "Mit der Richtwertspanne ergeben sich ungefähr 3.000 bis 5.000 Euro als Budgetorientierung." },
      { question: "Sind Putzarbeiten enthalten?", answer: "Nicht automatisch. Putz und weitere Folgearbeiten sollten im konkreten Angebot separat geprüft werden." },
    ],
    serviceSlug: "maurer", itemSlug: "kalksandstein-mauerwerk", itemLabel: "Kalksandstein-Mauerwerk", serviceLabel: "Maurerarbeiten", parentSlug: "innenwand-mauern-kosten", parentLabel: "Innenwand mauern Kosten",
  },
  {
    slug: "poroton-mauerwerk-kosten-pro-qm",
    title: "Poroton Mauerwerk Kosten pro m² 2026",
    h1: "Poroton Mauerwerk Kosten 2026: Richtwert pro m²",
    description: "Poroton Mauerwerk Kosten 2026 pro m²: BauKostenRadar-Richtwerte, Ziegelart, Wanddicke, Öffnungen, Material und Angebotsvergleich.",
    eyebrow: "Poroton 2026",
    intro: "Poroton-Ziegel werden häufig für Außen- und Innenwände eingesetzt. Der konkrete Wandaufbau hängt von Ziegeltyp, Wanddicke und energetischen Anforderungen ab.",
    keyFact: "Poroton-Mauerwerk etwa 70-120 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Poroton-Mauerwerk pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Poroton-Mauerwerk etwa 70 bis 120 Euro pro Quadratmeter. Für 50 m² Wandfläche entspricht das ungefähr 3.500 bis 6.000 Euro als Budgetorientierung.", "Spezielle Dämmziegel, dickere Außenwände, Stürze und aufwendige Anschlüsse können den konkreten Preis verändern."],
    table: { headers: ["Wandfläche", "Budgetorientierung"], rows: [
      { cells: ["20 m²", "1.400-2.400 €"] },
      { cells: ["50 m²", "3.500-6.000 €"] },
      { cells: ["100 m²", "7.000-12.000 €"] },
    ] },
    factors: ["Ziegeltyp und Rohdichte", "Wanddicke", "Tragende Funktion", "Öffnungen und Stürze", "Mörtel- oder Klebesystem", "Gerüst und Materiallogistik"],
    compareHeading: "Poroton mit vollständigem Wandaufbau vergleichen",
    compareParagraphs: ["Ein einzelner Quadratmeterpreis sagt wenig aus, wenn Wanddicke und Ziegeltyp nicht gleich sind. Fordern Sie deshalb eine genaue Materialbezeichnung und den statischen Aufbau.", "Kalksandstein und Porenbeton haben andere Eigenschaften und eigene BauKostenRadar-Richtwerte."],
    faqs: [
      { question: "Was kostet Poroton-Mauerwerk pro m² 2026?", answer: "BauKostenRadar führt etwa 70 bis 120 Euro pro Quadratmeter als Richtwert." },
      { question: "Was kosten 50 m² Poroton-Mauerwerk?", answer: "Mit der Richtwertspanne ergeben sich ungefähr 3.500 bis 6.000 Euro als Budgetorientierung." },
      { question: "Ist jede Poroton-Wand gleich teuer?", answer: "Nein. Ziegeltyp, Wanddicke, Statik und Öffnungen beeinflussen den konkreten Preis." },
    ],
    serviceSlug: "maurer", itemSlug: "poroton-mauerwerk", itemLabel: "Poroton-Mauerwerk", serviceLabel: "Maurerarbeiten", parentSlug: "innenwand-mauern-kosten", parentLabel: "Innenwand mauern Kosten",
  },
  {
    slug: "porenbeton-mauerwerk-kosten-pro-qm",
    title: "Porenbeton Mauerwerk Kosten pro m² 2026",
    h1: "Porenbeton Mauerwerk Kosten 2026: Richtwert pro m²",
    description: "Porenbeton Mauerwerk Kosten 2026 pro m²: BauKostenRadar-Richtwerte, Wanddicke, Steine, Öffnungen, Anschlüsse und Angebotsvergleich.",
    eyebrow: "Porenbeton 2026",
    intro: "Porenbeton ist leicht zu bearbeiten und wird für unterschiedliche Wandaufbauten eingesetzt. Wanddicke, Statik und die Zahl der Zuschnitte bestimmen den Arbeits- und Materialaufwand.",
    keyFact: "Porenbeton-Mauerwerk etwa 55-90 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Porenbeton-Mauerwerk pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Porenbeton-Mauerwerk etwa 55 bis 90 Euro pro Quadratmeter. Für 50 m² Wandfläche ergibt sich daraus eine Orientierung von ungefähr 2.750 bis 4.500 Euro.", "Putz, Bewehrungen, Stürze oder besondere Anschlüsse können abhängig vom Projekt zusätzlich kalkuliert werden."],
    table: { headers: ["Wandfläche", "Budgetorientierung"], rows: [
      { cells: ["20 m²", "1.100-1.800 €"] },
      { cells: ["50 m²", "2.750-4.500 €"] },
      { cells: ["100 m²", "5.500-9.000 €"] },
    ] },
    factors: ["Wanddicke", "Steinformat", "Tragende Funktion", "Zuschnitte und Öffnungen", "Stürze und Anschlüsse", "Putz und Folgearbeiten"],
    compareHeading: "Porenbeton im System statt isoliert vergleichen",
    compareParagraphs: ["Bei verschiedenen Mauerwerksarten sollten Wärmeschutz, Schallschutz und Wanddicke gemeinsam mit dem Preis betrachtet werden.", "Angebote sind nur vergleichbar, wenn Material und enthaltene Nebenarbeiten ähnlich beschrieben sind."],
    faqs: [
      { question: "Was kostet Porenbeton-Mauerwerk pro m² 2026?", answer: "BauKostenRadar führt etwa 55 bis 90 Euro pro Quadratmeter als Richtwert." },
      { question: "Was kosten 50 m² Porenbeton-Mauerwerk?", answer: "Mit der Richtwertspanne ergeben sich ungefähr 2.750 bis 4.500 Euro als Budgetorientierung." },
      { question: "Ist Putz im Richtwert enthalten?", answer: "Nicht automatisch. Folgearbeiten wie Putz sollten im konkreten Angebot separat geprüft werden." },
    ],
    serviceSlug: "maurer", itemSlug: "porenbeton-mauerwerk", itemLabel: "Porenbeton-Mauerwerk", serviceLabel: "Maurerarbeiten", parentSlug: "innenwand-mauern-kosten", parentLabel: "Innenwand mauern Kosten",
  },
  {
    slug: "treppenrenovierung-holzstufen-system-kosten",
    title: "Treppenrenovierung Holzstufen-System Kosten 2026",
    h1: "Treppenrenovierung mit Holzstufen-System Kosten 2026",
    description: "Treppenrenovierung Holzstufen-System Kosten 2026: BauKostenRadar-Richtwert pro Treppe, Stufen, Setzstufen, Untergrund und Angebotsvergleich.",
    eyebrow: "Treppenrenovierung 2026",
    intro: "Ein Holzstufen-System überarbeitet die sichtbaren Stufen einer bestehenden Treppe, ohne den tragenden Treppenkörper vollständig zu ersetzen. Materialklasse und Treppengeometrie prägen den Projektpreis.",
    keyFact: "Treppenrenovierung Holzstufen-System etwa 3.000-8.000 € pro Treppe in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet eine Treppenrenovierung mit Holzstufen-System?",
    priceParagraphs: ["BauKostenRadar führt für Treppenrenovierung mit Holzstufen-System etwa 3.000 bis 8.000 Euro pro Treppe als Richtwert. Die Anzahl der Stufen und das gewählte System bestimmen, wo das Projekt innerhalb der Spanne liegt.", "Geländer, Podeste, Setzstufen und Reparaturen am Untergrund müssen im konkreten Angebot als enthalten oder zusätzlich erkennbar sein."],
    factors: ["Anzahl der Stufen", "Gerade oder gewendelte Treppe", "Holzart und Oberflächenqualität", "Setzstufen und Wangen", "Podeste", "Geländer und Handlauf"],
    compareHeading: "Stufen-System, Schleifen und Überbau unterscheiden",
    compareParagraphs: ["Eine bestehende Massivholztreppe kann möglicherweise geschliffen werden. Andere Treppen eignen sich besser für einen Stufenüberbau. Diese Methoden haben unterschiedliche Leistungsumfänge.", "Vergleichen Sie Angebote deshalb nach System, Material und enthaltenen Treppenteilen, nicht nur nach dem Projektpreis."],
    faqs: [
      { question: "Was kostet Treppenrenovierung mit Holzstufen-System 2026?", answer: "BauKostenRadar führt etwa 3.000 bis 8.000 Euro pro Treppe als Richtwert." },
      { question: "Ist ein neues Geländer enthalten?", answer: "Nicht automatisch. Geländer und Handlauf sollten im konkreten Angebot ausdrücklich genannt werden." },
      { question: "Ist Schleifen günstiger?", answer: "Bei einer geeigneten Massivholztreppe kann Schleifen einen kleineren Leistungsumfang darstellen. Zustand und gewünschtes Ergebnis entscheiden." },
    ],
    serviceSlug: "treppen", itemSlug: "treppenrenovierung-holzstufen-system", itemLabel: "Treppenrenovierung Holzstufen-System", serviceLabel: "Treppen", parentSlug: "14-treppenstufen-renovieren-kosten", parentLabel: "Treppen renovieren Kosten",
    relatedExtra: [{ label: "Holztreppe schleifen Kosten", href: "/ratgeber/holztreppe-schleifen-kosten" }],
  },
  {
    slug: "treppen-stufenueberbau-gelaender-kosten",
    title: "Treppen Stufenüberbau + Geländer Kosten 2026",
    h1: "Holztreppe mit Stufenüberbau und Geländer Kosten 2026",
    description: "Holztreppe Stufenüberbau und Geländer Kosten 2026: BauKostenRadar-Richtwert pro Treppe, Stufen, Geländer, Material und Angebotsvergleich.",
    eyebrow: "Stufenüberbau 2026",
    intro: "Ein Stufenüberbau verändert die sichtbare Oberfläche der bestehenden Treppe und kann zusammen mit einem neuen oder überarbeiteten Geländer ein umfassendes Renovierungspaket bilden.",
    keyFact: "Holztreppe Stufenüberbau + Geländer etwa 2.650-7.300 € pro Treppe in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Stufenüberbau inklusive Geländer?",
    priceParagraphs: ["BauKostenRadar führt für Holztreppe Stufenüberbau plus Geländer etwa 2.650 bis 7.300 Euro pro Treppe als Richtwert. Treppengröße, Material und Geländerlösung bestimmen den konkreten Projektpreis.", "Podeste, komplizierte Wendelungen und Reparaturen an der Unterkonstruktion können zusätzliche Arbeiten verursachen."],
    factors: ["Anzahl und Form der Stufen", "Material des Überbaus", "Geländerart", "Podeste und Wangen", "Bestehender Untergrund", "Anschlussdetails"],
    compareHeading: "Geländer im Leistungsumfang genau prüfen",
    compareParagraphs: ["Ein Angebot mit neuem Geländer ist nicht mit einem reinen Stufenüberbau vergleichbar. Material und Umfang des Geländers sollten deshalb separat beschrieben sein.", "Bei intakten Holzstufen kann als Alternative eine Aufarbeitung durch Schleifen und Versiegeln geprüft werden."],
    faqs: [
      { question: "Was kostet Stufenüberbau mit Geländer 2026?", answer: "BauKostenRadar führt etwa 2.650 bis 7.300 Euro pro Treppe als Richtwert." },
      { question: "Ist das Geländer im Richtwert enthalten?", answer: "Die hinterlegte Preisposition ist ausdrücklich als Stufenüberbau plus Geländer beschrieben." },
      { question: "Kann die alte Treppe bestehen bleiben?", answer: "Beim Überbau bleibt der bestehende Treppenkörper grundsätzlich Grundlage der Renovierung. Sein Zustand muss vorab geprüft werden." },
    ],
    serviceSlug: "treppen", itemSlug: "holztreppe-stufenueberbau-gelaender", itemLabel: "Holztreppe Stufenüberbau + Geländer", serviceLabel: "Treppen", parentSlug: "14-treppenstufen-renovieren-kosten", parentLabel: "Treppen renovieren Kosten",
    relatedExtra: [{ label: "Holztreppe schleifen Kosten", href: "/ratgeber/holztreppe-schleifen-kosten" }],
  },
  {
    slug: "natursteintreppe-schleifen-kosten",
    title: "Natursteintreppe schleifen Kosten 2026",
    h1: "Natursteintreppe schleifen und polieren Kosten 2026",
    description: "Natursteintreppe schleifen Kosten 2026: BauKostenRadar-Richtwert pro Treppe für Schleifen und Polieren, Steinart, Schäden und Angebotsvergleich.",
    eyebrow: "Natursteintreppe 2026",
    intro: "Naturstein lässt sich bei geeigneter Substanz durch Schleifen und Polieren wieder aufwerten. Steinart, Kratzer, Kanten und vorhandene Beschichtungen beeinflussen die Zahl der Arbeitsgänge.",
    keyFact: "Natursteintreppe schleifen und polieren etwa 1.000-3.000 € pro Treppe in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Natursteintreppe schleifen und polieren?",
    priceParagraphs: ["BauKostenRadar führt für Natursteintreppe schleifen und polieren etwa 1.000 bis 3.000 Euro pro Treppe als Richtwert. Die Spanne bezieht sich auf das Aufarbeiten einer vorhandenen Natursteinoberfläche.", "Tiefe Ausbrüche, lose Platten, Neuverfugung oder der Austausch einzelner Stufen können den Leistungsumfang erweitern."],
    factors: ["Steinart", "Stufenanzahl", "Kratzer und Flecken", "Kanten und Podeste", "Reparaturen und Fugen", "Gewünschter Poliergrad"],
    compareHeading: "Aufarbeitung und neuer Belag sind verschiedene Projekte",
    compareParagraphs: ["Schleifen erhält vorhandenen Naturstein. Ein kompletter neuer Treppenbelag umfasst Material, Zuschnitt und Montage und ist daher nicht direkt vergleichbar.", "Lassen Sie im Angebot klar ausweisen, ob Reparaturen, Versiegelung oder Imprägnierung enthalten sind."],
    faqs: [
      { question: "Was kostet Natursteintreppe schleifen 2026?", answer: "BauKostenRadar führt für Schleifen und Polieren etwa 1.000 bis 3.000 Euro pro Treppe als Richtwert." },
      { question: "Sind Reparaturen enthalten?", answer: "Nicht automatisch. Ausbrüche, lose Platten oder Neuverfugung sollten im Angebot separat beschrieben werden." },
      { question: "Ist Polieren enthalten?", answer: "Ja, die hinterlegte BauKostenRadar-Preisposition ist als Schleifen und Polieren formuliert." },
    ],
    serviceSlug: "treppen", itemSlug: "natursteintreppe-schleifen-und-polieren", itemLabel: "Natursteintreppe schleifen und polieren", serviceLabel: "Treppen", parentSlug: "14-treppenstufen-renovieren-kosten", parentLabel: "Treppen renovieren Kosten",
  },
  {
    slug: "sanitaerobjekte-bad-kosten",
    title: "Sanitärobjekte und Armaturen Kosten 2026",
    h1: "Sanitärobjekte und Armaturen für ein 8-m²-Bad Kosten 2026",
    description: "Sanitärobjekte und Armaturen Kosten 2026: BauKostenRadar-Richtwert für ein 8-m²-Bad, Ausstattung, Qualitätsklasse und Angebotsvergleich.",
    eyebrow: "Badausstattung 2026",
    intro: "WC, Waschtisch, Dusche oder Wanne und Armaturen bilden einen eigenen Material- und Ausstattungsblock der Badsanierung. Marken, Design und Sonderfunktionen können die Spanne stark beeinflussen.",
    keyFact: "Sanitärobjekte und Armaturen für ein 8-m²-Bad etwa 3.500-5.500 € in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kosten Sanitärobjekte für ein 8-m²-Bad?",
    priceParagraphs: ["BauKostenRadar führt für Sanitärobjekte und Armaturen eines etwa 8 m² großen Bads rund 3.500 bis 5.500 Euro als Richtwert. Dieser Kostenblock ist nicht mit der Arbeitszeit des Sanitärinstallateurs gleichzusetzen.", "Eine bodengleiche Dusche, hochwertige Armaturen, spezielle Möbel oder Premium-Keramik können das konkrete Ausstattungsbudget erhöhen."],
    factors: ["WC und Waschtisch", "Dusche oder Badewanne", "Armaturenqualität", "Duschsystem und Unterputztechnik", "Badmöbel", "Marken- und Designauswahl"],
    compareHeading: "Ausstattung und Sanitärarbeit getrennt bewerten",
    compareParagraphs: ["Ein Komplettangebot sollte sichtbar machen, welcher Betrag auf Objekte und Armaturen und welcher auf Montage und Rohrarbeiten entfällt.", "So lässt sich erkennen, ob Preisunterschiede aus besserer Ausstattung oder höherem Arbeitsaufwand entstehen."],
    faqs: [
      { question: "Was kosten Sanitärobjekte und Armaturen 2026?", answer: "BauKostenRadar führt für ein etwa 8 m² großes Bad rund 3.500 bis 5.500 Euro als Richtwert." },
      { question: "Ist die Montage enthalten?", answer: "Die Datenbasis führt Arbeitszeit Sanitär als separate Preisposition. Der konkrete Angebotsumfang sollte daher getrennt geprüft werden." },
      { question: "Gilt der Wert für jedes Bad?", answer: "Nein. Er ist eine Budgetorientierung für ein Beispielbad mit etwa 8 m² und hängt stark von der Ausstattungsklasse ab." },
    ],
    serviceSlug: "sanitaer", itemSlug: "sanitaerobjekte-armaturen-fuer-8-m2-bad", itemLabel: "Sanitärobjekte & Armaturen für 8-m²-Bad", serviceLabel: "Sanitär", parentSlug: "sanitaer-kosten", parentLabel: "Sanitär Kosten",
    relatedExtra: [{ label: "Bad komplett sanieren Kosten", href: "/ratgeber/bad-komplett-sanieren-kosten" }],
  },
  {
    slug: "kueche-elektrogeraete-kosten",
    title: "Küchen Elektrogeräte Kosten 2026",
    h1: "Neue Elektrogeräte für die Küche Kosten 2026",
    description: "Küchen Elektrogeräte Kosten 2026: BauKostenRadar-Richtwert pro Küche, Gerätepakte, Einbaugeräte, Qualitätsklasse und Renovierungsbudget.",
    eyebrow: "Küchengeräte 2026",
    intro: "Bei einer Küchenrenovierung können neue Geräte einen eigenen vierstelligen Kostenblock bilden. Anzahl, Energieeffizienz und Geräteklasse beeinflussen das Budget stärker als die reine Küchenfläche.",
    keyFact: "Neue Elektrogeräte etwa 2.000-6.000 € pro Küche in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kosten neue Elektrogeräte für eine Küche?",
    priceParagraphs: ["BauKostenRadar führt für neue Elektrogeräte etwa 2.000 bis 6.000 Euro pro Küche als Richtwert. Die Position ist als Paket-Budget zu verstehen und nicht als Preis eines einzelnen Geräts.", "Backofen, Kochfeld, Kühlschrank, Geschirrspüler und Dunstabzug können je nach Ausstattung unterschiedlich kombiniert werden."],
    factors: ["Anzahl der Geräte", "Einbau- oder Standgeräte", "Marke und Produktklasse", "Induktion und Spezialfunktionen", "Kühlgerätgröße", "Montage und elektrische Anschlüsse"],
    compareHeading: "Gerätepaket vom Möbelpreis trennen",
    compareParagraphs: ["Bei Küchenangeboten sollten Möbel, Arbeitsplatte, Geräte und Montage nachvollziehbar getrennt sein. Dadurch lässt sich ein scheinbar günstiger Küchenpreis besser einordnen.", "Für eine komplett neue Einbauküche führt BauKostenRadar zusätzlich einen eigenen Projekt-Richtwert."],
    faqs: [
      { question: "Was kosten neue Küchengeräte 2026?", answer: "BauKostenRadar führt etwa 2.000 bis 6.000 Euro pro Küche als Richtwert für ein Gerätepaket." },
      { question: "Welche Geräte sind enthalten?", answer: "Die Preisposition ist ein allgemeiner Küchenblock. Das konkrete Angebot muss Anzahl und Typ der Geräte benennen." },
      { question: "Ist die Küchenmontage enthalten?", answer: "Nicht automatisch. Geräte, Möbelmontage und Elektroanschlüsse sollten als eigene Leistungsbestandteile geprüft werden." },
    ],
    serviceSlug: "kueche", itemSlug: "neue-elektrogeraete", itemLabel: "Neue Elektrogeräte", serviceLabel: "Küchenrenovierung", parentSlug: "kueche-10-qm-renovieren-kosten", parentLabel: "Küche renovieren Kosten",
  },
  {
    slug: "einbaukueche-kosten",
    title: "Einbauküche Kosten 2026",
    h1: "Komplett neue Einbauküche Kosten 2026",
    description: "Einbauküche Kosten 2026: BauKostenRadar-Richtwert pro Küche, Möbel, Arbeitsplatte, Geräte, Montage und Angebotsvergleich.",
    eyebrow: "Einbauküche 2026",
    intro: "Eine neue Einbauküche bündelt Möbel, Arbeitsplatte, Stauraum und je nach Angebot Geräte und Montage. Die große Preisspanne entsteht vor allem durch Material, Planung und Ausstattung.",
    keyFact: "Komplett neue Einbauküche etwa 5.000-25.000 € pro Küche in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet eine komplett neue Einbauküche?",
    priceParagraphs: ["BauKostenRadar führt für eine komplett neue Einbauküche etwa 5.000 bis 25.000 Euro pro Küche als Richtwert. Der konkrete Leistungsumfang muss im Angebot geprüft werden, weil Geräte und Montage unterschiedlich gebündelt sein können.", "Sondermaße, hochwertige Fronten, Stein- oder Keramikarbeitsplatten und komplexe Planung können den Preis stark verändern."],
    factors: ["Küchengröße und Schrankanzahl", "Fronten und Korpusqualität", "Arbeitsplattenmaterial", "Elektrogeräte", "Innenausstattung und Beschläge", "Lieferung, Montage und Anschlüsse"],
    compareHeading: "Küchenangebote nach Bestandteilen vergleichen",
    compareParagraphs: ["Ein Gesamtpreis ist nur aussagekräftig, wenn Möbel, Arbeitsplatte, Geräte und Montage ähnlich enthalten sind. Sonst entstehen große Scheindifferenzen.", "Bei einer Renovierung ohne komplett neue Möbel können Frontentausch oder neue Arbeitsplatte wirtschaftlich deutlich anders ausfallen."],
    faqs: [
      { question: "Was kostet eine Einbauküche 2026?", answer: "BauKostenRadar führt für eine komplett neue Einbauküche etwa 5.000 bis 25.000 Euro pro Küche als Richtwert." },
      { question: "Sind Elektrogeräte enthalten?", answer: "Der konkrete Paketumfang kann unterschiedlich sein. Geräte sollten im Angebot ausdrücklich benannt und bewertet werden." },
      { question: "Ist die Montage enthalten?", answer: "Das muss im konkreten Angebot geprüft werden. Lieferung, Montage und Anschlüsse sollten separat oder eindeutig im Gesamtpaket ausgewiesen sein." },
    ],
    serviceSlug: "kueche", itemSlug: "komplett-neue-einbaukueche", itemLabel: "Komplett neue Einbauküche", serviceLabel: "Küchenrenovierung", parentSlug: "kueche-10-qm-renovieren-kosten", parentLabel: "Küche renovieren Kosten",
    relatedExtra: [{ label: "Küchenfronten erneuern Kosten", href: "/ratgeber/kuechenfronten-erneuern-kosten" }, { label: "Küchengeräte Kosten", href: "/ratgeber/kueche-elektrogeraete-kosten" }],
  },
  {
    slug: "premium-kueche-umbau-kosten",
    title: "Premium-Küche mit Umbau Kosten 2026",
    h1: "Premium-Küche mit Umbau Kosten 2026",
    description: "Premium-Küche mit Umbau Kosten 2026: BauKostenRadar-Richtwert pro Küche, hochwertige Möbel, Geräte, Grundrissänderungen, Anschlüsse und Reserve.",
    eyebrow: "Premium-Küche 2026",
    intro: "Bei einer Premium-Küche mit Umbau geht es nicht nur um teurere Fronten. Geänderte Anschlüsse, neue Oberflächen, hochwertige Geräte und individuelle Planung können aus dem Küchenprojekt eine umfassende Renovierung machen.",
    keyFact: "Premium-Küche mit Umbau etwa 15.000-40.000 € pro Küche in der BauKostenRadar-Datenbasis; die Quelle nennt auch höhere Projekte als möglich",
    priceHeading: "Was kostet eine Premium-Küche mit Umbau?",
    priceParagraphs: ["BauKostenRadar führt für Premium-Küche mit Umbau etwa 15.000 bis 40.000 Euro pro Küche als Richtwert. Die hinterlegte Quelle nennt 40.000 Euro und mehr als mögliche Obergrenze, deshalb ist der obere Wert keine absolute Preisgrenze.", "Planungsänderungen, Elektro- und Sanitäranschlüsse, Boden, Wand und hochwertige Geräte können den Projektumfang zusätzlich prägen."],
    factors: ["Individuelle Küchenplanung", "Premium-Fronten und Beschläge", "Naturstein- oder Keramikarbeitsplatte", "Hochwertige Elektrogeräte", "Versetzen von Wasser und Elektrik", "Boden-, Wand- und Beleuchtungsarbeiten"],
    compareHeading: "Premium-Projekt nicht mit Standard-Einbauküche gleichsetzen",
    compareParagraphs: ["Eine Standard-Einbauküche ohne größere Umbauten hat einen anderen Leistungsumfang. Bei Premium-Projekten sollte der Bauanteil getrennt von Möbeln und Geräten erkennbar bleiben.", "Eine Reserve ist sinnvoll, wenn Anschlüsse, Böden oder Wände erst nach Demontage vollständig beurteilt werden können."],
    faqs: [
      { question: "Was kostet eine Premium-Küche mit Umbau 2026?", answer: "BauKostenRadar führt etwa 15.000 bis 40.000 Euro pro Küche als Richtwert. Die hinterlegte Quelle nennt auch Projekte oberhalb von 40.000 Euro als möglich." },
      { question: "Ist 40.000 Euro eine feste Obergrenze?", answer: "Nein. BauKostenRadar weist ausdrücklich darauf hin, dass die Quelle auch höhere Premium-Projekte nennt." },
      { question: "Was gehört zum Umbau?", answer: "Das kann Elektro-, Sanitär-, Boden-, Wand- und Beleuchtungsarbeiten umfassen. Der konkrete Umfang muss im Angebot definiert werden." },
    ],
    serviceSlug: "kueche", itemSlug: "premium-kueche-mit-umbau", itemLabel: "Premium-Küche mit Umbau", serviceLabel: "Küchenrenovierung", parentSlug: "kueche-10-qm-renovieren-kosten", parentLabel: "Küche renovieren Kosten",
    relatedExtra: [{ label: "Einbauküche Kosten", href: "/ratgeber/einbaukueche-kosten" }],
  },
];

export const quinaryOpportunityGuides: Guide[] = configs.map(createGuide);
