import type { Guide } from "@/lib/guides";

export const fliesenExpansionGuides: Guide[] = [
  {
    slug: "fliese-auf-fliese-kosten-pro-qm",
    title: "Fliese auf Fliese Kosten pro m² 2026",
    h1: "Fliese auf Fliese verlegen: Kosten 2026 pro m²",
    description: "Fliese auf Fliese Kosten 2026 pro m²: aktueller Richtwert für das Überfliesen eines tragfähigen Altbelags und wichtige Zusatzarbeiten.",
    eyebrow: "Fliese auf Fliese 2026",
    intro: "Ist der vorhandene Fliesenbelag fest, eben und tragfähig, kann ein neuer Belag unter bestimmten Voraussetzungen direkt darauf verlegt werden. Das spart Rückbau, erhöht aber den Boden- oder Wandaufbau und verlangt eine sorgfältige Prüfung des Bestands.",
    keyFact: "Fliese auf Fliese verlegen etwa 50-80 €/m²",
    sections: [
      { heading: "Was kostet Fliese auf Fliese 2026?", paragraphs: ["Für das Überfliesen eines tragfähigen Altbelags führt BauKostenRadar aktuell etwa 50 bis 80 Euro pro Quadratmeter.", "Aufbauhöhe, Zustand des Altbelags, Haftgrund und notwendige Ausgleichsarbeiten können den tatsächlichen Preis verändern."], table: { headers: ["Fliesenarbeit", "Richtwert 2026"], rows: [{ cells: ["Fliese auf Fliese verlegen", "50-80 €/m²"], href: "/kosten/fliesenleger/leistung/fliese-auf-fliese-verlegen" }] } },
      { heading: "Wann ist Überfliesen möglich?", paragraphs: ["Der vorhandene Belag muss als Untergrund geeignet sein."], bullets: ["Altfliesen fest und tragfähig", "keine losen oder hohl klingenden Bereiche", "ausreichend ebener Untergrund", "Aufbauhöhe an Türen und Anschlüssen beachten", "passende Grundierung und Kleber verwenden"] },
      { heading: "Rückbau und Überfliesen vergleichen", paragraphs: ["Überfliesen kann Rückbau- und Entsorgungskosten sparen. Bei schadhaften Altbelägen ist Entfernen jedoch oft die technisch sauberere Lösung.", "Im Angebot sollte klar stehen, ob Reinigung, Grundierung und kleinere Ausgleichsarbeiten enthalten sind."] },
    ],
    faqs: [
      { question: "Was kostet Fliese auf Fliese pro m²?", answer: "Der aktuelle BauKostenRadar-Richtwert liegt bei etwa 50 bis 80 Euro pro Quadratmeter." },
      { question: "Müssen alte Fliesen immer entfernt werden?", answer: "Nein. Ein tragfähiger und geeigneter Altbelag kann unter bestimmten Voraussetzungen überfliest werden." },
      { question: "Ist Untergrundausgleich enthalten?", answer: "Nicht automatisch. Größere Unebenheiten werden als eigener Kostenblock kalkuliert." },
    ],
    related: [
      { label: "Fliese auf Fliese Preisdetail", href: "/kosten/fliesenleger/leistung/fliese-auf-fliese-verlegen" },
      { label: "Fliesen verlegen Kosten", href: "/ratgeber/fliesen-verlegen-kosten-pro-qm" },
      { label: "Untergrund ausgleichen Kosten", href: "/ratgeber/fliesen-untergrund-ausgleichen-kosten" },
      { label: "Überfliesen berechnen", href: "/rechner/handwerkerkosten?gewerk=fliesenleger&leistung=fliese-auf-fliese-verlegen" },
    ],
  },
  {
    slug: "fliesen-untergrund-ausgleichen-kosten",
    title: "Fliesen Untergrund ausgleichen Kosten 2026",
    h1: "Untergrund vor Fliesen ausgleichen: Kosten 2026 pro m²",
    description: "Untergrund ausgleichen vor Fliesen Kosten 2026: aktueller Richtwert pro m², Unebenheiten, Spachtelmasse und Abgrenzung zur eigentlichen Verlegung.",
    eyebrow: "Fliesen-Untergrund 2026",
    intro: "Ein ebener Untergrund ist Voraussetzung für ein sauberes Fliesenbild. Besonders bei Großformaten können Unebenheiten zu Problemen führen. Ausgleichen und Verlegen sind deshalb zwei getrennte Kostenblöcke.",
    keyFact: "Untergrund ausgleichen etwa 10-30 €/m² zusätzlich zur Verlegung",
    sections: [
      { heading: "Was kostet Untergrund ausgleichen vor Fliesen?", paragraphs: ["Für das Ausgleichen unebener Böden oder Wände führt BauKostenRadar aktuell etwa 10 bis 30 Euro pro Quadratmeter.", "Die Position ist als zusätzliche Vorarbeit vor der eigentlichen Fliesenverlegung zu verstehen."], table: { headers: ["Vorarbeit", "Richtwert 2026"], rows: [{ cells: ["Untergrund ausgleichen", "10-30 €/m²"], href: "/kosten/fliesenleger/leistung/untergrund-ausgleichen" }] } },
      { heading: "Was beeinflusst den Aufwand?", paragraphs: ["Tiefe und Art der Unebenheiten bestimmen Material- und Arbeitsbedarf."], bullets: ["Untergrundzustand", "Höhenunterschiede", "Risse und Schäden", "notwendige Grundierung", "Schichtdicke der Ausgleichsmasse", "Boden- oder Wandfläche"] },
      { heading: "Bei Großformaten besonders wichtig", paragraphs: ["Großformatige Fliesen reagieren empfindlicher auf Unebenheiten. Eine gute Untergrundvorbereitung kann deshalb wichtiger werden als bei kleinen Formaten.", "Vor Auftrag sollte festgelegt werden, welche Ebenheit der Fachbetrieb herstellt und ob sie bereits im Verlegepreis enthalten ist."] },
    ],
    faqs: [
      { question: "Was kostet Untergrund ausgleichen pro m²?", answer: "BauKostenRadar führt aktuell etwa 10 bis 30 Euro pro Quadratmeter." },
      { question: "Ist das im Fliesenpreis enthalten?", answer: "Nicht automatisch. Größere Ausgleichsarbeiten werden häufig separat berechnet." },
      { question: "Warum ist das bei Großformat wichtig?", answer: "Große Formate benötigen einen besonders ebenen Untergrund, damit Höhenversätze und Hohlstellen vermieden werden." },
    ],
    related: [
      { label: "Untergrund ausgleichen Preisdetail", href: "/kosten/fliesenleger/leistung/untergrund-ausgleichen" },
      { label: "Großformat-Fliesen Kosten", href: "/ratgeber/grossformat-fliesen-verlegen-kosten" },
      { label: "Fliesen verlegen Kosten", href: "/ratgeber/fliesen-verlegen-kosten-pro-qm" },
      { label: "Untergrund berechnen", href: "/rechner/handwerkerkosten?gewerk=fliesenleger&leistung=untergrund-ausgleichen" },
    ],
  },
  {
    slug: "silikonfugen-kosten-pro-meter",
    title: "Silikonfugen Kosten pro Meter 2026",
    h1: "Silikonfugen ziehen: Kosten 2026 pro laufendem Meter",
    description: "Silikonfugen Kosten 2026 pro laufendem Meter: aktueller Richtwert für Anschluss- und Dehnungsfugen sowie typische Preisfaktoren.",
    eyebrow: "Silikonfugen 2026",
    intro: "Silikonfugen übernehmen Bewegungen an Anschlüssen und Ecken. Sie sind keine normalen Zementfugen und werden bei Fliesenarbeiten häufig als eigene laufende-Meter-Position kalkuliert.",
    keyFact: "Silikonfugen ziehen etwa 3-8 € pro laufendem Meter",
    sections: [
      { heading: "Was kosten Silikonfugen 2026?", paragraphs: ["Für das Ziehen von Silikonfugen führt BauKostenRadar aktuell etwa 3 bis 8 Euro pro laufendem Meter.", "Entfernung alter Fugen, Reinigung oder besondere Fugenbreiten können zusätzliche Arbeit verursachen."], table: { headers: ["Fugenarbeit", "Richtwert 2026"], rows: [{ cells: ["Silikonfugen ziehen", "3-8 €/lfd. m"], href: "/kosten/fliesenleger/leistung/silikonfugen-ziehen" }] } },
      { heading: "Wo werden Silikonfugen eingesetzt?", paragraphs: ["Typische Einsatzbereiche sind bewegungsbeanspruchte Anschlüsse."], bullets: ["Wand-Boden-Anschlüsse", "Innenecken", "Sanitärobjekte", "Badewannen und Duschen", "Übergänge verschiedener Bauteile"] },
      { heading: "Alte Fugen separat prüfen", paragraphs: ["Bei einer Sanierung muss altes Silikon häufig vollständig entfernt und der Untergrund gereinigt werden. Dieser Aufwand ist nicht automatisch im Preis für eine neue Fuge enthalten.", "Für Angebotsvergleiche sollte deshalb zwischen Erneuern und erstmaligem Herstellen unterschieden werden."] },
    ],
    faqs: [
      { question: "Was kosten Silikonfugen pro Meter?", answer: "Der aktuelle BauKostenRadar-Richtwert liegt bei etwa 3 bis 8 Euro pro laufendem Meter." },
      { question: "Ist altes Silikon entfernen enthalten?", answer: "Nicht automatisch. Rückbau und Reinigung sollten im Leistungsumfang geprüft werden." },
      { question: "Sind Silikonfugen normale Fliesenfugen?", answer: "Nein. Silikon wird typischerweise für elastische Anschluss- und Bewegungsfugen eingesetzt." },
    ],
    related: [
      { label: "Silikonfugen Preisdetail", href: "/kosten/fliesenleger/leistung/silikonfugen-ziehen" },
      { label: "Fliesenleger Kosten", href: "/ratgeber/fliesenleger-kosten-pro-qm" },
      { label: "Fliesen verlegen Kosten", href: "/ratgeber/fliesen-verlegen-kosten-pro-qm" },
      { label: "Silikonfugen berechnen", href: "/rechner/handwerkerkosten?gewerk=fliesenleger&leistung=silikonfugen-ziehen" },
    ],
  },
  {
    slug: "fliesen-sockelleisten-kosten-pro-meter",
    title: "Fliesen Sockelleisten Kosten pro Meter 2026",
    h1: "Fliesen-Sockelleisten anbringen: Kosten 2026 pro Meter",
    description: "Fliesen-Sockelleisten Kosten 2026 pro laufendem Meter: aktueller Arbeitsrichtwert, Zuschnitt, Material und Raumgeometrie als Preisfaktoren.",
    eyebrow: "Fliesen-Sockelleisten 2026",
    intro: "Sockelleisten aus Fliesen bilden den Abschluss zwischen Boden und Wand. Zuschnitt, Ecken und Materialformat bestimmen den Arbeitsaufwand und werden häufig separat zur Bodenfläche kalkuliert.",
    keyFact: "Fliesen-Sockelleisten anbringen etwa 5-10 € pro laufendem Meter Arbeit",
    sections: [
      { heading: "Was kosten Fliesen-Sockelleisten pro Meter?", paragraphs: ["Für das Anbringen von Fliesen-Sockelleisten führt BauKostenRadar aktuell etwa 5 bis 10 Euro pro laufendem Meter als Arbeitsrichtwert.", "Material, Zuschnitt und besondere Raumgeometrien können den Gesamtpreis erhöhen."], table: { headers: ["Fliesenarbeit", "Richtwert 2026"], rows: [{ cells: ["Fliesen-Sockelleisten anbringen", "5-10 €/lfd. m Arbeit"], href: "/kosten/fliesenleger/leistung/fliesen-sockelleisten-anbringen" }] } },
      { heading: "Was beeinflusst den Preis?", paragraphs: ["Viele Ecken und Zuschnitte erhöhen die Arbeitszeit pro Meter."], bullets: ["Sockelformat", "Materialhärte", "Innen- und Außenecken", "Zuschnitt aus Bodenfliesen", "Untergrund", "Anzahl kurzer Teilstücke"] },
      { heading: "Sockelleisten separat zur Fläche kalkulieren", paragraphs: ["Der Quadratmeterpreis für Bodenfliesen enthält Sockelleisten nicht automatisch. Sie sollten als eigene Meterposition im Angebot auftauchen.", "So lassen sich Fliesenfläche und Randabschluss sauber vergleichen."] },
    ],
    faqs: [
      { question: "Was kosten Fliesen-Sockelleisten pro Meter?", answer: "BauKostenRadar führt aktuell etwa 5 bis 10 Euro pro laufendem Meter als Arbeitsrichtwert." },
      { question: "Ist Material enthalten?", answer: "Die aktuelle Position beschreibt vor allem die Arbeitsleistung; Material sollte im Angebot separat geprüft werden." },
      { question: "Sind Sockelleisten im Fliesenpreis pro m² enthalten?", answer: "Nicht automatisch. Sie werden häufig separat pro laufendem Meter abgerechnet." },
    ],
    related: [
      { label: "Sockelleisten Preisdetail", href: "/kosten/fliesenleger/leistung/fliesen-sockelleisten-anbringen" },
      { label: "Fliesen verlegen Kosten", href: "/ratgeber/fliesen-verlegen-kosten-pro-qm" },
      { label: "Fliesenleger Kosten", href: "/ratgeber/fliesenleger-kosten-pro-qm" },
      { label: "Sockelleisten berechnen", href: "/rechner/handwerkerkosten?gewerk=fliesenleger&leistung=fliesen-sockelleisten-anbringen" },
    ],
  },
  {
    slug: "fliesenleger-stundensatz",
    title: "Fliesenleger Stundensatz 2026",
    h1: "Fliesenleger Stundensatz 2026: Kosten pro Stunde",
    description: "Fliesenleger Stundensatz 2026: aktueller Richtwert pro Stunde und Vergleich mit Quadratmeterpreisen für typische Fliesenarbeiten.",
    eyebrow: "Fliesenleger Stundensatz 2026",
    intro: "Viele Fliesenarbeiten werden nach Quadratmetern kalkuliert. Für kleine Reparaturen, Detailarbeiten und Zusatzleistungen kann dagegen ein Stundensatz verwendet werden.",
    keyFact: "Fliesenleger Stundensatz etwa 45-70 € pro Stunde",
    sections: [
      { heading: "Was kostet ein Fliesenleger pro Stunde?", paragraphs: ["Für einen Fliesenleger-Stundensatz führt BauKostenRadar aktuell etwa 45 bis 70 Euro pro Stunde.", "Material, Anfahrt und Zusatzarbeiten sind nicht automatisch im reinen Stundenpreis enthalten."], table: { headers: ["Fliesenleistung", "Richtwert 2026"], rows: [{ cells: ["Fliesenleger Stundensatz", "45-70 €/h"], href: "/kosten/fliesenleger/leistung/fliesenleger-stundensatz" }] } },
      { heading: "Wann ist Stundenabrechnung üblich?", paragraphs: ["Sie eignet sich besonders für kleinere oder schwer pauschal messbare Arbeiten."], bullets: ["Reparaturen", "kleine Teilflächen", "Zuschnitte und Details", "Nacharbeiten", "Sockel- und Anschlussarbeiten", "Zusatzleistungen"] },
      { heading: "Stunde oder Quadratmeter vergleichen", paragraphs: ["Bei großen, klar definierten Flächen ist ein Quadratmeterpreis meist transparenter. Stundenpreise sollten nicht zusätzlich auf einen bereits vollständigen Flächenpreis gerechnet werden.", "Entscheidend ist immer der dokumentierte Leistungsumfang."] },
    ],
    faqs: [
      { question: "Was kostet ein Fliesenleger pro Stunde 2026?", answer: "Der aktuelle BauKostenRadar-Richtwert liegt bei etwa 45 bis 70 Euro pro Stunde." },
      { question: "Ist Material enthalten?", answer: "Nicht automatisch. Material und weitere Zusatzkosten sollten separat geprüft werden." },
      { question: "Wann wird pro m² abgerechnet?", answer: "Bei klar definierten größeren Flächen ist eine Quadratmeterkalkulation sehr üblich." },
    ],
    related: [
      { label: "Fliesenleger Stundensatz Preisdetail", href: "/kosten/fliesenleger/leistung/fliesenleger-stundensatz" },
      { label: "Fliesenleger Kosten pro m²", href: "/ratgeber/fliesenleger-kosten-pro-qm" },
      { label: "Fliesen verlegen Kosten", href: "/ratgeber/fliesen-verlegen-kosten-pro-qm" },
      { label: "Stundensatz berechnen", href: "/rechner/handwerkerkosten?gewerk=fliesenleger&leistung=fliesenleger-stundensatz" },
    ],
  },
];
