import type { Guide, GuideTable } from "@/lib/guides";

type OpportunityGuideConfig = {
  slug: string;
  title: string;
  h1: string;
  description: string;
  eyebrow: string;
  intro: string;
  keyFact: string;
  priceHeading: string;
  priceParagraphs: string[];
  table?: GuideTable;
  factorsHeading: string;
  factorsIntro: string;
  factors: string[];
  compareHeading: string;
  compareParagraphs: string[];
  faqs: Array<{ question: string; answer: string }>;
  serviceSlug: string;
  itemSlug: string;
  itemLabel: string;
  serviceLabel: string;
  parentSlug: string;
  parentLabel: string;
  relatedExtra?: Array<{ label: string; href: string }>;
};

function createOpportunityGuide(config: OpportunityGuideConfig): Guide {
  return {
    slug: config.slug,
    title: config.title,
    h1: config.h1,
    description: config.description,
    eyebrow: config.eyebrow,
    intro: config.intro,
    keyFact: config.keyFact,
    sections: [
      {
        heading: config.priceHeading,
        paragraphs: config.priceParagraphs,
        ...(config.table ? { table: config.table } : {}),
      },
      {
        heading: config.factorsHeading,
        paragraphs: [config.factorsIntro],
        bullets: config.factors,
      },
      {
        heading: config.compareHeading,
        paragraphs: config.compareParagraphs,
      },
    ],
    faqs: config.faqs,
    related: [
      { label: `${config.itemLabel} Preisdetail`, href: `/kosten/${config.serviceSlug}/leistung/${config.itemSlug}` },
      { label: config.parentLabel, href: `/ratgeber/${config.parentSlug}` },
      { label: `${config.serviceLabel} Kosten`, href: `/kosten/${config.serviceSlug}` },
      ...(config.relatedExtra ?? []),
      { label: "Handwerkerkosten-Rechner", href: `/rechner/handwerkerkosten?gewerk=${config.serviceSlug}&leistung=${config.itemSlug}` },
    ],
  };
}

const configs: OpportunityGuideConfig[] = [
  {
    slug: "waende-streichen-kosten-pro-qm",
    title: "Wände streichen Kosten pro m² 2026",
    h1: "Wände streichen Kosten 2026: Preise pro m² Wandfläche",
    description: "Wände streichen Kosten 2026 pro m²: BauKostenRadar-Richtwerte, Beispielbudgets, Untergrund, Vorarbeiten, Anstriche und Angebotsvergleich.",
    eyebrow: "Innenanstrich 2026",
    intro: "Beim Streichen von Innenwänden entscheidet nicht nur die Farbe über den Preis. Zustand des Untergrunds, Abkleben, Spachtelstellen, Grundierung und die Zahl der Anstriche bestimmen, wie viel Arbeitszeit tatsächlich benötigt wird.",
    keyFact: "Wände streichen etwa 8-20 €/m² Wandfläche in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Wände streichen pro m²?",
    priceParagraphs: [
      "BauKostenRadar führt für Wände streichen etwa 8 bis 20 Euro pro Quadratmeter Wandfläche als Richtwert. Für 100 m² tatsächlich zu streichende Wandfläche ergibt sich damit eine erste Budgetorientierung von etwa 800 bis 2.000 Euro.",
      "Wandfläche und Wohnfläche sind nicht identisch. Für ein belastbares Angebot sollte deshalb klar sein, welche Decken, Wände, Laibungen und Nebenflächen wirklich bearbeitet werden.",
    ],
    table: { headers: ["Wandfläche", "Budgetorientierung"], rows: [
      { cells: ["50 m²", "400-1.000 €"] },
      { cells: ["100 m²", "800-2.000 €"] },
      { cells: ["200 m²", "1.600-4.000 €"] },
    ] },
    factorsHeading: "Welche Faktoren verändern den Malerpreis?",
    factorsIntro: "Ein glatter, heller und leerer Raum ist deutlich schneller zu streichen als ein stark beschädigter Bestand mit vielen Schutzarbeiten.",
    factors: ["Spachteln, Schleifen und Grundieren", "Ein oder mehrere deckende Anstriche", "Starker Farbwechsel oder intensive Farbtöne", "Abkleben von Fenstern, Türen und Einbauten", "Raumhöhe, Treppenhäuser und schlechte Zugänglichkeit", "Möbel räumen und Bodenflächen schützen"],
    compareHeading: "Angebote nach Wandfläche und Leistungsumfang vergleichen",
    compareParagraphs: ["Lassen Sie die berechnete Fläche sowie Vorarbeiten und Anzahl der Anstriche im Angebot benennen. Ein niedriger Quadratmeterpreis ist wenig aussagekräftig, wenn Spachteln, Abdecken oder Grundieren später zusätzlich berechnet werden.", "Für regionale Budgetwerte können Sie die Leistung im Handwerkerkosten-Rechner mit dem Modellfaktor Ihrer Stadt kombinieren."],
    faqs: [
      { question: "Was kostet Wände streichen pro m² 2026?", answer: "BauKostenRadar führt etwa 8 bis 20 Euro pro Quadratmeter Wandfläche als Richtwert." },
      { question: "Was kosten 100 m² Wände streichen?", answer: "Aus dem BauKostenRadar-Richtwert ergeben sich für 100 m² Wandfläche ungefähr 800 bis 2.000 Euro als erste Orientierung." },
      { question: "Wird nach Wohnfläche oder Wandfläche gerechnet?", answer: "Die verwendete Preisposition bezieht sich auf Wandfläche. Wohnfläche und tatsächlich zu streichende Fläche sollten nicht gleichgesetzt werden." },
    ],
    serviceSlug: "maler", itemSlug: "waende-streichen", itemLabel: "Wände streichen", serviceLabel: "Maler", parentSlug: "maler-kosten-pro-qm", parentLabel: "Maler Kosten pro m²",
  },
  {
    slug: "tapezieren-kosten-pro-qm",
    title: "Tapezieren Kosten pro m² 2026",
    h1: "Tapezieren Kosten 2026: Preise pro m² inklusive Tapete",
    description: "Tapezieren Kosten 2026 pro m²: BauKostenRadar-Richtwerte inklusive Tapete, Beispielbudgets, Tapetenarten, Untergrund und Angebotscheck.",
    eyebrow: "Tapezierarbeiten 2026",
    intro: "Beim Tapezieren entstehen Preisunterschiede vor allem durch Tapetenart, Untergrund und Zuschnitt. Muster, viele Ecken und alte Beläge können den Arbeitsaufwand deutlich erhöhen.",
    keyFact: "Tapezieren inklusive Tapete etwa 12-30 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Tapezieren pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Tapezieren inklusive Tapete etwa 12 bis 30 Euro pro Quadratmeter als Richtwert. Bei 100 m² Tapezierfläche entspricht das ungefähr 1.200 bis 3.000 Euro als Budgetorientierung.", "Bei hochwertigen Design- oder Spezialtapeten kann das Material allein deutlich teurer sein. Deshalb sollte die angebotene Tapete genau beschrieben werden."],
    table: { headers: ["Tapezierfläche", "Budgetorientierung"], rows: [
      { cells: ["50 m²", "600-1.500 €"] },
      { cells: ["100 m²", "1.200-3.000 €"] },
      { cells: ["200 m²", "2.400-6.000 €"] },
    ] },
    factorsHeading: "Was beeinflusst Tapezierkosten?",
    factorsIntro: "Die reine Bahnfläche ist nur ein Teil des Aufwands. Vorarbeiten und Rapporte können mehr Zeit kosten als das eigentliche Kleben.",
    factors: ["Raufaser, Vlies, Papier oder Mustertapete", "Alte Tapete entfernen", "Spachteln und Grundieren des Untergrunds", "Musterrapport und Verschnitt", "Viele Fenster, Türen und Nischen", "Zusätzlicher Anstrich nach dem Tapezieren"],
    compareHeading: "Tapetenmaterial und Arbeitsleistung sauber trennen",
    compareParagraphs: ["Vergleichen Sie nur Angebote mit ähnlicher Tapetenqualität und gleichem Untergrundzustand. Bei Materialpauschalen sollte erkennbar sein, welche Tapete einkalkuliert wurde.", "Wenn alte Beläge entfernt oder Wände vollflächig gespachtelt werden müssen, sollten diese Positionen separat ausgewiesen sein."],
    faqs: [
      { question: "Was kostet Tapezieren pro m² 2026?", answer: "BauKostenRadar führt etwa 12 bis 30 Euro pro Quadratmeter inklusive Tapete als Richtwert." },
      { question: "Was kosten 100 m² Tapezieren?", answer: "Mit der BauKostenRadar-Spanne ergeben sich für 100 m² etwa 1.200 bis 3.000 Euro als erste Budgetorientierung." },
      { question: "Ist das Entfernen alter Tapeten enthalten?", answer: "Nicht automatisch. Rückbau und Untergrundvorbereitung sollten im konkreten Angebot ausdrücklich ausgewiesen werden." },
    ],
    serviceSlug: "maler", itemSlug: "tapezieren-inkl-tapete", itemLabel: "Tapezieren", serviceLabel: "Maler", parentSlug: "maler-kosten-pro-qm", parentLabel: "Maler Kosten pro m²",
  },
  {
    slug: "innenputz-q3-kosten-pro-qm",
    title: "Innenputz Q3 Kosten pro m² 2026",
    h1: "Innenputz und Glätten Q3 Kosten 2026: Richtwerte pro m²",
    description: "Innenputz und Glätten Q3 Kosten 2026: BauKostenRadar-Richtwerte pro m², Beispielbudgets, Untergrund, Qualitätsstufe und Angebotsvergleich.",
    eyebrow: "Innenputz Q3 2026",
    intro: "Bei glatten Innenflächen ist die gewünschte Oberflächenqualität entscheidend. Q3 beschreibt einen erhöhten Glättungsaufwand gegenüber einer einfachen Standardverspachtelung und muss zusammen mit dem vorhandenen Untergrund betrachtet werden.",
    keyFact: "Innenputz oder Glätten Q3 etwa 15-35 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Innenputz oder Glätten Q3 pro m²?",
    priceParagraphs: ["Für die Preisposition Innenputz / Glätten Q3 führt BauKostenRadar etwa 15 bis 35 Euro pro Quadratmeter. Bei 100 m² ergibt sich daraus eine erste Orientierung von rund 1.500 bis 3.500 Euro.", "Die Position bündelt Innenputz beziehungsweise Glätten auf Q3-Niveau. Bei konkreten Angeboten muss deshalb klar sein, ob Neuputz, Überarbeitung eines Bestandsputzes oder reine Feinspachtelung gemeint ist."],
    table: { headers: ["Fläche", "Budgetorientierung"], rows: [
      { cells: ["50 m²", "750-1.750 €"] },
      { cells: ["100 m²", "1.500-3.500 €"] },
      { cells: ["200 m²", "3.000-7.000 €"] },
    ] },
    factorsHeading: "Was verändert die Kosten für Q3-Flächen?",
    factorsIntro: "Je unebener oder rissiger der Untergrund, desto mehr Arbeitsgänge sind vor der fertigen Oberfläche nötig.",
    factors: ["Neuputz oder Überarbeitung vorhandener Flächen", "Risse, Unebenheiten und lose Altbeschichtungen", "Erforderliche Schichtdicken", "Eckschutz, Laibungen und Anschlüsse", "Schleifaufwand und Staubschutz", "Gewünschte Endbeschichtung"],
    compareHeading: "Q2, Q3 und Q4 nicht vermischen",
    compareParagraphs: ["Oberflächenqualitäten sollten im Angebot ausdrücklich genannt werden. Ein Q3-Angebot ist nicht direkt mit einer einfachen Q2-Verspachtelung oder einer besonders glatten Q4-Oberfläche vergleichbar.", "Bei Trockenbauflächen mit Q4-Anforderung steht auf BauKostenRadar eine separate Preisposition zur Verfügung."],
    faqs: [
      { question: "Was kostet Innenputz Q3 pro m² 2026?", answer: "BauKostenRadar führt für Innenputz / Glätten Q3 etwa 15 bis 35 Euro pro Quadratmeter als Richtwert." },
      { question: "Was kosten 100 m² Q3-Fläche?", answer: "Rechnerisch ergeben sich mit dem Richtwert etwa 1.500 bis 3.500 Euro als Budgetorientierung." },
      { question: "Ist Q3 dasselbe wie Q4?", answer: "Nein. Q4 verlangt eine noch hochwertigere, vollflächig geglättete Oberfläche und ist deshalb separat zu kalkulieren." },
    ],
    serviceSlug: "maler", itemSlug: "innenputz-glaetten-q3", itemLabel: "Innenputz Q3", serviceLabel: "Maler", parentSlug: "maler-kosten-pro-qm", parentLabel: "Maler Kosten pro m²",
    relatedExtra: [{ label: "Verspachtelung Q4 Kosten", href: "/ratgeber/verspachtelung-q4-kosten-pro-qm" }],
  },
  {
    slug: "fliesen-verlegen-kosten-pro-qm",
    title: "Fliesen verlegen Kosten pro m² 2026",
    h1: "Fliesen verlegen Kosten 2026: Standardfliesen pro m²",
    description: "Fliesen verlegen Kosten 2026 pro m²: BauKostenRadar-Richtwerte für die Arbeit, Beispielbudgets, Untergrund, Zuschnitte und Angebotsvergleich.",
    eyebrow: "Fliesenarbeiten 2026",
    intro: "Bei Standardfliesen bestimmen Fläche, Untergrund und Zuschnitte den Arbeitsaufwand. Materialpreise für die Fliesen selbst sollten getrennt betrachtet werden, wenn die Preisposition ausdrücklich nur die Verlegearbeit beschreibt.",
    keyFact: "Standard-Fliesen verlegen etwa 45-85 €/m² Arbeit in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Fliesen verlegen pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Standard-Fliesen verlegen etwa 45 bis 85 Euro pro Quadratmeter Arbeitsleistung. Für 20 m² ergibt sich damit eine erste Orientierung von etwa 900 bis 1.700 Euro für diese Preisposition.", "Fliesenmaterial, Rückbau alter Beläge, Untergrundausgleich und Abdichtung können je nach Projekt zusätzlich anfallen."],
    table: { headers: ["Fliesenfläche", "Budgetorientierung Arbeit"], rows: [
      { cells: ["10 m²", "450-850 €"] },
      { cells: ["20 m²", "900-1.700 €"] },
      { cells: ["40 m²", "1.800-3.400 €"] },
    ] },
    factorsHeading: "Welche Faktoren treiben die Verlegekosten?",
    factorsIntro: "Gerade bei kleinen Bädern oder stark gegliederten Flächen kann der Zeitaufwand pro Quadratmeter höher sein als auf einer großen freien Bodenfläche.",
    factors: ["Zustand und Ebenheit des Untergrunds", "Wand- oder Bodenfläche", "Anzahl der Zuschnitte und Durchdringungen", "Sockel, Schienen und Abschlussprofile", "Verlegemuster und Fugenbild", "Rückbau, Entsorgung und Abdichtung"],
    compareHeading: "Arbeitskosten und Fliesenmaterial getrennt prüfen",
    compareParagraphs: ["Die BauKostenRadar-Position ist als Arbeitspreis formuliert. Ein Komplettangebot inklusive Fliesenmaterial darf deshalb nicht direkt mit diesem reinen Arbeitsrichtwert verglichen werden.", "Bei XXL-Fliesen ab 80 x 80 cm sollte die separate Großformat-Preisposition verwendet werden."],
    faqs: [
      { question: "Was kostet Fliesen verlegen pro m² 2026?", answer: "BauKostenRadar führt für Standardfliesen etwa 45 bis 85 Euro pro Quadratmeter Arbeitsleistung als Richtwert." },
      { question: "Was kostet die Arbeit für 20 m² Fliesen?", answer: "Mit dem Richtwert ergeben sich etwa 900 bis 1.700 Euro für die Verlegearbeit." },
      { question: "Sind die Fliesen im Richtwert enthalten?", answer: "Nein. Die verwendete Preisposition ist ausdrücklich als Arbeit pro Quadratmeter bezeichnet." },
    ],
    serviceSlug: "fliesenleger", itemSlug: "standard-fliesen-verlegen", itemLabel: "Standard-Fliesen verlegen", serviceLabel: "Fliesenleger", parentSlug: "fliesenleger-kosten-pro-qm", parentLabel: "Fliesenleger Kosten pro m²",
    relatedExtra: [{ label: "Großformat-Fliesen verlegen Kosten", href: "/ratgeber/grossformat-fliesen-verlegen-kosten" }],
  },
  {
    slug: "grossformat-fliesen-verlegen-kosten",
    title: "Großformat-Fliesen verlegen Kosten 2026",
    h1: "Großformat-Fliesen verlegen Kosten 2026: Preise ab 80 x 80 cm",
    description: "Großformat-Fliesen verlegen Kosten 2026: BauKostenRadar-Richtwerte pro m² Arbeit, Handling, Untergrund, Zuschnitte und Angebotscheck.",
    eyebrow: "XXL-Fliesen 2026",
    intro: "Großformatige Fliesen verlangen einen besonders ebenen Untergrund, präzises Handling und saubere Ausrichtung. Schon wenige Platten können schwer und unhandlich sein, wodurch sich der Arbeitsaufwand gegenüber Standardformaten erhöht.",
    keyFact: "Großformat ab 80 x 80 cm etwa 60-110 €/m² Arbeit in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet das Verlegen von Großformat-Fliesen?",
    priceParagraphs: ["Für Großformat ab 80 x 80 cm führt BauKostenRadar etwa 60 bis 110 Euro pro Quadratmeter Arbeitsleistung. Bei 20 m² entspricht das rund 1.200 bis 2.200 Euro als erste Orientierung.", "Die Fliesen selbst, Untergrundkorrekturen, Spezialkleber oder Abdichtung können zusätzlich berechnet werden."],
    table: { headers: ["Fliesenfläche", "Budgetorientierung Arbeit"], rows: [
      { cells: ["10 m²", "600-1.100 €"] },
      { cells: ["20 m²", "1.200-2.200 €"] },
      { cells: ["40 m²", "2.400-4.400 €"] },
    ] },
    factorsHeading: "Warum kosten XXL-Fliesen mehr?",
    factorsIntro: "Das Format erhöht Anforderungen an Untergrund, Werkzeug und häufig auch an die Zahl der Monteure.",
    factors: ["Plattengröße und Gewicht", "Ebenheit des Untergrunds", "Nivelliersystem und Kleberbett", "Zuschnitte an Kanten und Durchdringungen", "Transport und Bruchrisiko", "Wandmontage oder schwer zugängliche Bereiche"],
    compareHeading: "Standardformat und Großformat separat kalkulieren",
    compareParagraphs: ["Ein Standard-Fliesenpreis ist keine verlässliche Grundlage für XXL-Formate. Prüfen Sie bei Angeboten Format, Verlegemuster, Untergrundvorbereitung und enthaltene Zuschnitte.", "Für einfache Standardformate steht eine separate BauKostenRadar-Preisposition zur Verfügung."],
    faqs: [
      { question: "Was kostet Großformat-Fliesen verlegen pro m² 2026?", answer: "BauKostenRadar führt für Formate ab 80 x 80 cm etwa 60 bis 110 Euro pro Quadratmeter Arbeitsleistung." },
      { question: "Was kosten 20 m² Großformat-Fliesen verlegen?", answer: "Aus dem Richtwert ergeben sich etwa 1.200 bis 2.200 Euro für die Verlegearbeit." },
      { question: "Warum sind große Fliesen teurer zu verlegen?", answer: "Vor allem Handling, Gewicht, Untergrundgenauigkeit und aufwendige Zuschnitte erhöhen den Arbeitsaufwand." },
    ],
    serviceSlug: "fliesenleger", itemSlug: "grossformat-ab-80-x-80-cm", itemLabel: "Großformat-Fliesen", serviceLabel: "Fliesenleger", parentSlug: "fliesenleger-kosten-pro-qm", parentLabel: "Fliesenleger Kosten pro m²",
    relatedExtra: [{ label: "Standard-Fliesen verlegen Kosten", href: "/ratgeber/fliesen-verlegen-kosten-pro-qm" }],
  },
  {
    slug: "steckdose-installieren-kosten",
    title: "Steckdose installieren Kosten 2026",
    h1: "Steckdose installieren Kosten 2026: Richtwerte pro Stück",
    description: "Steckdose installieren Kosten 2026: BauKostenRadar-Richtwert pro Stück, Leitungswege, Schlitze, Absicherung und Angebotsvergleich.",
    eyebrow: "Elektroinstallation 2026",
    intro: "Eine zusätzliche Steckdose kann ein kleiner Montageauftrag oder Teil einer deutlich größeren Elektroarbeit sein. Entscheidend ist, ob Leitung, Dose und Absicherung bereits vorhanden sind oder neu hergestellt werden müssen.",
    keyFact: "Steckdose installieren etwa 80-150 € pro Stück in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet es, eine Steckdose installieren zu lassen?",
    priceParagraphs: ["BauKostenRadar führt für Steckdose installieren etwa 80 bis 150 Euro pro Stück als Richtwert. Für fünf Steckdosen ergibt sich damit rechnerisch eine erste Orientierung von etwa 400 bis 750 Euro.", "Lange Leitungswege, neue Stromkreise, Schlitze oder Arbeiten am Verteiler können zusätzliche Kosten verursachen."],
    table: { headers: ["Anzahl", "Budgetorientierung"], rows: [
      { cells: ["1 Steckdose", "80-150 €"] },
      { cells: ["5 Steckdosen", "400-750 €"] },
      { cells: ["10 Steckdosen", "800-1.500 €"] },
    ] },
    factorsHeading: "Was beeinflusst den Preis pro Steckdose?",
    factorsIntro: "Die sichtbare Steckdose ist nur der Endpunkt. Der eigentliche Aufwand steckt häufig im Leitungsweg und in der vorhandenen Elektroanlage.",
    factors: ["Vorhandener oder neuer Stromkreis", "Unterputz, Aufputz oder Trockenbau", "Länge des Leitungswegs", "Schlitzen, Bohren und Wiederherstellen", "Schalterprogramm und Steckdosentyp", "Prüfung und Dokumentation der Elektroanlage"],
    compareHeading: "Einzelne Steckdose und komplette Neuinstallation unterscheiden",
    compareParagraphs: ["Bei mehreren neuen Stromkreisen oder einer alten Elektroanlage kann eine größere Teilmodernisierung sinnvoller sein als viele einzeln kalkulierte Steckdosen. Lassen Sie zusätzliche Leitungs- und Verteilerarbeiten separat ausweisen.", "Arbeiten an elektrischen Anlagen gehören in die Hände eines qualifizierten Fachbetriebs."],
    faqs: [
      { question: "Was kostet eine Steckdose installieren 2026?", answer: "BauKostenRadar führt etwa 80 bis 150 Euro pro Stück als Richtwert." },
      { question: "Was kosten fünf neue Steckdosen?", answer: "Rechnerisch ergeben sich aus dem Richtwert etwa 400 bis 750 Euro, sofern keine umfangreichen Zusatzarbeiten nötig sind." },
      { question: "Sind neue Leitungen automatisch enthalten?", answer: "Nicht zwingend. Leitungswege, neue Stromkreise und Arbeiten am Verteiler sollten im Angebot separat beschrieben sein." },
    ],
    serviceSlug: "elektriker", itemSlug: "steckdose-installieren", itemLabel: "Steckdose installieren", serviceLabel: "Elektriker", parentSlug: "elektrik-erneuern-altbau", parentLabel: "Elektrik erneuern Kosten",
  },
  {
    slug: "dach-neu-eindecken-kosten-pro-qm",
    title: "Dach neu eindecken Kosten pro m² 2026",
    h1: "Dach neu eindecken Kosten 2026: Richtwerte pro m² inklusive Lattung",
    description: "Dach neu eindecken Kosten 2026 pro m²: BauKostenRadar-Richtwerte inklusive Lattung, Beispielbudgets, Dachform, Material und Nebenarbeiten.",
    eyebrow: "Dacheindeckung 2026",
    intro: "Beim Neueindecken eines Dachs bestimmen Dachform, Deckmaterial, Anschlüsse und der Zustand der Unterkonstruktion den Preis. Gerüst, Rückbau und Dämmung sollten dabei nicht automatisch mit der eigentlichen Neueindeckung gleichgesetzt werden.",
    keyFact: "Neueindeckung inklusive Lattung etwa 120-250 €/m² Dachfläche in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Dach neu eindecken pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Neueindeckung inklusive Lattung etwa 120 bis 250 Euro pro Quadratmeter Dachfläche. Bei 150 m² ergibt sich daraus eine Orientierung von ungefähr 18.000 bis 37.500 Euro für diese Preisposition.", "Gerüst, Entsorgung einer alten Deckung, zusätzliche Holzarbeiten und Dämmmaßnahmen können je nach Projekt separat hinzukommen."],
    table: { headers: ["Dachfläche", "Budgetorientierung"], rows: [
      { cells: ["100 m²", "12.000-25.000 €"] },
      { cells: ["150 m²", "18.000-37.500 €"] },
      { cells: ["200 m²", "24.000-50.000 €"] },
    ] },
    factorsHeading: "Was treibt die Kosten einer Neueindeckung?",
    factorsIntro: "Je komplizierter Geometrie und Anschlüsse, desto mehr Arbeitszeit fällt je Quadratmeter an.",
    factors: ["Dachziegel, Betonstein oder andere Deckmaterialien", "Dachneigung, Gauben und Kehlen", "Zustand von Lattung und Unterkonstruktion", "Anschlüsse an Kamin, Fenster und Ortgang", "Rückbau und Entsorgung der alten Deckung", "Gerüst und Zugänglichkeit der Baustelle"],
    compareHeading: "Neueindeckung und komplette Dachsanierung trennen",
    compareParagraphs: ["Eine komplette energetische Dachsanierung kann zusätzlich Dämmung, Luftdichtheit und weitere Schichten umfassen. Vergleichen Sie deshalb nur Angebote mit gleichem Leistungsumfang.", "Für Aufsparren- und Zwischensparrendämmung stehen separate BauKostenRadar-Preispositionen zur Verfügung."],
    faqs: [
      { question: "Was kostet Dach neu eindecken pro m² 2026?", answer: "BauKostenRadar führt etwa 120 bis 250 Euro pro Quadratmeter Dachfläche inklusive Lattung als Richtwert." },
      { question: "Was kosten 150 m² Dach neu eindecken?", answer: "Mit dem Richtwert ergeben sich etwa 18.000 bis 37.500 Euro als erste Budgetorientierung." },
      { question: "Ist die Dämmung im Richtwert enthalten?", answer: "Nein, nicht automatisch. Die Preisposition beschreibt die Neueindeckung inklusive Lattung. Dämmung sollte separat kalkuliert werden." },
    ],
    serviceSlug: "dachsanierung", itemSlug: "neueindeckung-inkl-lattung", itemLabel: "Dach neu eindecken", serviceLabel: "Dachsanierung", parentSlug: "dach-sanieren-kosten-pro-qm", parentLabel: "Dach sanieren Kosten pro m²",
  },
  {
    slug: "vinylboden-verlegen-kosten-pro-qm",
    title: "Vinylboden verlegen Kosten pro m² 2026",
    h1: "Vinylboden verlegen Kosten 2026: Klickvinyl inklusive Material",
    description: "Vinylboden verlegen Kosten 2026 pro m²: BauKostenRadar-Richtwerte für Klickvinyl inklusive Material, Untergrund, Sockelleisten und Angebotscheck.",
    eyebrow: "Vinylboden 2026",
    intro: "Klickvinyl lässt sich vergleichsweise schnell verlegen, doch ein unebener Untergrund kann das Projekt deutlich verteuern. Für den Preisvergleich sollten Belagsqualität, Unterlage, Sockelleisten und Vorarbeiten gemeinsam betrachtet werden.",
    keyFact: "Klickvinyl inklusive Material etwa 35-65 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Klickvinyl inklusive Material pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Vinylboden Klick inklusive Material etwa 35 bis 65 Euro pro Quadratmeter. Bei 50 m² ergibt sich daraus eine erste Budgetorientierung von ungefähr 1.750 bis 3.250 Euro.", "Untergrundausgleich, Rückbau alter Beläge und Sockelleisten können abhängig vom Angebot zusätzlich berechnet werden."],
    table: { headers: ["Bodenfläche", "Budgetorientierung"], rows: [
      { cells: ["20 m²", "700-1.300 €"] },
      { cells: ["50 m²", "1.750-3.250 €"] },
      { cells: ["100 m²", "3.500-6.500 €"] },
    ] },
    factorsHeading: "Welche Faktoren beeinflussen Vinylboden-Kosten?",
    factorsIntro: "Der Untergrund ist oft wichtiger als die reine Verlegegeschwindigkeit des Klicksystems.",
    factors: ["Qualität und Nutzungsklasse des Vinylbodens", "Unterlage und Trittschall", "Ebenheit und Feuchte des Untergrunds", "Alten Boden entfernen und entsorgen", "Sockelleisten und Übergangsprofile", "Viele Türen, Nischen und Zuschnitte"],
    compareHeading: "Klickvinyl, Klebevinyl und Laminat nicht vermischen",
    compareParagraphs: ["Die BauKostenRadar-Position bezieht sich ausdrücklich auf Klickvinyl inklusive Material. Klebevinyl kann andere Anforderungen an den Untergrund und damit einen anderen Preis haben.", "Für Laminat und Parkett stehen eigene Preispositionen und Ratgeber zur Verfügung."],
    faqs: [
      { question: "Was kostet Vinylboden verlegen pro m² 2026?", answer: "BauKostenRadar führt für Klickvinyl inklusive Material etwa 35 bis 65 Euro pro Quadratmeter als Richtwert." },
      { question: "Was kosten 50 m² Klickvinyl?", answer: "Mit dem Richtwert ergeben sich ungefähr 1.750 bis 3.250 Euro als Budgetorientierung." },
      { question: "Ist das Vinylmaterial enthalten?", answer: "Ja. Die verwendete BauKostenRadar-Preisposition ist ausdrücklich als Klickvinyl inklusive Material bezeichnet." },
    ],
    serviceSlug: "bodenleger", itemSlug: "vinylboden-klick-inkl-material", itemLabel: "Vinylboden Klick", serviceLabel: "Bodenleger", parentSlug: "bodenleger-kosten-pro-qm", parentLabel: "Bodenleger Kosten pro m²",
  },
  {
    slug: "verspachtelung-q4-kosten-pro-qm",
    title: "Verspachtelung Q4 Kosten pro m² 2026",
    h1: "Verspachtelung Q4 Kosten 2026: Richtwerte pro m²",
    description: "Verspachtelung Q4 Kosten 2026 pro m²: BauKostenRadar-Richtwerte, Beispielbudgets, Oberflächenqualität, Schleifen und Angebotsvergleich.",
    eyebrow: "Q4-Oberfläche 2026",
    intro: "Q4 ist eine besonders hohe Oberflächenanforderung und wird typischerweise gewählt, wenn sehr glatte, streiflichtempfindliche oder hochwertige Endoberflächen geplant sind. Der Aufwand liegt deutlich über einer normalen Fugenverspachtelung.",
    keyFact: "Verspachtelung Q4 etwa 94-103 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Verspachtelung Q4 pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Verspachtelung Q4 etwa 94 bis 103 Euro pro Quadratmeter. Für 50 m² ergibt sich daraus eine Orientierung von ungefähr 4.700 bis 5.150 Euro für diese definierte Preisposition.", "Der Richtwert sollte nicht mit den Kosten einer kompletten Trockenbauwand verwechselt werden. Q4 beschreibt die hochwertige Oberflächenbearbeitung."],
    table: { headers: ["Q4-Fläche", "Budgetorientierung"], rows: [
      { cells: ["20 m²", "1.880-2.060 €"] },
      { cells: ["50 m²", "4.700-5.150 €"] },
      { cells: ["100 m²", "9.400-10.300 €"] },
    ] },
    factorsHeading: "Was beeinflusst den Q4-Aufwand?",
    factorsIntro: "Die Ausgangsfläche und die Anforderungen an das spätere Lichtbild entscheiden, wie viele Arbeitsgänge nötig sind.",
    factors: ["Qualität der vorhandenen Beplankung", "Vollflächige Spachtelung statt reiner Fugenbearbeitung", "Mehrere Schleif- und Kontrollgänge", "Streiflicht und hochwertige Anstriche", "Ecken, Laibungen und Anschlüsse", "Staubschutz und Baustellenlogistik"],
    compareHeading: "Q3 und Q4 klar unterscheiden",
    compareParagraphs: ["Ein Q4-Angebot sollte die geforderte Oberflächenqualität eindeutig benennen. Q3 und Q4 sind nicht austauschbar, weil Q4 zusätzliche vollflächige Arbeitsschritte erfordert.", "Für Malerflächen mit Q3-Anforderung steht ein eigener Ratgeber bereit."],
    faqs: [
      { question: "Was kostet Q4 Spachteln pro m² 2026?", answer: "BauKostenRadar führt für Verspachtelung Q4 etwa 94 bis 103 Euro pro Quadratmeter als Richtwert." },
      { question: "Was kosten 50 m² Q4?", answer: "Rechnerisch ergeben sich ungefähr 4.700 bis 5.150 Euro als Budgetorientierung für die definierte Preisposition." },
      { question: "Ist Q4 eine komplette Trockenbauwand?", answer: "Nein. Q4 beschreibt die besonders hochwertige Oberflächenbearbeitung und ist nicht mit dem gesamten Wandaufbau gleichzusetzen." },
    ],
    serviceSlug: "trockenbau", itemSlug: "verspachtelung-q4", itemLabel: "Verspachtelung Q4", serviceLabel: "Trockenbau", parentSlug: "trockenbau-kosten-pro-qm", parentLabel: "Trockenbau Kosten pro m²",
    relatedExtra: [{ label: "Innenputz Q3 Kosten", href: "/ratgeber/innenputz-q3-kosten-pro-qm" }],
  },
  {
    slug: "luft-wasser-waermepumpe-kosten",
    title: "Luft-Wasser-Wärmepumpe Kosten 2026",
    h1: "Luft-Wasser-Wärmepumpe Kosten 2026: Komplettanlage vor Förderung",
    description: "Luft-Wasser-Wärmepumpe Kosten 2026: BauKostenRadar-Richtwert für die komplette Anlage vor Förderung, Kostenblöcke und Angebotsvergleich.",
    eyebrow: "Wärmepumpe 2026",
    intro: "Bei einer Luft-Wasser-Wärmepumpe ist der Anlagenpreis nur ein Teil des Projekts. Hydraulik, Elektroarbeiten, Warmwasserbereitung, Aufstellort und Anpassungen im Heizsystem bestimmen den Gesamtumfang.",
    keyFact: "Luft-Wasser-Wärmepumpe komplett etwa 25.000-45.000 € pro Anlage vor Förderung in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet eine komplette Luft-Wasser-Wärmepumpe?",
    priceParagraphs: ["BauKostenRadar führt für eine komplette Luft-Wasser-Wärmepumpe etwa 25.000 bis 45.000 Euro pro Anlage vor Förderung als Richtwert. Der Wert dient der Budgetplanung und ersetzt keine objektspezifische Heizlast- und Anlagenplanung.", "Förderung, vorhandene Heizflächen und notwendige Umbauten können die individuelle Investition beziehungsweise Eigenbelastung deutlich verändern."],
    factorsHeading: "Welche Kostenblöcke gehören zum Wärmepumpenprojekt?",
    factorsIntro: "Zwei Anlagen mit gleicher Nennleistung können aufgrund des Gebäudes und der vorhandenen Haustechnik unterschiedlich teuer werden.",
    factors: ["Wärmepumpengerät und Leistungsgröße", "Hydraulik, Speicher und Warmwasserbereitung", "Elektroanschluss und mögliche Anpassungen", "Fundament, Leitungswege und Aufstellort", "Demontage einer vorhandenen Heizung", "Anpassung von Heizkörpern oder hydraulischem System"],
    compareHeading: "Anlagenpreis, Installation und Förderung getrennt lesen",
    compareParagraphs: ["Vergleichen Sie Angebote danach, ob Gerät, Montage, Elektroarbeiten, Speicher, Inbetriebnahme und Entsorgung enthalten sind. Ein reiner Gerätepreis ist nicht mit einem Komplettangebot vergleichbar.", "Die BauKostenRadar-Spanne ist als Wert vor Förderung gekennzeichnet. Förderbedingungen sollten zum Zeitpunkt der Entscheidung separat geprüft werden."],
    faqs: [
      { question: "Was kostet eine Luft-Wasser-Wärmepumpe 2026?", answer: "BauKostenRadar führt für eine komplette Anlage etwa 25.000 bis 45.000 Euro vor Förderung als Richtwert." },
      { question: "Ist die Installation enthalten?", answer: "Die Preisposition ist als komplette Luft-Wasser-Wärmepumpe formuliert. Der konkrete Angebotsumfang sollte trotzdem Position für Position geprüft werden." },
      { question: "Sind Förderungen schon abgezogen?", answer: "Nein. Der BauKostenRadar-Richtwert ist ausdrücklich als Preis vor Förderung angegeben." },
    ],
    serviceSlug: "waermepumpe", itemSlug: "luft-wasser-waermepumpe-komplett", itemLabel: "Luft-Wasser-Wärmepumpe komplett", serviceLabel: "Wärmepumpe", parentSlug: "waermepumpe-kosten-2026", parentLabel: "Wärmepumpe Kosten 2026",
    relatedExtra: [{ label: "Wärmepumpe Wartung Kosten", href: "/ratgeber/waermepumpe-wartung-kosten" }],
  },
  {
    slug: "photovoltaik-10-kwp-kosten",
    title: "Photovoltaik 10 kWp Kosten 2026",
    h1: "Photovoltaik 10 kWp Kosten 2026: Anlage inklusive Installation",
    description: "Photovoltaik 10 kWp Kosten 2026: BauKostenRadar-Richtwerte inklusive Installation, Dach, Wechselrichter, Elektroarbeiten und Vergleich mit Speicher.",
    eyebrow: "PV 10 kWp 2026",
    intro: "Eine 10-kWp-Anlage ist eine häufige Größenordnung für Einfamilienhäuser. Für einen sinnvollen Preisvergleich sollten Module, Wechselrichter, Unterkonstruktion, Montage, Elektroarbeiten und Inbetriebnahme gemeinsam betrachtet werden.",
    keyFact: "PV-Anlage 10 kWp inklusive Installation etwa 9.200-10.400 € in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet eine 10-kWp-PV-Anlage?",
    priceParagraphs: ["BauKostenRadar führt für eine PV-Anlage mit 10 kWp inklusive Installation etwa 9.200 bis 10.400 Euro pro Anlage. Diese Preisposition eignet sich als erste Orientierung für ein System ohne die separate Speicherposition.", "Dachzugang, Gerüst, Zählerschrank oder besondere Elektroarbeiten können je nach Objekt zusätzlichen Aufwand verursachen."],
    factorsHeading: "Welche Faktoren verändern den PV-Preis?",
    factorsIntro: "Die reine Modulleistung erklärt den Endpreis nicht vollständig. Dach und Elektroanlage können relevante Zusatzkosten verursachen.",
    factors: ["Modul- und Wechselrichterqualität", "Dachform, Neigung und Zugänglichkeit", "Unterkonstruktion und Montageaufwand", "Gerüst oder andere Absturzsicherung", "Zählerschrank und Elektroarbeiten", "Monitoring, Optimierer und zusätzliche Komponenten"],
    compareHeading: "10 kWp ohne Speicher und Komplettsystem mit Speicher trennen",
    compareParagraphs: ["Ein Angebot mit Batteriespeicher darf nicht direkt mit der reinen 10-kWp-Anlage verglichen werden. BauKostenRadar führt dafür eine separate Preisposition mit etwa 10 kWh Speicher.", "Prüfen Sie außerdem, ob Netzanschlussarbeiten und eventuelle Anpassungen am Zählerschrank enthalten sind."],
    faqs: [
      { question: "Was kostet eine 10-kWp-PV-Anlage 2026?", answer: "BauKostenRadar führt etwa 9.200 bis 10.400 Euro pro Anlage inklusive Installation als Richtwert." },
      { question: "Ist ein Batteriespeicher enthalten?", answer: "Nicht in dieser Preisposition. Für 10 kWp PV plus etwa 10 kWh Speicher gibt es auf BauKostenRadar einen separaten Richtwert." },
      { question: "Warum können Angebote trotz gleicher kWp stark variieren?", answer: "Dach, Komponentenqualität, Gerüst, Zählerschrank und weitere Elektroarbeiten können den Gesamtpreis verändern." },
    ],
    serviceSlug: "photovoltaik", itemSlug: "pv-anlage-10-kwp-inkl-installation", itemLabel: "PV-Anlage 10 kWp", serviceLabel: "Photovoltaik", parentSlug: "photovoltaik-kosten-2026", parentLabel: "Photovoltaik Kosten 2026",
    relatedExtra: [{ label: "Photovoltaik mit Speicher Kosten", href: "/ratgeber/photovoltaik-mit-speicher-kosten" }],
  },
  {
    slug: "photovoltaik-mit-speicher-kosten",
    title: "Photovoltaik mit Speicher Kosten 2026",
    h1: "Photovoltaik mit Speicher Kosten 2026: 10 kWp plus etwa 10 kWh",
    description: "Photovoltaik mit Speicher Kosten 2026: BauKostenRadar-Richtwert für 10 kWp PV plus etwa 10 kWh Speicher, Kostenblöcke und Angebotsvergleich.",
    eyebrow: "PV mit Speicher 2026",
    intro: "Bei PV-Komplettsystemen mit Speicher bestimmen nicht nur Module und Batteriekapazität den Preis. Wechselrichterkonzept, Elektroinstallation, Energiemanagement und Einbindung in die Hausanlage gehören ebenfalls zum Vergleich.",
    keyFact: "10 kWp PV plus etwa 10 kWh Speicher rund 17.500-20.000 € pro Anlage in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet 10 kWp Photovoltaik mit 10 kWh Speicher?",
    priceParagraphs: ["BauKostenRadar führt für 10 kWp PV plus etwa 10 kWh Speicher rund 17.500 bis 20.000 Euro pro Anlage. Der Richtwert beschreibt ein kombiniertes System und sollte nicht mit dem Preis einer PV-Anlage ohne Speicher verwechselt werden.", "Zusätzliche Arbeiten am Zählerschrank, besondere Dachbedingungen oder weitere Energiemanagement-Komponenten können den Projektpreis verändern."],
    factorsHeading: "Welche Komponenten beeinflussen das Gesamtbudget?",
    factorsIntro: "Bei einem Komplettsystem greifen PV-Generator, Wechselrichter, Speicher und Hausinstallation technisch ineinander.",
    factors: ["PV-Leistung und Modulqualität", "Nutzbare Speicherkapazität", "Batterietechnologie und Garantie", "Hybridwechselrichter oder separates Speichersystem", "Dachmontage und Gerüst", "Zählerschrank, Elektroarbeiten und Energiemanagement"],
    compareHeading: "Systempreis und Speicherpreis pro kWh ergänzend betrachten",
    compareParagraphs: ["Für einen vollständigen Vergleich sollten Sie den Komplettpreis und zusätzlich Größe sowie nutzbare Kapazität des Speichers betrachten. Ein größerer Speicher ist nicht automatisch wirtschaftlicher.", "BauKostenRadar führt außerdem einen separaten LFP-Speicherpreis pro kWh, der zur Einordnung der Speicherkomponente dient."],
    faqs: [
      { question: "Was kostet Photovoltaik mit Speicher 2026?", answer: "Für 10 kWp PV plus etwa 10 kWh Speicher führt BauKostenRadar rund 17.500 bis 20.000 Euro pro Anlage als Richtwert." },
      { question: "Wie groß ist der Speicher in diesem Richtwert?", answer: "Die Preisposition bezieht sich auf ungefähr 10 kWh Speicherkapazität bei einer 10-kWp-PV-Anlage." },
      { question: "Ist ein größerer Speicher immer besser?", answer: "Nein. Die passende Kapazität hängt vom Stromverbrauch, Lastprofil und gewünschten Eigenverbrauch ab." },
    ],
    serviceSlug: "photovoltaik", itemSlug: "10-kwp-pv-ca-10-kwh-speicher", itemLabel: "PV plus Speicher", serviceLabel: "Photovoltaik", parentSlug: "photovoltaik-kosten-2026", parentLabel: "Photovoltaik Kosten 2026",
    relatedExtra: [{ label: "PV 10 kWp ohne Speicher", href: "/ratgeber/photovoltaik-10-kwp-kosten" }, { label: "Stromspeicher Kosten pro kWh", href: "/ratgeber/stromspeicher-kosten-pro-kwh" }],
  },
  {
    slug: "fenster-3-fach-verglasung-kosten",
    title: "Fenster 3-fach Verglasung Kosten 2026",
    h1: "Fenster mit 3-fach Verglasung Kosten 2026: Preis pro Fenster",
    description: "Fenster mit 3-fach Verglasung Kosten 2026: BauKostenRadar-Richtwerte pro Standardfenster ohne Einbau, Beispiele und Montagekosten separat erklärt.",
    eyebrow: "3-fach Verglasung 2026",
    intro: "Bei Fenstern mit Dreifachverglasung sollten Fensterpreis und Montage getrennt gelesen werden. Rahmenmaterial, Größe, Öffnungsart und Sicherheitsausstattung beeinflussen den Produktpreis, während der Einbau eine eigene Arbeitsposition ist.",
    keyFact: "Fenster mit 3-fach Verglasung etwa 550-900 € pro Standardfenster ohne Einbau in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet ein Fenster mit 3-fach Verglasung?",
    priceParagraphs: ["BauKostenRadar führt für ein Standardfenster von ungefähr 1,3 x 1,3 m mit Dreifachverglasung etwa 550 bis 900 Euro pro Fenster ohne Einbau. Für zehn Fenster ergibt das etwa 5.500 bis 9.000 Euro als reine Fensterorientierung.", "Der professionelle Fenstereinbau wird separat mit einer eigenen BauKostenRadar-Preisposition geführt."],
    table: { headers: ["Anzahl Standardfenster", "Fenster ohne Einbau"], rows: [
      { cells: ["5 Fenster", "2.750-4.500 €"] },
      { cells: ["10 Fenster", "5.500-9.000 €"] },
      { cells: ["20 Fenster", "11.000-18.000 €"] },
    ] },
    factorsHeading: "Was verändert den Fensterpreis?",
    factorsIntro: "Dreifachverglasung ist nur ein Merkmal. Rahmen, Größe und Ausstattung können den Stückpreis ebenfalls stark verändern.",
    factors: ["Kunststoff, Holz oder Aluminium", "Fenstergröße und Sonderformen", "Öffnungsart und Beschläge", "Schall- und Sicherheitsanforderungen", "Rollläden oder Sonnenschutz", "Farbe, Dekor und Sonderausstattung"],
    compareHeading: "Fensterpreis und Fenstereinbau getrennt kalkulieren",
    compareParagraphs: ["Die BauKostenRadar-Position für Dreifachverglasung ist ausdrücklich ohne Einbau. Montage, Ausbau alter Fenster und Anschlussarbeiten müssen deshalb separat geprüft werden.", "Für den Einbau steht ein eigener Ratgeber mit Richtwert pro Fenster zur Verfügung."],
    faqs: [
      { question: "Was kostet ein Fenster mit 3-fach Verglasung 2026?", answer: "BauKostenRadar führt etwa 550 bis 900 Euro pro Standardfenster ohne Einbau als Richtwert." },
      { question: "Was kosten zehn Fenster mit 3-fach Verglasung?", answer: "Für zehn Standardfenster ergeben sich etwa 5.500 bis 9.000 Euro ohne Einbau." },
      { question: "Ist die Montage enthalten?", answer: "Nein. Der Fenstereinbau wird bei BauKostenRadar als separate Preisposition geführt." },
    ],
    serviceSlug: "fenster", itemSlug: "fenster-mit-3-fach-verglasung", itemLabel: "Fenster 3-fach", serviceLabel: "Fenster", parentSlug: "fenster-austauschen-kosten-haus", parentLabel: "Fenster austauschen Kosten",
    relatedExtra: [{ label: "Fenstereinbau Kosten", href: "/ratgeber/fenstereinbau-kosten" }],
  },
  {
    slug: "gasheizung-austauschen-kosten",
    title: "Gasheizung austauschen Kosten 2026",
    h1: "Gasheizung austauschen Kosten 2026: Richtwert für den Heizungstausch",
    description: "Gasheizung austauschen Kosten 2026: BauKostenRadar-Richtwert, Demontage, Hydraulik, Abgasweg, Regelung und Angebotsvergleich.",
    eyebrow: "Gasheizung 2026",
    intro: "Beim Austausch einer Gasheizung ist der Wärmeerzeuger nur ein Teil des Projekts. Demontage, hydraulische Einbindung, Regelung, Abgasweg und mögliche Anpassungen im Heizsystem entscheiden über den tatsächlichen Leistungsumfang.",
    keyFact: "Gasheizung austauschen etwa 6.000-12.000 € pauschal in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet es, eine Gasheizung auszutauschen?",
    priceParagraphs: ["BauKostenRadar führt für Gasheizung austauschen etwa 6.000 bis 12.000 Euro pauschal als Richtwert. Die Spanne dient der Budgetorientierung für diese konkrete Preisposition und ist kein allgemeiner Festpreis für jede Heizungsmodernisierung.", "Vor einer Investitionsentscheidung sollten neben dem reinen Austausch auch langfristige Energiekosten und alternative Heizsysteme separat verglichen werden."],
    factorsHeading: "Welche Arbeiten können im Angebot enthalten sein?",
    factorsIntro: "Ein Austausch am gleichen Standort ist anders zu kalkulieren als eine umfangreiche Anpassung der gesamten Heizungsanlage.",
    factors: ["Neuer Wärmeerzeuger und Regelung", "Demontage und Entsorgung des Altgeräts", "Anpassung von Rohrleitungen und Hydraulik", "Abgasweg und Schornsteinanschluss", "Warmwasserspeicher oder zusätzliche Komponenten", "Inbetriebnahme und hydraulische Optimierung"],
    compareHeading: "Reinen Kesseltausch und Systemwechsel unterscheiden",
    compareParagraphs: ["Ein Angebot für den Austausch einer vorhandenen Gasheizung ist nicht mit einem kompletten Wechsel auf ein anderes Heizsystem vergleichbar. Leistungsumfang und notwendige Nebenarbeiten unterscheiden sich deutlich.", "Für Luft-Wasser-Wärmepumpen führt BauKostenRadar einen separaten Komplett-Richtwert vor Förderung."],
    faqs: [
      { question: "Was kostet Gasheizung austauschen 2026?", answer: "BauKostenRadar führt etwa 6.000 bis 12.000 Euro pauschal als Richtwert für die Preisposition Gasheizung austauschen." },
      { question: "Ist der komplette Heizungsumbau enthalten?", answer: "Nicht automatisch. Größere Änderungen an Heizflächen, Verteilung oder Gebäudehülle können zusätzliche Kosten verursachen." },
      { question: "Sollte man Alternativen vergleichen?", answer: "Ja. Vor einer langfristigen Investition ist ein Vergleich von Investitions-, Betriebs- und möglichen Umbaukosten verschiedener Heizsysteme sinnvoll." },
    ],
    serviceSlug: "heizung", itemSlug: "gasheizung-austauschen", itemLabel: "Gasheizung austauschen", serviceLabel: "Heizung", parentSlug: "heizung-erneuern-kosten", parentLabel: "Heizung erneuern Kosten",
    relatedExtra: [{ label: "Luft-Wasser-Wärmepumpe Kosten", href: "/ratgeber/luft-wasser-waermepumpe-kosten" }],
  },
  {
    slug: "heizungswartung-kosten",
    title: "Heizungswartung Kosten 2026",
    h1: "Heizungswartung Kosten 2026: Richtwerte pro Wartung",
    description: "Heizungswartung Kosten 2026: BauKostenRadar-Richtwert pro Wartung, Leistungsumfang, Verschleißteile, Wartungsvertrag und Angebotscheck.",
    eyebrow: "Heizungswartung 2026",
    intro: "Eine regelmäßige Heizungswartung dient dazu, Funktion, Sicherheit und Effizienz der Anlage zu kontrollieren. Welche Prüfungen und Reinigungsarbeiten enthalten sind, hängt vom Heizsystem und vom Wartungsangebot ab.",
    keyFact: "Heizungswartung etwa 100-200 € pro Wartung in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet eine Heizungswartung?",
    priceParagraphs: ["BauKostenRadar führt für Heizungswartung etwa 100 bis 200 Euro pro Wartung als Richtwert. Ersatzteile, Reparaturen oder größere Reinigungsarbeiten können abhängig vom Zustand separat berechnet werden.", "Bei Wartungsverträgen sollte geprüft werden, welche Leistungen, Anfahrten und Reaktionszeiten tatsächlich enthalten sind."],
    factorsHeading: "Was beeinflusst die Wartungskosten?",
    factorsIntro: "Heizsystem, Anlagenzustand und Leistungsumfang bestimmen, wie lange die Wartung dauert und welche Teile benötigt werden.",
    factors: ["Art und Alter der Heizungsanlage", "Reinigung und Messumfang", "Verschleißteile und Filter", "Anfahrt und regionale Betriebskosten", "Einzelwartung oder Wartungsvertrag", "Zusätzliche Reparaturen außerhalb der Wartung"],
    compareHeading: "Wartung und Reparatur nicht gleichsetzen",
    compareParagraphs: ["Eine planmäßige Wartung ist keine pauschale Reparaturleistung. Werden Defekte festgestellt, sollten Ersatzteile und zusätzliche Arbeitszeit separat ausgewiesen werden.", "Für die Wartung einer Wärmepumpe führt BauKostenRadar eine eigene Preisposition mit eigenem Richtwert."],
    faqs: [
      { question: "Was kostet Heizungswartung 2026?", answer: "BauKostenRadar führt etwa 100 bis 200 Euro pro Wartung als Richtwert." },
      { question: "Sind Ersatzteile im Wartungspreis enthalten?", answer: "Nicht automatisch. Verschleißteile und Reparaturen können zusätzlich berechnet werden und sollten im Angebot klar beschrieben sein." },
      { question: "Ist Wärmepumpenwartung gleich teuer?", answer: "Nicht zwingend. BauKostenRadar führt für Wärmepumpenwartung eine separate Preisposition." },
    ],
    serviceSlug: "heizung", itemSlug: "heizungswartung", itemLabel: "Heizungswartung", serviceLabel: "Heizung", parentSlug: "heizung-erneuern-kosten", parentLabel: "Heizung erneuern Kosten",
    relatedExtra: [{ label: "Wärmepumpe Wartung Kosten", href: "/ratgeber/waermepumpe-wartung-kosten" }],
  },
  {
    slug: "doppelstabmattenzaun-kosten-pro-meter",
    title: "Doppelstabmattenzaun Kosten pro Meter 2026",
    h1: "Doppelstabmattenzaun Kosten 2026: Preis pro Meter inklusive Montage",
    description: "Doppelstabmattenzaun Kosten 2026 pro Meter: BauKostenRadar-Richtwerte inklusive Montage, Beispielbudgets, Höhe, Fundamente, Tore und Angebotsvergleich.",
    eyebrow: "Zaunbau 2026",
    intro: "Beim Doppelstabmattenzaun bestimmen Höhe, Drahtstärke, Pfostenfundamente und Gelände den Gesamtpreis. Tore, Sichtschutzstreifen oder schwieriger Boden sollten separat im Angebot erkennbar sein.",
    keyFact: "Doppelstabmattenzaun inklusive Montage etwa 60-120 €/lfd. Meter in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet ein Doppelstabmattenzaun pro Meter?",
    priceParagraphs: ["BauKostenRadar führt für Doppelstabmattenzaun inklusive Montage etwa 60 bis 120 Euro pro laufendem Meter. Für 30 Meter ergibt sich daraus eine erste Budgetorientierung von ungefähr 1.800 bis 3.600 Euro.", "Tore, schwierige Fundamente, Geländesprünge oder zusätzliche Sichtschutzelemente können das Gesamtbudget erhöhen."],
    table: { headers: ["Zaunlänge", "Budgetorientierung"], rows: [
      { cells: ["20 m", "1.200-2.400 €"] },
      { cells: ["30 m", "1.800-3.600 €"] },
      { cells: ["50 m", "3.000-6.000 €"] },
    ] },
    factorsHeading: "Welche Faktoren verändern den Meterpreis?",
    factorsIntro: "Ein gerader Zaun auf ebenem Boden ist einfacher zu montieren als eine Grundstücksgrenze mit Gefälle, Ecken und Toranlagen.",
    factors: ["Zaunhöhe und Drahtstärke", "Pfostenabstand und Fundamentierung", "Bodenbeschaffenheit", "Gefälle, Ecken und Höhenversätze", "Tore und Pforten", "Sichtschutzstreifen und weiteres Zubehör"],
    compareHeading: "Materialpreis und montierten Zaun nicht verwechseln",
    compareParagraphs: ["Die BauKostenRadar-Position ist inklusive Montage formuliert. Reine Online-Materialpreise für Matten und Pfosten sind deshalb nicht direkt vergleichbar.", "Für ein belastbares Angebot sollten Fundamentierung, Montage, Tore und Entsorgung vorhandener Zaunelemente eindeutig beschrieben sein."],
    faqs: [
      { question: "Was kostet Doppelstabmattenzaun pro Meter 2026?", answer: "BauKostenRadar führt inklusive Montage etwa 60 bis 120 Euro pro laufendem Meter als Richtwert." },
      { question: "Was kosten 30 Meter Doppelstabmattenzaun?", answer: "Mit dem BauKostenRadar-Richtwert ergeben sich etwa 1.800 bis 3.600 Euro als Budgetorientierung." },
      { question: "Sind Tore im Meterpreis enthalten?", answer: "Nicht automatisch. Tore und Pforten sollten als eigene Position im Angebot ausgewiesen werden." },
    ],
    serviceSlug: "garten", itemSlug: "doppelstabmattenzaun-inkl-montage", itemLabel: "Doppelstabmattenzaun", serviceLabel: "Garten & Außenanlagen", parentSlug: "garten-anlegen-kosten", parentLabel: "Garten anlegen Kosten",
  },
  {
    slug: "trockenestrich-kosten-pro-qm",
    title: "Trockenestrich Kosten pro m² 2026",
    h1: "Trockenestrich Kosten 2026: Richtwerte pro m²",
    description: "Trockenestrich Kosten 2026 pro m²: BauKostenRadar-Richtwerte, Beispielbudgets, Platten, Schüttung, Dämmung und Angebotsvergleich.",
    eyebrow: "Trockenestrich 2026",
    intro: "Trockenestrich kommt ohne lange Trocknungszeit eines Nassestrichs aus und ist besonders im Bestand interessant. Preisentscheidend sind Plattensystem, Untergrund, Ausgleichsschüttung und gewünschter Bodenaufbau.",
    keyFact: "Trockenestrich etwa 30-60 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Trockenestrich pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Trockenestrich etwa 30 bis 60 Euro pro Quadratmeter als Richtwert. Bei 50 m² ergibt sich daraus eine erste Orientierung von etwa 1.500 bis 3.000 Euro.", "Ob Ausgleichsschüttung, Dämmung oder zusätzliche Unterlagen enthalten sind, muss im konkreten Angebot geprüft werden."],
    table: { headers: ["Estrichfläche", "Budgetorientierung"], rows: [
      { cells: ["25 m²", "750-1.500 €"] },
      { cells: ["50 m²", "1.500-3.000 €"] },
      { cells: ["100 m²", "3.000-6.000 €"] },
    ] },
    factorsHeading: "Was beeinflusst Trockenestrich-Kosten?",
    factorsIntro: "Besonders im Altbau kann die notwendige Nivellierung des Untergrunds den Aufbau und Materialbedarf verändern.",
    factors: ["Gipsfaser- oder andere Plattensysteme", "Ausgleichsschüttung und Ebenheit", "Trittschall- und Wärmedämmung", "Aufbauhöhe und Türanschlüsse", "Feuchteschutz in geeigneten Bereichen", "Zuschnitte und kleine verwinkelte Flächen"],
    compareHeading: "Trockenestrich und Nassestrich getrennt bewerten",
    compareParagraphs: ["Trockenestrich punktet vor allem durch kurze Bauzeit und geringere Feuchtigkeit im Bauablauf. Nassestriche können dagegen je nach Aufbau und Fläche wirtschaftlicher sein.", "Vergleichen Sie daher nicht nur den Quadratmeterpreis, sondern auch Aufbauhöhe, Trocknungszeit und Folgearbeiten."],
    faqs: [
      { question: "Was kostet Trockenestrich pro m² 2026?", answer: "BauKostenRadar führt etwa 30 bis 60 Euro pro Quadratmeter als Richtwert." },
      { question: "Was kosten 50 m² Trockenestrich?", answer: "Mit dem Richtwert ergeben sich etwa 1.500 bis 3.000 Euro als erste Budgetorientierung." },
      { question: "Ist Ausgleichsschüttung enthalten?", answer: "Nicht automatisch. Der konkrete Aufbau sollte im Angebot mit allen Schichten beschrieben sein." },
    ],
    serviceSlug: "estrich", itemSlug: "trockenestrich", itemLabel: "Trockenestrich", serviceLabel: "Estrich", parentSlug: "estrich-100-qm-kosten", parentLabel: "Estrich 100 m² Kosten",
  },
  {
    slug: "zwischensparrendaemmung-kosten-pro-qm",
    title: "Zwischensparrendämmung Kosten pro m² 2026",
    h1: "Zwischensparrendämmung Kosten 2026: Richtwerte pro m² Dachfläche",
    description: "Zwischensparrendämmung Kosten 2026 pro m²: BauKostenRadar-Richtwerte, Beispielbudgets, Dämmstoff, Luftdichtheit und Angebotsvergleich.",
    eyebrow: "Dachdämmung 2026",
    intro: "Bei der Zwischensparrendämmung wird der vorhandene Raum zwischen den Sparren genutzt. Entscheidend sind Sparrenhöhe, Dämmstoff, Luftdichtheit und die Frage, ob Innenbekleidungen geöffnet oder neu hergestellt werden müssen.",
    keyFact: "Dachdämmung zwischen den Sparren etwa 60-120 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Zwischensparrendämmung pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Dachdämmung Zwischensparren etwa 60 bis 120 Euro pro Quadratmeter. Für 100 m² ergibt sich daraus eine erste Orientierung von ungefähr 6.000 bis 12.000 Euro.", "Innenbekleidung, zusätzliche Untersparrendämmung oder umfangreiche Luftdichtheitsarbeiten können abhängig vom Bestand weitere Kosten verursachen."],
    table: { headers: ["Dämmfläche", "Budgetorientierung"], rows: [
      { cells: ["50 m²", "3.000-6.000 €"] },
      { cells: ["100 m²", "6.000-12.000 €"] },
      { cells: ["150 m²", "9.000-18.000 €"] },
    ] },
    factorsHeading: "Welche Faktoren beeinflussen die Dachdämmung?",
    factorsIntro: "Bestandsdächer unterscheiden sich stark bei Sparren, Innenausbau und Luftdichtheit.",
    factors: ["Dämmstoff und erforderliche Dämmstärke", "Sparrenhöhe und Sparrenabstände", "Dampfbremse und luftdichte Anschlüsse", "Ausbau vorhandener Innenbekleidungen", "Gauben, Dachfenster und viele Anschlüsse", "Zusätzliche Untersparrendämmung oder Installationsebene"],
    compareHeading: "Zwischen- und Aufsparrendämmung nicht gleichsetzen",
    compareParagraphs: ["Die Zwischensparrendämmung greift überwiegend von innen in den Dachaufbau ein. Eine Aufsparrendämmung liegt oberhalb der Sparren und wird häufig mit Arbeiten an der Dacheindeckung kombiniert.", "Für Aufsparrendämmung führt BauKostenRadar einen separaten Richtwert und Ratgeber."],
    faqs: [
      { question: "Was kostet Zwischensparrendämmung pro m² 2026?", answer: "BauKostenRadar führt etwa 60 bis 120 Euro pro Quadratmeter als Richtwert." },
      { question: "Was kosten 100 m² Zwischensparrendämmung?", answer: "Mit dem Richtwert ergeben sich ungefähr 6.000 bis 12.000 Euro als Budgetorientierung." },
      { question: "Ist die Innenverkleidung enthalten?", answer: "Nicht automatisch. Rückbau und neue Innenbekleidung sollten im konkreten Angebot separat beschrieben werden." },
    ],
    serviceSlug: "daemmung", itemSlug: "dachdaemmung-zwischensparren", itemLabel: "Zwischensparrendämmung", serviceLabel: "Dämmung", parentSlug: "daemmung-kosten-pro-qm", parentLabel: "Dämmung Kosten pro m²",
    relatedExtra: [{ label: "Aufsparrendämmung Kosten", href: "/ratgeber/aufsparrendaemmung-kosten-pro-qm" }],
  },
  {
    slug: "aufsparrendaemmung-kosten-pro-qm",
    title: "Aufsparrendämmung Kosten pro m² 2026",
    h1: "Aufsparrendämmung Kosten 2026: Richtwerte pro m² Dachfläche",
    description: "Aufsparrendämmung Kosten 2026 pro m²: BauKostenRadar-Richtwerte, Beispielbudgets, Dachaufbau, Eindeckung und Angebotsvergleich.",
    eyebrow: "Dachdämmung außen 2026",
    intro: "Bei der Aufsparrendämmung liegt die Dämmschicht oberhalb der Sparren. Dadurch entsteht eine durchgehende Dämmebene, die Ausführung ist jedoch eng mit dem äußeren Dachaufbau und häufig mit einer Neueindeckung verbunden.",
    keyFact: "Dachdämmung Aufsparren etwa 100-180 €/m² Dachfläche in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Aufsparrendämmung pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Dachdämmung Aufsparren etwa 100 bis 180 Euro pro Quadratmeter Dachfläche. Bei 100 m² ergibt sich daraus eine Budgetorientierung von ungefähr 10.000 bis 18.000 Euro für diese Preisposition.", "Dacheindeckung, Gerüst und weitere Dacharbeiten können je nach Leistungsbeschreibung separat anfallen. Bei einer Dachsanierung sollte der Gesamtaufbau deshalb gemeinsam geplant werden."],
    table: { headers: ["Dachfläche", "Budgetorientierung Dämmung"], rows: [
      { cells: ["50 m²", "5.000-9.000 €"] },
      { cells: ["100 m²", "10.000-18.000 €"] },
      { cells: ["150 m²", "15.000-27.000 €"] },
    ] },
    factorsHeading: "Was beeinflusst Aufsparrendämmung-Kosten?",
    factorsIntro: "Die Maßnahme ist Teil des äußeren Dachaufbaus und hängt deshalb stark von Deckung, Anschlüssen und Baustellenlogistik ab.",
    factors: ["Dämmstoff und Dämmstärke", "Dachfläche, Neigung und Geometrie", "Gauben, Dachfenster und Anschlüsse", "Unterdeckbahn, Konterlattung und Systemaufbau", "Gerüst und Zugänglichkeit", "Kombination mit neuer Dacheindeckung"],
    compareHeading: "Dämmung und Neueindeckung getrennt ausweisen",
    compareParagraphs: ["Wenn Aufsparrendämmung im Zuge einer Dachsanierung ausgeführt wird, sollte das Angebot Dämmung, Deckung, Lattung und Gerüst möglichst transparent trennen. So wird sichtbar, welcher Kostenblock zu welcher Leistung gehört.", "Für Neueindeckung inklusive Lattung steht eine separate BauKostenRadar-Preisposition bereit."],
    faqs: [
      { question: "Was kostet Aufsparrendämmung pro m² 2026?", answer: "BauKostenRadar führt etwa 100 bis 180 Euro pro Quadratmeter Dachfläche als Richtwert." },
      { question: "Was kosten 100 m² Aufsparrendämmung?", answer: "Mit dem Richtwert ergeben sich etwa 10.000 bis 18.000 Euro für die Dämm-Preisposition." },
      { question: "Ist die neue Dacheindeckung enthalten?", answer: "Nicht automatisch. Die Dacheindeckung wird bei BauKostenRadar als separate Preisposition geführt." },
    ],
    serviceSlug: "daemmung", itemSlug: "dachdaemmung-aufsparren", itemLabel: "Aufsparrendämmung", serviceLabel: "Dämmung", parentSlug: "daemmung-kosten-pro-qm", parentLabel: "Dämmung Kosten pro m²",
    relatedExtra: [{ label: "Dach neu eindecken Kosten", href: "/ratgeber/dach-neu-eindecken-kosten-pro-qm" }, { label: "Zwischensparrendämmung Kosten", href: "/ratgeber/zwischensparrendaemmung-kosten-pro-qm" }],
  },
  {
    slug: "putzfassade-kosten-pro-qm",
    title: "Putzfassade Kosten pro m² 2026",
    h1: "Putzfassade Kosten 2026: neue Fassade pro m² inklusive Material",
    description: "Putzfassade Kosten 2026 pro m²: BauKostenRadar-Richtwerte inklusive Material, Beispielbudgets, Untergrund, Gerüst und Angebotsvergleich.",
    eyebrow: "Fassadenputz 2026",
    intro: "Eine neue Putzfassade besteht aus mehr als der sichtbaren Deckschicht. Untergrund, Putzsystem, Anschlüsse und Gerüst bestimmen, ob eine Fläche einfach neu verputzt werden kann oder zusätzliche Sanierungsarbeiten nötig sind.",
    keyFact: "Neue Putzfassade etwa 45-120 €/m² inklusive Material in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet eine neue Putzfassade pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Putz-Fassade neu etwa 45 bis 120 Euro pro Quadratmeter inklusive Material. Für 100 m² ergibt sich daraus eine erste Orientierung von rund 4.500 bis 12.000 Euro für diese Preisposition.", "Gerüst, umfangreiche Risssanierung, Dämmung oder Rückbau alter Fassadenschichten können abhängig vom Projekt zusätzlich anfallen."],
    table: { headers: ["Fassadenfläche", "Budgetorientierung"], rows: [
      { cells: ["50 m²", "2.250-6.000 €"] },
      { cells: ["100 m²", "4.500-12.000 €"] },
      { cells: ["200 m²", "9.000-24.000 €"] },
    ] },
    factorsHeading: "Welche Faktoren verändern Fassadenputz-Kosten?",
    factorsIntro: "Der Zustand des Untergrunds entscheidet, wie viele Vorarbeiten vor dem neuen Putzsystem notwendig sind.",
    factors: ["Altputz prüfen, ausbessern oder entfernen", "Untergrund und erforderliche Grundierung", "Putzsystem und Körnung", "Sockel, Fensterlaibungen und Anschlüsse", "Gerüst und Gebäudehöhe", "Zusätzliche Fassadendämmung"],
    compareHeading: "Putzfassade, Anstrich und Dämmung getrennt kalkulieren",
    compareParagraphs: ["Ein neuer Fassadenputz ist eine andere Leistung als ein reiner Fassadenanstrich. Auch eine gedämmte Fassade hat einen deutlich größeren Systemaufbau.", "Prüfen Sie deshalb, ob Angebotspreise Putz, Anstrich, Gerüst und mögliche Dämmung getrennt oder als eindeutig beschriebenes Paket enthalten."],
    faqs: [
      { question: "Was kostet eine Putzfassade pro m² 2026?", answer: "BauKostenRadar führt für Putz-Fassade neu etwa 45 bis 120 Euro pro Quadratmeter inklusive Material als Richtwert." },
      { question: "Was kosten 100 m² Putzfassade?", answer: "Mit dem Richtwert ergeben sich etwa 4.500 bis 12.000 Euro als erste Budgetorientierung." },
      { question: "Ist eine Fassadendämmung enthalten?", answer: "Nicht automatisch. Fassadendämmung wird bei BauKostenRadar als separate Preisposition geführt." },
    ],
    serviceSlug: "fassade", itemSlug: "putz-fassade-neu", itemLabel: "Putz-Fassade neu", serviceLabel: "Fassade", parentSlug: "fassade-sanieren-kosten", parentLabel: "Fassade sanieren Kosten",
    relatedExtra: [{ label: "Fassadendämmung Kosten", href: "/ratgeber/fassadendaemmung-kosten-pro-qm" }],
  },
];

export const tertiaryOpportunityGuides: Guide[] = configs.map(createOpportunityGuide);
