import type { Guide, GuideTable } from "@/lib/guides";

type OpportunityGuideConfig = {
  slug: string;
  title: string;
  h1: string;
  description: string;
  eyebrow: string;
  intro: string;
  keyFact: string;
  priceHeading: string;
  priceParagraphs: string[];
  table?: GuideTable;
  factorsHeading: string;
  factorsIntro: string;
  factors: string[];
  compareHeading: string;
  compareParagraphs: string[];
  faqs: Array<{ question: string; answer: string }>;
  serviceSlug: string;
  itemSlug: string;
  itemLabel: string;
  serviceLabel: string;
  parentSlug: string;
  parentLabel: string;
  relatedExtra?: Array<{ label: string; href: string }>;
};

function createOpportunityGuide(config: OpportunityGuideConfig): Guide {
  return {
    slug: config.slug,
    title: config.title,
    h1: config.h1,
    description: config.description,
    eyebrow: config.eyebrow,
    intro: config.intro,
    keyFact: config.keyFact,
    sections: [
      {
        heading: config.priceHeading,
        paragraphs: config.priceParagraphs,
        ...(config.table ? { table: config.table } : {}),
      },
      {
        heading: config.factorsHeading,
        paragraphs: [config.factorsIntro],
        bullets: config.factors,
      },
      {
        heading: config.compareHeading,
        paragraphs: config.compareParagraphs,
      },
    ],
    faqs: config.faqs,
    related: [
      { label: `${config.itemLabel} Preisdetail`, href: `/kosten/${config.serviceSlug}/leistung/${config.itemSlug}` },
      { label: config.parentLabel, href: `/ratgeber/${config.parentSlug}` },
      { label: `${config.serviceLabel} Kosten`, href: `/kosten/${config.serviceSlug}` },
      ...(config.relatedExtra ?? []),
      { label: "Handwerkerkosten-Rechner", href: `/rechner/handwerkerkosten?gewerk=${config.serviceSlug}&leistung=${config.itemSlug}` },
    ],
  };
}

const configs: OpportunityGuideConfig[] = [
  {
    slug: "mosaik-fliesen-verlegen-kosten-pro-qm",
    title: "Mosaikfliesen verlegen Kosten pro m² 2026",
    h1: "Mosaikfliesen verlegen Kosten 2026: Arbeitskosten pro m²",
    description: "Mosaikfliesen verlegen Kosten 2026 pro m²: BauKostenRadar-Richtwerte für die Arbeit, Zuschnitte, Untergrund, Abdichtung und Angebotsvergleich.",
    eyebrow: "Mosaikfliesen 2026",
    intro: "Mosaik ist kleinteilig und verlangt einen gleichmäßigen Untergrund, saubere Raster und viele Detailanschlüsse. Deshalb liegt die reine Verlegearbeit typischerweise über einfachen Standardformaten.",
    keyFact: "Mosaik-Fliesen verlegen etwa 90-180 €/m² Arbeitsleistung in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Mosaikfliesen verlegen pro m²?",
    priceParagraphs: [
      "BauKostenRadar führt für Mosaik-Fliesen verlegen etwa 90 bis 180 Euro pro Quadratmeter Arbeitsleistung. Für 20 m² ergibt sich damit eine erste Budgetorientierung von ungefähr 1.800 bis 3.600 Euro.",
      "Fliesenmaterial, alte Beläge, Untergrundausgleich und eine notwendige Verbundabdichtung sind je nach Angebot zusätzliche Kostenblöcke.",
    ],
    table: { headers: ["Mosaikfläche", "Budgetorientierung Arbeit"], rows: [
      { cells: ["10 m²", "900-1.800 €"] },
      { cells: ["20 m²", "1.800-3.600 €"] },
      { cells: ["40 m²", "3.600-7.200 €"] },
    ] },
    factorsHeading: "Was treibt die Mosaik-Verlegekosten?",
    factorsIntro: "Je kleinteiliger das Raster und je mehr Anschlüsse vorhanden sind, desto größer ist der Zeitbedarf.",
    factors: ["Mosaikformat und Trägermatten", "Untergrundebenheit und Spachtelarbeiten", "Viele Ecken, Nischen und Ablagen", "Bodenabläufe und Gefälleflächen", "Verfugung und Fugenfarbe", "Abdichtung in Nassbereichen"],
    compareHeading: "Mosaik nicht mit Standardfliesen gleichsetzen",
    compareParagraphs: ["Vergleichen Sie Angebote nur bei gleichem Fliesenformat und ähnlichem Untergrund. Ein Standardpreis pro Quadratmeter ist für kleinteiliges Mosaik oft nicht übertragbar.", "Material und Arbeitsleistung sollten getrennt erkennbar sein, damit hochwertige Mosaike nicht den Vergleich der Handwerkerleistung verzerren."],
    faqs: [
      { question: "Was kostet Mosaikfliesen verlegen pro m² 2026?", answer: "BauKostenRadar führt etwa 90 bis 180 Euro pro Quadratmeter Arbeitsleistung als Richtwert." },
      { question: "Was kosten 20 m² Mosaikfliesen verlegen?", answer: "Für die Arbeitsleistung ergeben sich ungefähr 1.800 bis 3.600 Euro als Budgetorientierung." },
      { question: "Sind Mosaikfliesen im Preis enthalten?", answer: "Die verwendete Preisposition beschreibt die Arbeit. Material und zusätzliche Untergrund- oder Abdichtungsarbeiten sind separat zu prüfen." },
    ],
    serviceSlug: "fliesenleger", itemSlug: "mosaik-fliesen-verlegen", itemLabel: "Mosaik-Fliesen verlegen", serviceLabel: "Fliesenleger", parentSlug: "fliesenleger-kosten-pro-qm", parentLabel: "Fliesenleger Kosten pro m²",
    relatedExtra: [{ label: "Standard-Fliesen verlegen Kosten", href: "/ratgeber/fliesen-verlegen-kosten-pro-qm" }],
  },
  {
    slug: "naturstein-verlegen-kosten-pro-qm",
    title: "Naturstein verlegen Kosten pro m² 2026",
    h1: "Naturstein verlegen Kosten 2026: Arbeitskosten pro m²",
    description: "Naturstein verlegen Kosten 2026 pro m²: BauKostenRadar-Richtwerte für die Arbeit, Materialeigenschaften, Untergrund, Zuschnitte und Angebotsvergleich.",
    eyebrow: "Naturstein 2026",
    intro: "Naturstein verlangt je nach Sorte besondere Kleber, passende Fugenmaterialien und sorgfältige Auswahl der Platten. Gewicht, Kalibrierung und Zuschnitt können den Arbeitsaufwand deutlich erhöhen.",
    keyFact: "Naturstein verlegen etwa 100-220 €/m² Arbeitsleistung in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Naturstein verlegen pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Naturstein verlegen etwa 100 bis 220 Euro pro Quadratmeter Arbeitsleistung. Für 20 m² ergibt sich daraus eine Orientierung von ungefähr 2.000 bis 4.400 Euro.", "Der Naturstein selbst ist in dieser Arbeitsposition nicht automatisch enthalten. Materialqualität und Plattendicke können das Gesamtbudget stark verändern."],
    table: { headers: ["Natursteinfläche", "Budgetorientierung Arbeit"], rows: [
      { cells: ["10 m²", "1.000-2.200 €"] },
      { cells: ["20 m²", "2.000-4.400 €"] },
      { cells: ["40 m²", "4.000-8.800 €"] },
    ] },
    factorsHeading: "Welche Faktoren beeinflussen die Naturstein-Verlegung?",
    factorsIntro: "Naturstein ist kein einheitliches Produkt. Härte, Maßhaltigkeit und Empfindlichkeit bestimmen die Verarbeitung.",
    factors: ["Steinart und Plattenformat", "Kalibrierte oder unterschiedlich starke Platten", "Gewicht und Transportwege", "Spezialkleber und Verfugung", "Untergrundausgleich", "Zuschnitte, Sockel und Treppenanschlüsse"],
    compareHeading: "Steinmaterial und Verlegearbeit getrennt vergleichen",
    compareParagraphs: ["Ein günstiger Verlegepreis kann durch teures Material oder zusätzliche Vorarbeiten relativiert werden. Lassen Sie deshalb Stein, Kleber, Fuge und Arbeitsleistung separat oder eindeutig als Paket ausweisen.", "Bei großen Formaten sollte zusätzlich geprüft werden, ob der Aufwand eher einem Großformat-Angebot entspricht."],
    faqs: [
      { question: "Was kostet Naturstein verlegen pro m² 2026?", answer: "BauKostenRadar führt etwa 100 bis 220 Euro pro Quadratmeter Arbeitsleistung als Richtwert." },
      { question: "Was kosten 20 m² Naturstein verlegen?", answer: "Für die Arbeitsleistung ergeben sich ungefähr 2.000 bis 4.400 Euro als erste Orientierung." },
      { question: "Ist der Naturstein im Richtwert enthalten?", answer: "Nein, die verwendete Preisposition beschreibt die Verlegearbeit. Das Steinmaterial muss im konkreten Angebot separat geprüft werden." },
    ],
    serviceSlug: "fliesenleger", itemSlug: "naturstein-verlegen", itemLabel: "Naturstein verlegen", serviceLabel: "Fliesenleger", parentSlug: "fliesenleger-kosten-pro-qm", parentLabel: "Fliesenleger Kosten pro m²",
    relatedExtra: [{ label: "Großformat-Fliesen Kosten", href: "/ratgeber/grossformat-fliesen-verlegen-kosten" }],
  },
  {
    slug: "lichtschalter-austauschen-kosten",
    title: "Lichtschalter austauschen Kosten 2026",
    h1: "Lichtschalter austauschen Kosten 2026: Richtwert pro Stück",
    description: "Lichtschalter austauschen Kosten 2026: BauKostenRadar-Richtwert pro Stück, Material, Einsatz, Fehlersuche, Anfahrt und Angebotsvergleich.",
    eyebrow: "Elektro-Kleinauftrag 2026",
    intro: "Beim Austausch eines Lichtschalters ist der einzelne Einsatz schnell gewechselt, doch Anfahrt, Prüfung und kleine Auftragsmengen beeinflussen den tatsächlichen Rechnungsbetrag. Bei mehreren Schaltern verteilen sich Fixkosten besser.",
    keyFact: "Lichtschalter austauschen etwa 50-100 € pro Stück in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet ein neuer Lichtschalter inklusive Austausch?",
    priceParagraphs: ["BauKostenRadar führt für Lichtschalter austauschen etwa 50 bis 100 Euro pro Stück als Richtwert. Zehn Schalter entsprechen rechnerisch ungefähr 500 bis 1.000 Euro.", "Bei einem einzelnen Schalter können Mindestauftragswert oder Anfahrt stärker ins Gewicht fallen. Hochwertige Schalterprogramme und Smart-Home-Komponenten können zusätzlich kosten."],
    table: { headers: ["Anzahl", "Budgetorientierung"], rows: [
      { cells: ["5 Schalter", "250-500 €"] },
      { cells: ["10 Schalter", "500-1.000 €"] },
      { cells: ["20 Schalter", "1.000-2.000 €"] },
    ] },
    factorsHeading: "Was beeinflusst den Preis pro Schalter?",
    factorsIntro: "Entscheidend ist, ob nur ein vorhandener Einsatz ersetzt wird oder Leitungen und Dose geprüft beziehungsweise angepasst werden müssen.",
    factors: ["Standard- oder Design-Schalterprogramm", "Vorhandene Unterputzdose", "Fehlersuche und Messungen", "Mehrfachrahmen und Kombinationen", "Smart-Home- oder Dimmer-Funktion", "Anfahrt und Mindestauftragswert"],
    compareHeading: "Austausch und Neuinstallation unterscheiden",
    compareParagraphs: ["Der Austausch an einer vorhandenen Stelle ist nicht mit einer neuen Leitung inklusive Schlitzen und Dose gleichzusetzen. Angebote sollten den konkreten Leistungsumfang nennen.", "Wer mehrere Steckdosen und Schalter erneuert, sollte ein gebündeltes Angebot vergleichen, weil sich Anfahrt und Rüstzeit verteilen können."],
    faqs: [
      { question: "Was kostet Lichtschalter austauschen 2026?", answer: "BauKostenRadar führt etwa 50 bis 100 Euro pro Stück als Richtwert." },
      { question: "Was kosten zehn neue Lichtschalter?", answer: "Rechnerisch ergeben sich ungefähr 500 bis 1.000 Euro als Budgetorientierung für die Preisposition." },
      { question: "Ist eine neue Leitung enthalten?", answer: "Nicht automatisch. Die Preisposition beschreibt den Austausch des Schalters, nicht eine komplette Neuverkabelung." },
    ],
    serviceSlug: "elektriker", itemSlug: "lichtschalter-austauschen", itemLabel: "Lichtschalter austauschen", serviceLabel: "Elektrik", parentSlug: "elektrik-erneuern-altbau", parentLabel: "Elektrik im Altbau erneuern",
    relatedExtra: [{ label: "Steckdose installieren Kosten", href: "/ratgeber/steckdose-installieren-kosten" }],
  },
  {
    slug: "geruest-kosten-pro-qm",
    title: "Gerüst Kosten pro m² 2026",
    h1: "Gerüst Kosten 2026: Richtwert pro m² für etwa vier Wochen",
    description: "Gerüst Kosten 2026 pro m²: BauKostenRadar-Richtwert für etwa vier Wochen, Gerüstfläche, Standzeit, Auf- und Abbau sowie Angebotsvergleich.",
    eyebrow: "Fassadengerüst 2026",
    intro: "Gerüstkosten werden häufig nach eingerüsteter Fläche kalkuliert. Gebäudehöhe, Standzeit, Schutzmaßnahmen und Zugänglichkeit entscheiden, ob ein Standardgerüst ausreicht oder zusätzliche Bauteile benötigt werden.",
    keyFact: "Gerüst für etwa vier Wochen etwa 8-15 €/m² Gerüstfläche in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet ein Gerüst pro m²?",
    priceParagraphs: ["BauKostenRadar führt für ein Gerüst mit etwa vier Wochen Standzeit rund 8 bis 15 Euro pro Quadratmeter Gerüstfläche. Für 150 m² Gerüstfläche ergibt sich daraus eine Orientierung von etwa 1.200 bis 2.250 Euro.", "Gerüstfläche ist nicht identisch mit Wohnfläche oder Dachfläche. Verlängerte Standzeiten und besondere Schutz- oder Fanggerüste können zusätzlich berechnet werden."],
    table: { headers: ["Gerüstfläche", "Budgetorientierung"], rows: [
      { cells: ["100 m²", "800-1.500 €"] },
      { cells: ["150 m²", "1.200-2.250 €"] },
      { cells: ["200 m²", "1.600-3.000 €"] },
    ] },
    factorsHeading: "Welche Faktoren verändern Gerüstkosten?",
    factorsIntro: "Ein gerader, gut erreichbarer Baukörper ist einfacher einzurüsten als ein Gebäude mit Anbauten, Gauben und schwierigem Gelände.",
    factors: ["Gerüstfläche und Gebäudehöhe", "Auf- und Abbau", "Standzeit über die Grunddauer hinaus", "Dachfang- oder Schutzgerüst", "Netze und Wetterschutz", "Schwierige Zufahrt oder Aufstellflächen"],
    compareHeading: "Gerüst als eigenen Kostenblock ausweisen",
    compareParagraphs: ["Bei Dach- und Fassadenangeboten sollte erkennbar sein, ob das Gerüst bereits enthalten ist. Sonst lassen sich scheinbar günstige Gesamtpreise schlecht vergleichen.", "Wenn mehrere Gewerke dasselbe Gerüst nutzen können, kann eine abgestimmte Bauablaufplanung Doppelaufwand vermeiden."],
    faqs: [
      { question: "Was kostet ein Gerüst pro m² 2026?", answer: "BauKostenRadar führt für etwa vier Wochen rund 8 bis 15 Euro pro Quadratmeter Gerüstfläche als Richtwert." },
      { question: "Was kosten 150 m² Gerüst?", answer: "Mit der BauKostenRadar-Spanne ergeben sich ungefähr 1.200 bis 2.250 Euro als Orientierung." },
      { question: "Ist die Standzeit unbegrenzt?", answer: "Nein. Die Preisposition bezieht sich auf ungefähr vier Wochen. Eine längere Standzeit kann Mehrkosten verursachen." },
    ],
    serviceSlug: "dachsanierung", itemSlug: "geruest-ca-4-wochen", itemLabel: "Gerüst ca. 4 Wochen", serviceLabel: "Dachsanierung", parentSlug: "dach-sanieren-kosten-pro-qm", parentLabel: "Dach sanieren Kosten pro m²",
    relatedExtra: [{ label: "Dach neu eindecken Kosten", href: "/ratgeber/dach-neu-eindecken-kosten-pro-qm" }],
  },
  {
    slug: "boden-sanieren-kosten-pro-qm",
    title: "Boden sanieren Kosten pro m² 2026",
    h1: "Bodensanierung Kosten 2026: alten Boden raus, neuen Boden rein",
    description: "Boden sanieren Kosten 2026 pro m²: BauKostenRadar-Richtwerte für Rückbau und neuen Boden, Untergrund, Entsorgung und Angebotsvergleich.",
    eyebrow: "Bodensanierung 2026",
    intro: "Eine Bodensanierung umfasst mehr als das Verlegen eines neuen Belags. Rückbau, Entsorgung, Untergrundvorbereitung und der neue Aufbau entscheiden darüber, wie breit die Kostenspanne ausfällt.",
    keyFact: "Boden-Sanierung alt raus, neu rein etwa 65-180 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet eine komplette Bodensanierung pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Boden-Sanierung mit altem Belag raus und neuem Belag rein etwa 65 bis 180 Euro pro Quadratmeter. Für 100 m² ergibt sich eine erste Budgetorientierung von ungefähr 6.500 bis 18.000 Euro.", "Welche Art neuer Boden in der Spanne steckt, muss im konkreten Angebot geprüft werden. Hochwertiges Parkett kann deutlich anders kalkuliert werden als einfacher Laminat- oder Vinylboden."],
    table: { headers: ["Bodenfläche", "Budgetorientierung"], rows: [
      { cells: ["50 m²", "3.250-9.000 €"] },
      { cells: ["100 m²", "6.500-18.000 €"] },
      { cells: ["150 m²", "9.750-27.000 €"] },
    ] },
    factorsHeading: "Was beeinflusst die Kosten der Bodensanierung?",
    factorsIntro: "Der Bestand unter dem sichtbaren Boden ist oft der größte Unsicherheitsfaktor.",
    factors: ["Art und Verklebung des Altbelags", "Entsorgung und Container", "Estrichzustand und Ausgleich", "Neuer Bodenbelag und Materialklasse", "Sockelleisten und Türanschlüsse", "Möbel, Zugänglichkeit und Etappierung"],
    compareHeading: "Rückbau, Untergrund und neuen Belag separat prüfen",
    compareParagraphs: ["Ein Komplettpreis ist nur dann vergleichbar, wenn der neue Belag und die Untergrundarbeiten ausreichend beschrieben sind. Sonst können Nachträge entstehen.", "Für Vinyl, Laminat und Parkett führt BauKostenRadar zusätzlich eigene Preispositionen und Ratgeber."],
    faqs: [
      { question: "Was kostet Bodensanierung pro m² 2026?", answer: "BauKostenRadar führt etwa 65 bis 180 Euro pro Quadratmeter für die Position alt raus, neu rein als Richtwert." },
      { question: "Was kosten 100 m² Bodensanierung?", answer: "Mit der Richtwertspanne ergeben sich ungefähr 6.500 bis 18.000 Euro als Budgetorientierung." },
      { question: "Ist der neue Boden enthalten?", answer: "Die Preisposition ist als alt raus, neu rein formuliert. Der konkrete Belag und seine Materialqualität müssen im Angebot eindeutig beschrieben sein." },
    ],
    serviceSlug: "bodenleger", itemSlug: "boden-sanierung-alt-raus-neu-rein", itemLabel: "Boden-Sanierung alt raus, neu rein", serviceLabel: "Bodenleger", parentSlug: "bodenleger-kosten-pro-qm", parentLabel: "Bodenleger Kosten pro m²",
    relatedExtra: [{ label: "Vinylboden verlegen Kosten", href: "/ratgeber/vinylboden-verlegen-kosten-pro-qm" }, { label: "Parkett verlegen Kosten", href: "/ratgeber/parkett-verlegen-kosten-pro-qm" }],
  },
  {
    slug: "bad-entkernen-kosten",
    title: "Bad entkernen Kosten 2026",
    h1: "Bad entkernen Kosten 2026: Demontage und Entsorgung",
    description: "Bad entkernen Kosten 2026: BauKostenRadar-Richtwert für Demontage und Entsorgung eines Altbads, Leistungsumfang, Container und Angebotsvergleich.",
    eyebrow: "Bad-Rückbau 2026",
    intro: "Vor einer Badsanierung müssen häufig Sanitärobjekte, alte Möbel und weitere Bestandteile demontiert und entsorgt werden. Der Rückbau sollte als eigener Kostenblock sichtbar sein, damit Sanierungsangebote vergleichbar bleiben.",
    keyFact: "Demontage und Entsorgung Altbad etwa 1.100-1.800 € pro Bad in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet ein Bad zu entkernen?",
    priceParagraphs: ["BauKostenRadar führt für Demontage und Entsorgung eines Altbads etwa 1.100 bis 1.800 Euro pro Bad als Richtwert. Die Position bildet einen typischen Rückbau-Kostenblock ab, nicht die anschließende Neuinstallation.", "Fliesenabbruch, Estricharbeiten, Schadstofffunde oder besonders schwere Einbauten können je nach Leistungsbeschreibung zusätzliche Arbeiten auslösen."],
    factorsHeading: "Was beeinflusst die Rückbaukosten im Bad?",
    factorsIntro: "Menge, Gewicht und Zugänglichkeit des auszubauenden Materials bestimmen den Arbeits- und Entsorgungsaufwand.",
    factors: ["Anzahl der Sanitärobjekte", "Badmöbel und Duschabtrennungen", "Fliesen- und Wandbeläge im Rückbauumfang", "Stockwerk und Transportweg", "Container und Entsorgungsgebühren", "Besondere Altmaterialien oder Schadstoffe"],
    compareHeading: "Rückbau und neue Badsanierung getrennt lesen",
    compareParagraphs: ["Ein Angebot sollte zeigen, ob Demontage, Abtransport und Entsorgung vollständig enthalten sind. Danach folgen Installation, Abdichtung, Fliesen und neue Sanitärobjekte als eigene Kostenblöcke.", "Für das Gesamtprojekt bietet BauKostenRadar einen separaten Ratgeber zur kompletten Badsanierung."],
    faqs: [
      { question: "Was kostet Bad entkernen 2026?", answer: "BauKostenRadar führt etwa 1.100 bis 1.800 Euro pro Bad für Demontage und Entsorgung des Altbads als Richtwert." },
      { question: "Ist die neue Badeinrichtung enthalten?", answer: "Nein. Die Preisposition betrifft Rückbau und Entsorgung. Neue Sanitärobjekte und Installation sind separate Kostenblöcke." },
      { question: "Sind alte Fliesen automatisch enthalten?", answer: "Nicht zwingend. Der konkrete Rückbauumfang sollte im Angebot ausdrücklich beschrieben sein." },
    ],
    serviceSlug: "sanitaer", itemSlug: "demontage-entsorgung-altbad", itemLabel: "Demontage & Entsorgung Altbad", serviceLabel: "Sanitär", parentSlug: "bad-komplett-sanieren-kosten", parentLabel: "Bad komplett sanieren Kosten",
    relatedExtra: [{ label: "Sanitär Kosten", href: "/ratgeber/sanitaer-kosten" }],
  },
  {
    slug: "photovoltaik-15-kwp-kosten",
    title: "Photovoltaik 15 kWp Kosten 2026",
    h1: "Photovoltaik 15 kWp Kosten 2026: Anlage inklusive Installation",
    description: "Photovoltaik 15 kWp Kosten 2026: BauKostenRadar-Richtwerte inklusive Installation, Dach, Wechselrichter, Speicheroption und Angebotsvergleich.",
    eyebrow: "PV 15 kWp 2026",
    intro: "Eine 15-kWp-Anlage richtet sich häufig an größere Einfamilienhäuser oder Gebäude mit höherem Strombedarf. Dachfläche, Modulbelegung, Gerüst und Elektroarbeiten bestimmen, wie nah das Projekt am unteren oder oberen Richtwert liegt.",
    keyFact: "PV-Anlage 15 kWp inklusive Installation etwa 15.000-21.000 € in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet eine 15-kWp-Photovoltaikanlage?",
    priceParagraphs: ["BauKostenRadar führt für eine PV-Anlage mit 15 kWp inklusive Installation etwa 15.000 bis 21.000 Euro pro Anlage als Richtwert. Ein Stromspeicher ist in dieser Preisposition nicht ausdrücklich enthalten.", "Für den Angebotsvergleich sollten Modulleistung, Wechselrichter, Montagesystem, Gerüst, Elektroarbeiten, Anmeldung und gegebenenfalls Speicher klar beschrieben sein."],
    factorsHeading: "Was verändert die Kosten einer 15-kWp-PV-Anlage?",
    factorsIntro: "Bei größeren Anlagen sinkt der Preis je kWp nicht automatisch in jedem Projekt, weil Dachgeometrie und elektrische Einbindung unterschiedlich aufwendig sein können.",
    factors: ["Modul- und Wechselrichterklasse", "Dachform, Neigung und Belegung", "Gerüst und Absturzsicherung", "Zählerschrank und Elektroanpassungen", "Leitungswege und Überspannungsschutz", "Optionaler Stromspeicher"],
    compareHeading: "15 kWp nur mit gleichem Leistungsumfang vergleichen",
    compareParagraphs: ["Vergleichen Sie Angebote anhand installierter kWp, Komponenten und enthaltenen Nebenleistungen. Ein niedriger Gesamtpreis kann auf andere Module oder nicht enthaltene Elektroarbeiten zurückgehen.", "BauKostenRadar führt zusätzlich eigene Richtwerte für 10 kWp und ein 10-kWp-System mit Speicher."],
    faqs: [
      { question: "Was kostet Photovoltaik mit 15 kWp 2026?", answer: "BauKostenRadar führt etwa 15.000 bis 21.000 Euro inklusive Installation als Richtwert." },
      { question: "Ist ein Stromspeicher bei 15 kWp enthalten?", answer: "Nicht automatisch. Die 15-kWp-Preisposition nennt eine PV-Anlage inklusive Installation, ein Speicher sollte separat geprüft werden." },
      { question: "Sollte man nach Euro pro kWp vergleichen?", answer: "Der Wert pro kWp ist hilfreich, ersetzt aber nicht den Vergleich von Komponenten, Dachaufwand und enthaltenen Elektroarbeiten." },
    ],
    serviceSlug: "photovoltaik", itemSlug: "pv-anlage-15-kwp-inkl-installation", itemLabel: "PV-Anlage 15 kWp inkl. Installation", serviceLabel: "Photovoltaik", parentSlug: "photovoltaik-kosten-2026", parentLabel: "Photovoltaik Kosten 2026",
    relatedExtra: [{ label: "Photovoltaik 10 kWp Kosten", href: "/ratgeber/photovoltaik-10-kwp-kosten" }, { label: "Photovoltaik mit Speicher Kosten", href: "/ratgeber/photovoltaik-mit-speicher-kosten" }],
  },
  {
    slug: "fenster-2-fach-verglasung-kosten",
    title: "Fenster 2-fach Verglasung Kosten 2026",
    h1: "Fenster mit 2-fach Verglasung Kosten 2026: Preis pro Fenster",
    description: "Fenster mit 2-fach Verglasung Kosten 2026: BauKostenRadar-Richtwert pro Standardfenster ohne Einbau, Material, Größe, Montage und Angebotsvergleich.",
    eyebrow: "2-fach Fenster 2026",
    intro: "Bei neuen Fenstern beeinflussen Rahmenmaterial, Größe, Beschläge und Verglasung den Stückpreis. Für einen fairen Vergleich muss außerdem klar sein, ob Montage, Ausbau und Entsorgung enthalten sind.",
    keyFact: "Fenster mit 2-fach Verglasung etwa 400-700 € pro Standardfenster ohne Einbau in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet ein Fenster mit 2-fach Verglasung?",
    priceParagraphs: ["BauKostenRadar führt für ein Standardfenster mit 2-fach Verglasung etwa 400 bis 700 Euro pro Fenster ohne Einbau. Bei zehn Fenstern ergibt sich damit eine reine Fenster-Budgetorientierung von ungefähr 4.000 bis 7.000 Euro.", "Die Datenbasis bezieht sich auf eine Standardgröße von ungefähr 1,3 × 1,3 Metern. Größere Elemente, Sonderformen und besondere Rahmenmaterialien können deutlich abweichen."],
    table: { headers: ["Anzahl", "Fenster ohne Einbau"], rows: [
      { cells: ["5 Fenster", "2.000-3.500 €"] },
      { cells: ["10 Fenster", "4.000-7.000 €"] },
      { cells: ["20 Fenster", "8.000-14.000 €"] },
    ] },
    factorsHeading: "Welche Faktoren verändern den Fensterpreis?",
    factorsIntro: "Verglasung ist nur ein Teil des Gesamtfensters. Rahmen und Öffnungsart sind ebenfalls preisbestimmend.",
    factors: ["Kunststoff, Holz oder Aluminium", "Fenstergröße und Sonderformen", "Dreh-Kipp- oder Festverglasung", "Schallschutz und Sicherheitsbeschläge", "Farbe und Dekor", "Montage, Ausbau und Entsorgung"],
    compareHeading: "Fensterpreis und Einbau getrennt betrachten",
    compareParagraphs: ["Die BauKostenRadar-Preisposition nennt das Fenster ohne Einbau. Für ein komplettes Austauschprojekt muss die Montage separat hinzugerechnet oder im Angebot ausdrücklich enthalten sein.", "Wer zwischen 2-fach und 3-fach Verglasung vergleicht, sollte neben dem Preis auch energetische Anforderungen und den gesamten Bauteilanschluss berücksichtigen."],
    faqs: [
      { question: "Was kostet ein Fenster mit 2-fach Verglasung 2026?", answer: "BauKostenRadar führt etwa 400 bis 700 Euro pro Standardfenster ohne Einbau als Richtwert." },
      { question: "Was kosten zehn 2-fach verglaste Fenster?", answer: "Ohne Einbau ergeben sich ungefähr 4.000 bis 7.000 Euro als erste Orientierung." },
      { question: "Ist der Fenstereinbau enthalten?", answer: "Nein. Der BauKostenRadar-Richtwert für diese Position ist ausdrücklich ohne Einbau angegeben." },
    ],
    serviceSlug: "fenster", itemSlug: "fenster-mit-2-fach-verglasung", itemLabel: "Fenster mit 2-fach Verglasung", serviceLabel: "Fenster", parentSlug: "fenster-austauschen-kosten-haus", parentLabel: "Fenster austauschen Kosten",
    relatedExtra: [{ label: "Fenstereinbau Kosten", href: "/ratgeber/fenstereinbau-kosten" }, { label: "3-fach Verglasung Kosten", href: "/ratgeber/fenster-3-fach-verglasung-kosten" }],
  },
  {
    slug: "thermostat-installieren-kosten",
    title: "Thermostat installieren Kosten 2026",
    h1: "Thermostat installieren Kosten 2026: Richtwert pro Stück",
    description: "Thermostat installieren Kosten 2026: BauKostenRadar-Richtwert pro Stück, Ventil, Heizkörper, smarte Thermostate und Angebotsvergleich.",
    eyebrow: "Heizungsregelung 2026",
    intro: "Ein Thermostatwechsel ist ein überschaubarer Eingriff, kann aber je nach Ventil, Heizkörper und gewünschter Regelung unterschiedlich aufwendig sein. Mehrere Thermostate lassen sich meist effizienter in einem Termin bearbeiten.",
    keyFact: "Thermostat installieren etwa 50-150 € pro Stück in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Thermostat installieren pro Stück?",
    priceParagraphs: ["BauKostenRadar führt für Thermostat installieren etwa 50 bis 150 Euro pro Stück. Zehn Thermostate ergeben rechnerisch ungefähr 500 bis 1.500 Euro als Budgetorientierung.", "Bei einfachen Thermostatköpfen kann der Aufwand geringer sein als bei Ventiltausch, hydraulischen Anpassungen oder smarten Systemen mit zusätzlicher Einrichtung."],
    table: { headers: ["Anzahl", "Budgetorientierung"], rows: [
      { cells: ["5 Thermostate", "250-750 €"] },
      { cells: ["10 Thermostate", "500-1.500 €"] },
      { cells: ["20 Thermostate", "1.000-3.000 €"] },
    ] },
    factorsHeading: "Was beeinflusst die Thermostatkosten?",
    factorsIntro: "Wichtig ist, ob nur der Bedienkopf oder auch das Heizkörperventil erneuert werden muss.",
    factors: ["Mechanischer oder smarter Thermostat", "Vorhandenes Ventil", "Ventiltausch und Entleerung", "Einrichtung einer App oder Zentrale", "Anzahl der Heizkörper", "Anfahrt und Mindestauftragswert"],
    compareHeading: "Thermostatkopf und Ventiltausch unterscheiden",
    compareParagraphs: ["Angebote sollten benennen, welche Bauteile ersetzt werden. Ein reiner Thermostatkopf ist nicht dieselbe Leistung wie ein Ventiltausch mit Eingriff in das Heizsystem.", "Bei vielen Heizkörpern lohnt es sich, Thermostate und weitere Heizungsarbeiten gemeinsam kalkulieren zu lassen."],
    faqs: [
      { question: "Was kostet Thermostat installieren 2026?", answer: "BauKostenRadar führt etwa 50 bis 150 Euro pro Stück als Richtwert." },
      { question: "Was kosten zehn Thermostate?", answer: "Rechnerisch ergeben sich ungefähr 500 bis 1.500 Euro als Budgetorientierung." },
      { question: "Sind smarte Thermostate enthalten?", answer: "Nicht automatisch. Produktpreis und Einrichtung eines Smart-Home-Systems können den konkreten Preis verändern." },
    ],
    serviceSlug: "heizung", itemSlug: "thermostat-installieren", itemLabel: "Thermostat installieren", serviceLabel: "Heizung", parentSlug: "heizung-erneuern-kosten", parentLabel: "Heizung erneuern Kosten",
    relatedExtra: [{ label: "Heizkörper montieren Kosten", href: "/ratgeber/heizkoerper-montieren-kosten" }],
  },
  {
    slug: "fassadenrisse-sanieren-kosten-pro-qm",
    title: "Fassadenrisse sanieren Kosten pro m² 2026",
    h1: "Fassadenrisse sanieren Kosten 2026: Richtwerte pro m²",
    description: "Fassadenrisse sanieren Kosten 2026 pro m²: BauKostenRadar-Richtwerte, Schadensbild, Putz, Gerüst, Anstrich und Angebotsvergleich.",
    eyebrow: "Fassadensanierung 2026",
    intro: "Risse in der Fassade können oberflächlich im Putz liegen oder auf tiefergehende Bewegungen hindeuten. Vor der Preisbewertung muss deshalb klar sein, welche Ursache und welcher Sanierungsaufbau zugrunde liegen.",
    keyFact: "Fassaden-Sanierung bei Rissen etwa 32-85 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Fassadenrisse sanieren pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Fassaden-Sanierung bei Rissen etwa 32 bis 85 Euro pro Quadratmeter. Für 100 m² ergibt sich daraus eine erste Budgetorientierung von ungefähr 3.200 bis 8.500 Euro.", "Gerüst, statische Untersuchungen, vollständiger Neuputz oder Dämmarbeiten können abhängig vom Schadensbild zusätzlich erforderlich sein."],
    table: { headers: ["Fassadenfläche", "Budgetorientierung"], rows: [
      { cells: ["50 m²", "1.600-4.250 €"] },
      { cells: ["100 m²", "3.200-8.500 €"] },
      { cells: ["200 m²", "6.400-17.000 €"] },
    ] },
    factorsHeading: "Welche Faktoren beeinflussen die Risssanierung?",
    factorsIntro: "Nicht jeder Riss wird mit derselben Methode behandelt. Ursache, Breite und Bewegung sind entscheidend.",
    factors: ["Putzriss oder tieferer Bauteilriss", "Rissbreite und Rissbewegung", "Armierungsgewebe und Putzaufbau", "Flächiger Neuputz oder lokale Reparatur", "Gerüst und Gebäudehöhe", "Anschließender Fassadenanstrich"],
    compareHeading: "Ursache vor Kosmetik klären",
    compareParagraphs: ["Ein Angebot nur für das Überspachteln sichtbarer Risse ist nicht mit einer systematischen Fassadensanierung vergleichbar. Der vorgesehene Aufbau sollte beschrieben sein.", "Bei großflächig geschädigtem Putz kann eine neue Putzfassade wirtschaftlich anders zu bewerten sein als viele Einzelreparaturen."],
    faqs: [
      { question: "Was kostet Fassadenrisse sanieren pro m² 2026?", answer: "BauKostenRadar führt etwa 32 bis 85 Euro pro Quadratmeter als Richtwert." },
      { question: "Was kosten 100 m² Fassadensanierung bei Rissen?", answer: "Mit der Richtwertspanne ergeben sich ungefähr 3.200 bis 8.500 Euro als Budgetorientierung." },
      { question: "Ist ein Gerüst enthalten?", answer: "Nicht automatisch. Gerüstkosten sollten im konkreten Angebot ausdrücklich geprüft werden." },
    ],
    serviceSlug: "fassade", itemSlug: "fassaden-sanierung-bei-rissen", itemLabel: "Fassaden-Sanierung bei Rissen", serviceLabel: "Fassade", parentSlug: "fassade-sanieren-kosten", parentLabel: "Fassade sanieren Kosten",
    relatedExtra: [{ label: "Putzfassade Kosten", href: "/ratgeber/putzfassade-kosten-pro-qm" }, { label: "Gerüst Kosten", href: "/ratgeber/geruest-kosten-pro-qm" }],
  },
  {
    slug: "vorgehaengte-hinterlueftete-fassade-kosten-pro-qm",
    title: "Vorgehängte hinterlüftete Fassade Kosten pro m² 2026",
    h1: "Vorgehängte hinterlüftete Fassade Kosten 2026: Richtwert pro m²",
    description: "Vorgehängte hinterlüftete Fassade Kosten 2026 pro m²: BauKostenRadar-Richtwerte mit Dämmung und Montage, Bekleidung, Unterkonstruktion und Angebotsvergleich.",
    eyebrow: "VHF-Fassade 2026",
    intro: "Eine vorgehängte hinterlüftete Fassade besteht aus Unterkonstruktion, Dämmung, Hinterlüftungsebene und sichtbarer Bekleidung. Materialwahl und Befestigungssystem beeinflussen den Quadratmeterpreis stark.",
    keyFact: "Vorgehängte hinterlüftete Fassade etwa 250-350 €/m² mit Dämmung und Montage in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet eine VHF-Fassade pro m²?",
    priceParagraphs: ["BauKostenRadar führt für eine vorgehängte hinterlüftete Fassade etwa 250 bis 350 Euro pro Quadratmeter. Die zugrunde liegende Preisposition nennt Dämmung und Montage als Bestandteil.", "Für 100 m² ergibt sich daraus eine erste Orientierung von etwa 25.000 bis 35.000 Euro. Gerüst, besondere Fassadenbekleidungen oder komplizierte Anschlüsse können die Kalkulation verändern."],
    table: { headers: ["Fassadenfläche", "Budgetorientierung"], rows: [
      { cells: ["50 m²", "12.500-17.500 €"] },
      { cells: ["100 m²", "25.000-35.000 €"] },
      { cells: ["200 m²", "50.000-70.000 €"] },
    ] },
    factorsHeading: "Was beeinflusst die Kosten einer hinterlüfteten Fassade?",
    factorsIntro: "Die sichtbare Bekleidung ist nur ein Teil des Systems. Unterkonstruktion und Anschlüsse können einen großen Arbeitsanteil ausmachen.",
    factors: ["Bekleidungsart und Plattenformat", "Unterkonstruktion aus Holz oder Metall", "Dämmstoff und Dämmstärke", "Fensterlaibungen und Gebäudeecken", "Brandschutzdetails", "Gerüst und Gebäudehöhe"],
    compareHeading: "VHF nicht mit WDVS oder einfachem Putz vergleichen",
    compareParagraphs: ["Eine VHF ist konstruktiv deutlich komplexer als ein reiner Fassadenanstrich oder neuer Putz. Auch gegenüber einem WDVS unterscheiden sich Aufbau und Bekleidung.", "Vergleichen Sie nur Angebote, die Dämmung, Unterkonstruktion, Bekleidung, Anschlüsse und Gerüst eindeutig beschreiben."],
    faqs: [
      { question: "Was kostet eine vorgehängte hinterlüftete Fassade pro m² 2026?", answer: "BauKostenRadar führt etwa 250 bis 350 Euro pro Quadratmeter als Richtwert." },
      { question: "Was kosten 100 m² VHF?", answer: "Mit dem Richtwert ergeben sich ungefähr 25.000 bis 35.000 Euro als Budgetorientierung." },
      { question: "Ist Dämmung enthalten?", answer: "Die BauKostenRadar-Preisposition ist mit Dämmung und Montage beschrieben. Der genaue Systemaufbau muss im Angebot trotzdem geprüft werden." },
    ],
    serviceSlug: "fassade", itemSlug: "vorgehaengte-hinterlueftete-fassade", itemLabel: "Vorgehängte hinterlüftete Fassade", serviceLabel: "Fassade", parentSlug: "fassade-sanieren-kosten", parentLabel: "Fassade sanieren Kosten",
    relatedExtra: [{ label: "Fassadendämmung Kosten", href: "/ratgeber/fassadendaemmung-kosten-pro-qm" }],
  },
  {
    slug: "heckenschnitt-kosten-pro-meter",
    title: "Heckenschnitt Kosten pro Meter 2026",
    h1: "Heckenschnitt Kosten 2026: Richtwert pro laufendem Meter",
    description: "Heckenschnitt Kosten 2026 pro Meter: BauKostenRadar-Richtwerte, Höhe, Schnittstärke, Grüngut, Zugänglichkeit und Angebotsvergleich.",
    eyebrow: "Gartenpflege 2026",
    intro: "Beim Heckenschnitt zählen nicht nur Meter. Höhe, Breite, Schnittmenge und die Frage, ob das Grüngut entsorgt wird, bestimmen den tatsächlichen Aufwand.",
    keyFact: "Heckenschnitt etwa 3-8 €/lfd. Meter in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Heckenschnitt pro Meter?",
    priceParagraphs: ["BauKostenRadar führt für Heckenschnitt etwa 3 bis 8 Euro pro laufendem Meter. Für 50 Meter Hecke ergibt sich daraus rechnerisch eine erste Orientierung von etwa 150 bis 400 Euro.", "Bei sehr hohen oder stark zurückzuschneidenden Hecken, schwieriger Zugänglichkeit und großer Grüngutmenge kann der Aufwand deutlich höher ausfallen."],
    table: { headers: ["Heckenlänge", "Budgetorientierung"], rows: [
      { cells: ["20 m", "60-160 €"] },
      { cells: ["50 m", "150-400 €"] },
      { cells: ["100 m", "300-800 €"] },
    ] },
    factorsHeading: "Welche Faktoren verändern Heckenschnitt-Kosten?",
    factorsIntro: "Eine niedrige Pflegehecke ist schneller bearbeitet als eine hohe, breite oder lange nicht geschnittene Hecke.",
    factors: ["Heckenhöhe und -breite", "Pflegeschnitt oder starker Rückschnitt", "Leiter- oder Gerüsteinsatz", "Zugänglichkeit beider Heckenseiten", "Aufnehmen und Häckseln des Schnittguts", "Abtransport und Entsorgung"],
    compareHeading: "Schnitt und Entsorgung getrennt prüfen",
    compareParagraphs: ["Bei Angeboten sollte klar sein, ob Schnittgut aufgenommen, gehäckselt und abgefahren wird. Ein reiner Schnittpreis kann sonst deutlich niedriger aussehen.", "Für regelmäßige Gartenpflege kann ein Stunden- oder Pflegevertrag sinnvoll anders kalkuliert werden als ein einmaliger Heckenschnitt."],
    faqs: [
      { question: "Was kostet Heckenschnitt pro Meter 2026?", answer: "BauKostenRadar führt etwa 3 bis 8 Euro pro laufendem Meter als Richtwert." },
      { question: "Was kosten 50 Meter Heckenschnitt?", answer: "Rechnerisch ergeben sich etwa 150 bis 400 Euro als erste Budgetorientierung." },
      { question: "Ist die Entsorgung enthalten?", answer: "Nicht automatisch. Aufnahme, Häckseln und Abtransport des Schnittguts sollten im Angebot ausdrücklich beschrieben sein." },
    ],
    serviceSlug: "garten", itemSlug: "heckenschnitt", itemLabel: "Heckenschnitt", serviceLabel: "Garten & Außenanlagen", parentSlug: "garten-anlegen-kosten", parentLabel: "Garten anlegen Kosten",
  },
  {
    slug: "innentuer-einbauen-kosten",
    title: "Innentür einbauen Kosten 2026",
    h1: "Innentür einbauen Kosten 2026: Tür inklusive Zarge",
    description: "Innentür einbauen Kosten 2026: BauKostenRadar-Richtwert pro Tür inklusive Zarge, Türblatt, Beschläge, Ausbau und Angebotsvergleich.",
    eyebrow: "Innentür 2026",
    intro: "Beim Einbau einer Innentür bestimmen Türblatt, Zarge, Wandstärke und vorhandene Öffnung den Aufwand. Für mehrere Türen ist ein Stückpreis besonders gut vergleichbar, wenn Materialstandard und Rückbau gleich definiert sind.",
    keyFact: "Innentür einbauen inklusive Zarge etwa 250-600 € pro Tür in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet eine Innentür inklusive Zarge?",
    priceParagraphs: ["BauKostenRadar führt für Innentür einbauen inklusive Zarge etwa 250 bis 600 Euro pro Tür als Richtwert in Standardausführung. Sechs Türen ergeben rechnerisch etwa 1.500 bis 3.600 Euro.", "Sondermaße, Schallschutz, hochwertige Türblätter, Glas oder aufwendige Anpassungen können den Stückpreis erhöhen."],
    table: { headers: ["Anzahl", "Budgetorientierung"], rows: [
      { cells: ["1 Tür", "250-600 €"] },
      { cells: ["6 Türen", "1.500-3.600 €"] },
      { cells: ["10 Türen", "2.500-6.000 €"] },
    ] },
    factorsHeading: "Was beeinflusst Innentür-Kosten?",
    factorsIntro: "Der Türpreis hängt sowohl vom Produkt als auch von der Passgenauigkeit der vorhandenen Öffnung ab.",
    factors: ["Türblatt und Oberflächenqualität", "Zargenbreite und Wandstärke", "Standard- oder Sondermaß", "Beschläge und Schloss", "Ausbau alter Tür und Zarge", "Nacharbeiten an Laibung und Boden"],
    compareHeading: "Materialstandard und Montageumfang festlegen",
    compareParagraphs: ["Ein Stückpreis ist nur vergleichbar, wenn Türblatt, Zarge, Beschläge und Montage ähnlich definiert sind. Prüfen Sie außerdem, ob alte Türen entsorgt werden.", "Für ein typisches Paket mit sechs Türen bietet BauKostenRadar zusätzlich ein konkretes Szenario mit Gesamtkosten."],
    faqs: [
      { question: "Was kostet Innentür einbauen 2026?", answer: "BauKostenRadar führt etwa 250 bis 600 Euro pro Tür inklusive Zarge als Richtwert für Standardausführung." },
      { question: "Was kosten sechs Innentüren?", answer: "Rechnerisch ergeben sich ungefähr 1.500 bis 3.600 Euro als erste Budgetorientierung." },
      { question: "Ist der Ausbau alter Türen enthalten?", answer: "Nicht automatisch. Rückbau und Entsorgung sollten im konkreten Angebot ausdrücklich ausgewiesen werden." },
    ],
    serviceSlug: "tueren", itemSlug: "innentuer-einbauen-inkl-zarge", itemLabel: "Innentür einbauen inkl. Zarge", serviceLabel: "Türen", parentSlug: "6-innentueren-austauschen-kosten", parentLabel: "6 Innentüren austauschen Kosten",
  },
  {
    slug: "tuer-lackieren-kosten",
    title: "Tür lackieren Kosten 2026",
    h1: "Tür lackieren Kosten 2026: Tür und Zarge aufarbeiten",
    description: "Tür lackieren Kosten 2026: BauKostenRadar-Richtwert pro Stück mit Zarge, Schleifen, Vorarbeiten, Lackaufbau und Angebotsvergleich.",
    eyebrow: "Türen aufarbeiten 2026",
    intro: "Vorhandene Türen zu lackieren kann günstiger sein als ein kompletter Austausch, wenn Türblatt und Zarge technisch in Ordnung sind. Der Zustand der alten Beschichtung bestimmt, wie viel geschliffen und gespachtelt werden muss.",
    keyFact: "Tür lackieren mit Zarge etwa 170-250 € pro Stück in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Tür lackieren mit Zarge?",
    priceParagraphs: ["BauKostenRadar führt für Tür lackieren mit Zarge etwa 170 bis 250 Euro pro Stück als Richtwert. Für sechs Türen ergibt sich daraus eine Orientierung von ungefähr 1.020 bis 1.500 Euro.", "Starke Lackschäden, Profilierungen, Glasfelder oder notwendige Reparaturen können den Aufwand erhöhen. Beschläge und Türdrücker sind gesondert zu betrachten."],
    table: { headers: ["Anzahl", "Budgetorientierung"], rows: [
      { cells: ["1 Tür", "170-250 €"] },
      { cells: ["6 Türen", "1.020-1.500 €"] },
      { cells: ["10 Türen", "1.700-2.500 €"] },
    ] },
    factorsHeading: "Was beeinflusst Lackierkosten bei Türen?",
    factorsIntro: "Je schlechter die Altbeschichtung, desto mehr Vorarbeit ist vor dem neuen Lackaufbau nötig.",
    factors: ["Zustand von Türblatt und Zarge", "Schleifen und Spachteln", "Anzahl der Lackschichten", "Kassetten, Profile und Glasfelder", "Demontage und Wiedermontage von Beschlägen", "Farbwechsel und Lackqualität"],
    compareHeading: "Lackieren mit Austausch vergleichen",
    compareParagraphs: ["Bei intakten, hochwertigen Holztüren kann Aufarbeitung wirtschaftlich attraktiv sein. Bei einfachen beschädigten Türen sollte der Preis mit einem kompletten Austausch inklusive neuer Zarge verglichen werden.", "Angebote sollten Türblatt und Zarge ausdrücklich nennen, damit nicht nur eine Teilfläche kalkuliert wird."],
    faqs: [
      { question: "Was kostet Tür lackieren 2026?", answer: "BauKostenRadar führt für Tür lackieren mit Zarge etwa 170 bis 250 Euro pro Stück als Richtwert." },
      { question: "Was kosten sechs Türen lackieren?", answer: "Mit der Richtwertspanne ergeben sich ungefähr 1.020 bis 1.500 Euro als Budgetorientierung." },
      { question: "Ist Schleifen enthalten?", answer: "Der konkrete Vorbereitungsumfang muss im Angebot geprüft werden. Zustand und notwendige Schleif- oder Spachtelarbeiten beeinflussen den Preis wesentlich." },
    ],
    serviceSlug: "tueren", itemSlug: "tuer-lackieren-mit-zarge", itemLabel: "Tür lackieren mit Zarge", serviceLabel: "Türen", parentSlug: "6-innentueren-austauschen-kosten", parentLabel: "6 Innentüren austauschen Kosten",
    relatedExtra: [{ label: "Innentür einbauen Kosten", href: "/ratgeber/innentuer-einbauen-kosten" }],
  },
  {
    slug: "anhydritestrich-kosten-pro-qm",
    title: "Anhydritestrich Kosten pro m² 2026",
    h1: "Anhydritestrich Kosten 2026: Calciumsulfatestrich pro m²",
    description: "Anhydritestrich Kosten 2026 pro m²: BauKostenRadar-Richtwerte für Calciumsulfatestrich, Fläche, Aufbau, Fußbodenheizung und Angebotsvergleich.",
    eyebrow: "Calciumsulfatestrich 2026",
    intro: "Calciumsulfat- beziehungsweise Anhydritestrich lässt sich großflächig und eben herstellen und wird häufig mit Fußbodenheizung kombiniert. Feuchtebeanspruchung und der gesamte Bodenaufbau müssen zum Einsatzbereich passen.",
    keyFact: "Calciumsulfat- / Anhydritestrich etwa 28-55 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Anhydritestrich pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Calciumsulfat- beziehungsweise Anhydritestrich etwa 28 bis 55 Euro pro Quadratmeter. Für 100 m² ergibt sich daraus eine erste Orientierung von ungefähr 2.800 bis 5.500 Euro.", "Dämmung, Ausgleich, besondere Estrichdicken und zusätzliche Anforderungen an den Bodenaufbau können den Gesamtpreis verändern."],
    table: { headers: ["Estrichfläche", "Budgetorientierung"], rows: [
      { cells: ["50 m²", "1.400-2.750 €"] },
      { cells: ["100 m²", "2.800-5.500 €"] },
      { cells: ["150 m²", "4.200-8.250 €"] },
    ] },
    factorsHeading: "Welche Faktoren verändern Anhydritestrich-Kosten?",
    factorsIntro: "Fläche und Aufbau bestimmen Materialmenge und Arbeitsablauf. Kleinflächen können relativ teurer sein.",
    factors: ["Estrichdicke", "Untergrund und Dämmaufbau", "Fußbodenheizung", "Pump- und Förderweg", "Randstreifen und Bewegungsfugen", "Flächengröße und Baustellenlogistik"],
    compareHeading: "Anhydrit- und Zementestrich passend zum Einsatz wählen",
    compareParagraphs: ["Der Preis allein entscheidet nicht über das geeignete Estrichsystem. Feuchtebeanspruchung, Trocknung und gewünschter Bodenbelag gehören in die Planung.", "Vergleichen Sie Angebote mit gleichem Aufbau und gleicher Estrichdicke, nicht nur anhand des Quadratmeterpreises."],
    faqs: [
      { question: "Was kostet Anhydritestrich pro m² 2026?", answer: "BauKostenRadar führt etwa 28 bis 55 Euro pro Quadratmeter als Richtwert." },
      { question: "Was kosten 100 m² Anhydritestrich?", answer: "Mit der Richtwertspanne ergeben sich ungefähr 2.800 bis 5.500 Euro als Budgetorientierung." },
      { question: "Ist Anhydritestrich für Fußbodenheizung geeignet?", answer: "Er wird häufig in beheizten Bodenaufbauten eingesetzt. Der konkrete Systemaufbau muss jedoch technisch passend geplant werden." },
    ],
    serviceSlug: "estrich", itemSlug: "calciumsulfat-anhydritestrich", itemLabel: "Calciumsulfat- / Anhydritestrich", serviceLabel: "Estrich", parentSlug: "estrich-100-qm-kosten", parentLabel: "Estrich 100 m² Kosten",
    relatedExtra: [{ label: "Trockenestrich Kosten", href: "/ratgeber/trockenestrich-kosten-pro-qm" }],
  },
  {
    slug: "gussasphaltestrich-kosten-pro-qm",
    title: "Gussasphaltestrich Kosten pro m² 2026",
    h1: "Gussasphaltestrich Kosten 2026: Richtwerte pro m²",
    description: "Gussasphaltestrich Kosten 2026 pro m²: BauKostenRadar-Richtwerte, Einbau, Aufbauhöhe, Dämmung, Baustellenlogistik und Angebotsvergleich.",
    eyebrow: "Gussasphalt 2026",
    intro: "Gussasphaltestrich wird heiß eingebaut und kommt ohne Baufeuchte aus. Die Verarbeitung erfordert spezielle Logistik und Fachtechnik, weshalb Baustellenzugang und Förderweg besonders relevant sind.",
    keyFact: "Gussasphaltestrich etwa 40-70 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Gussasphaltestrich pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Gussasphaltestrich etwa 40 bis 70 Euro pro Quadratmeter. Für 100 m² ergibt sich daraus eine erste Budgetorientierung von ungefähr 4.000 bis 7.000 Euro.", "Dämmung, Untergrundvorbereitung und besondere Schichtdicken können zusätzlich in den Bodenaufbau einfließen."],
    table: { headers: ["Estrichfläche", "Budgetorientierung"], rows: [
      { cells: ["50 m²", "2.000-3.500 €"] },
      { cells: ["100 m²", "4.000-7.000 €"] },
      { cells: ["150 m²", "6.000-10.500 €"] },
    ] },
    factorsHeading: "Was beeinflusst Gussasphalt-Kosten?",
    factorsIntro: "Die heiße Verarbeitung macht Logistik und Einbringweg zu einem wesentlichen Kostenfaktor.",
    factors: ["Flächengröße", "Schichtdicke und Aufbau", "Transport- und Förderweg", "Stockwerk und Zugänglichkeit", "Dämm- und Trennlagen", "Anschlüsse und kleine Teilflächen"],
    compareHeading: "Schnelle Nutzung gegen höheren Spezialaufwand abwägen",
    compareParagraphs: ["Gussasphaltestrich bringt keine zusätzliche Baufeuchte ein und ist nach Abkühlung schnell nutzbar. Dem steht ein spezialisierter Einbau gegenüber.", "Vergleichen Sie daher nicht nur den Quadratmeterpreis, sondern auch Bauzeit, Folgearbeiten und den kompletten Bodenaufbau."],
    faqs: [
      { question: "Was kostet Gussasphaltestrich pro m² 2026?", answer: "BauKostenRadar führt etwa 40 bis 70 Euro pro Quadratmeter als Richtwert." },
      { question: "Was kosten 100 m² Gussasphaltestrich?", answer: "Mit der Richtwertspanne ergeben sich ungefähr 4.000 bis 7.000 Euro als Budgetorientierung." },
      { question: "Warum ist die Baustellenlogistik wichtig?", answer: "Gussasphalt wird heiß verarbeitet. Transport- und Einbringwege können deshalb den Arbeitsaufwand wesentlich beeinflussen." },
    ],
    serviceSlug: "estrich", itemSlug: "gussasphaltestrich", itemLabel: "Gussasphaltestrich", serviceLabel: "Estrich", parentSlug: "estrich-100-qm-kosten", parentLabel: "Estrich 100 m² Kosten",
  },
  {
    slug: "sichtestrich-kosten-pro-qm",
    title: "Sichtestrich Kosten pro m² 2026",
    h1: "Sichtestrich Kosten 2026: Richtwerte pro m² fertige Oberfläche",
    description: "Sichtestrich Kosten 2026 pro m²: BauKostenRadar-Richtwerte, Oberflächenqualität, Schleifen, Versiegelung, Fugen und Angebotsvergleich.",
    eyebrow: "Sichtestrich 2026",
    intro: "Bei Sichtestrich bleibt der Estrich selbst als fertige Oberfläche sichtbar. Dadurch steigen die Anforderungen an Ebenheit, Farbwirkung, Fugenbild und Oberflächenbehandlung deutlich gegenüber einem Estrich unter Bodenbelag.",
    keyFact: "Sichtestrich etwa 90-300 €/m² in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Sichtestrich pro m²?",
    priceParagraphs: ["BauKostenRadar führt für Sichtestrich etwa 90 bis 300 Euro pro Quadratmeter. Für 50 m² ergibt sich daraus eine breite Budgetorientierung von ungefähr 4.500 bis 15.000 Euro.", "Die große Spanne zeigt, wie stark Gestaltung und Oberflächenfinish den Preis beeinflussen. Schleifen, Spachteln, Pigmentierung oder Versiegelung sollten im Angebot eindeutig beschrieben sein."],
    table: { headers: ["Sichtfläche", "Budgetorientierung"], rows: [
      { cells: ["25 m²", "2.250-7.500 €"] },
      { cells: ["50 m²", "4.500-15.000 €"] },
      { cells: ["100 m²", "9.000-30.000 €"] },
    ] },
    factorsHeading: "Was treibt Sichtestrich-Kosten?",
    factorsIntro: "Die technische Estrichschicht wird zum Gestaltungselement. Kleine optische Fehler sind daher wesentlich relevanter.",
    factors: ["Gewünschte Farb- und Wolkenwirkung", "Schleif- und Poliergrad", "Versiegelung oder Beschichtung", "Fugenplanung", "Ebenheit und Detailanschlüsse", "Musterflächen und Qualitätsanforderung"],
    compareHeading: "Sichtestrich nicht mit normalem Unterestrich vergleichen",
    compareParagraphs: ["Ein Estrich, der später mit Parkett oder Fliesen abgedeckt wird, hat andere optische Anforderungen. Sichtestrich ist deshalb als fertige Bodenoberfläche zu bewerten.", "Fordern Sie Referenzflächen oder eine genaue Beschreibung des Finishs, bevor Sie Angebote nur über den Quadratmeterpreis vergleichen."],
    faqs: [
      { question: "Was kostet Sichtestrich pro m² 2026?", answer: "BauKostenRadar führt etwa 90 bis 300 Euro pro Quadratmeter als Richtwert." },
      { question: "Was kosten 50 m² Sichtestrich?", answer: "Mit der Richtwertspanne ergeben sich ungefähr 4.500 bis 15.000 Euro als Budgetorientierung." },
      { question: "Warum ist die Preisspanne so groß?", answer: "Oberflächenqualität, Schleifen, Gestaltung und Versiegelung können den Aufwand stark verändern." },
    ],
    serviceSlug: "estrich", itemSlug: "sichtestrich", itemLabel: "Sichtestrich", serviceLabel: "Estrich", parentSlug: "estrich-100-qm-kosten", parentLabel: "Estrich 100 m² Kosten",
    relatedExtra: [{ label: "Anhydritestrich Kosten", href: "/ratgeber/anhydritestrich-kosten-pro-qm" }],
  },
  {
    slug: "holztreppe-schleifen-kosten",
    title: "Holztreppe schleifen Kosten 2026",
    h1: "Holztreppe schleifen und versiegeln Kosten 2026",
    description: "Holztreppe schleifen Kosten 2026: BauKostenRadar-Richtwert pro Treppe für Schleifen und Versiegeln, Zustand, Geländer und Angebotsvergleich.",
    eyebrow: "Treppenaufarbeitung 2026",
    intro: "Eine massive Holztreppe lässt sich oft durch Schleifen und neue Versiegelung sichtbar aufwerten. Lackschichten, tiefe Schäden, Kanten und Geländerteile bestimmen, wie viele Arbeitsgänge nötig sind.",
    keyFact: "Holztreppe schleifen und versiegeln etwa 800-2.500 € pro Treppe in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet eine Holztreppe schleifen und versiegeln?",
    priceParagraphs: ["BauKostenRadar führt für Holztreppe schleifen und versiegeln etwa 800 bis 2.500 Euro pro Treppe als Richtwert. Die Spanne hängt stark von Stufenzahl, Beschichtung und Zustand ab.", "Geländer, Wangen, Podeste oder Reparaturen sind je nach Angebot nicht automatisch im gleichen Umfang enthalten."],
    factorsHeading: "Welche Faktoren beeinflussen die Treppenaufarbeitung?",
    factorsIntro: "Treppen bestehen aus vielen Kanten und Detailflächen. Dadurch ist die Arbeit aufwendiger als das Schleifen einer ebenen Bodenfläche.",
    factors: ["Anzahl und Form der Stufen", "Altlack oder alte Beschichtung", "Tiefe Kratzer und Reparaturen", "Wangen und Setzstufen", "Geländer und Handlauf", "Öl, Lack oder andere Versiegelung"],
    compareHeading: "Aufarbeitung mit Stufenüberbau vergleichen",
    compareParagraphs: ["Wenn die vorhandenen Holzstufen technisch gut sind, kann Schleifen sinnvoll sein. Bei stark beschädigten Stufen kann ein Überbau oder anderes Renovierungssystem wirtschaftlich anders ausfallen.", "Angebote sollten klar nennen, welche Treppenteile geschliffen und wie viele Finish-Arbeitsgänge ausgeführt werden."],
    faqs: [
      { question: "Was kostet Holztreppe schleifen 2026?", answer: "BauKostenRadar führt für Schleifen und Versiegeln etwa 800 bis 2.500 Euro pro Treppe als Richtwert." },
      { question: "Ist das Geländer enthalten?", answer: "Nicht automatisch. Geländer und Handlauf sollten im konkreten Angebot als Bestandteil oder Zusatzleistung genannt sein." },
      { question: "Lohnt Schleifen statt neuer Treppe?", answer: "Bei technisch intakter Massivholztreppe kann Aufarbeitung deutlich weniger eingreifend sein. Der Zustand entscheidet über die Wirtschaftlichkeit." },
    ],
    serviceSlug: "treppen", itemSlug: "holztreppe-schleifen-und-versiegeln", itemLabel: "Holztreppe schleifen und versiegeln", serviceLabel: "Treppen", parentSlug: "14-treppenstufen-renovieren-kosten", parentLabel: "14 Treppenstufen renovieren Kosten",
  },
  {
    slug: "betontreppe-neuer-belag-kosten",
    title: "Betontreppe neuer Belag Kosten 2026",
    h1: "Betontreppe mit neuem Belag Kosten 2026",
    description: "Betontreppe neuer Belag Kosten 2026: BauKostenRadar-Richtwert pro Treppe, Untergrund, Holz, Fliesen, Naturstein und Angebotsvergleich.",
    eyebrow: "Betontreppe renovieren 2026",
    intro: "Bei einer Betontreppe kann der tragende Kern erhalten bleiben, während Stufen und Podeste einen neuen Belag erhalten. Materialwahl und Ausgleich des Untergrunds bestimmen den Preis stärker als bei einer einfachen Oberflächenauffrischung.",
    keyFact: "Betontreppe mit neuem Belag etwa 1.500-4.500 € pro Treppe in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet eine Betontreppe mit neuem Belag?",
    priceParagraphs: ["BauKostenRadar führt für Betontreppe mit neuem Belag etwa 1.500 bis 4.500 Euro pro Treppe als Richtwert. Holz, Fliesen, Naturstein oder andere Beläge können innerhalb und außerhalb dieser Spanne unterschiedlich ausfallen.", "Rückbau des Altbelags, Stufenausgleich, neue Sockel und Geländerarbeiten sollten im konkreten Angebot eindeutig beschrieben sein."],
    factorsHeading: "Was beeinflusst die Kosten der Betontreppe?",
    factorsIntro: "Der tragende Beton bleibt bestehen, aber jede Stufe muss maßgenau für den neuen Belag vorbereitet werden.",
    factors: ["Anzahl und Geometrie der Stufen", "Rückbau vorhandener Beläge", "Untergrundausgleich", "Holz, Fliesen oder Naturstein", "Stirnseiten und Sockel", "Geländeranschlüsse"],
    compareHeading: "Belagmaterial und Vorbereitung getrennt bewerten",
    compareParagraphs: ["Ein günstiges Material kann durch aufwendigen Untergrundausgleich relativiert werden. Deshalb sollte das Angebot Rückbau, Vorbereitung, Belag und Montage nachvollziehbar trennen.", "Für Holztreppen führt BauKostenRadar einen separaten Richtwert zum Schleifen und Versiegeln."],
    faqs: [
      { question: "Was kostet Betontreppe mit neuem Belag 2026?", answer: "BauKostenRadar führt etwa 1.500 bis 4.500 Euro pro Treppe als Richtwert." },
      { question: "Welcher Belag ist enthalten?", answer: "Die Preisposition beschreibt einen neuen Belag allgemein. Das konkrete Material und seine Qualität müssen im Angebot festgelegt werden." },
      { question: "Ist der alte Belag entfernt?", answer: "Nicht automatisch. Rückbau und Entsorgung sollten als enthaltene oder separate Position erkennbar sein." },
    ],
    serviceSlug: "treppen", itemSlug: "betontreppe-mit-neuem-belag", itemLabel: "Betontreppe mit neuem Belag", serviceLabel: "Treppen", parentSlug: "14-treppenstufen-renovieren-kosten", parentLabel: "14 Treppenstufen renovieren Kosten",
    relatedExtra: [{ label: "Holztreppe schleifen Kosten", href: "/ratgeber/holztreppe-schleifen-kosten" }],
  },
  {
    slug: "fliesenspiegel-erneuern-kosten",
    title: "Fliesenspiegel erneuern Kosten 2026",
    h1: "Fliesenspiegel in der Küche erneuern Kosten 2026",
    description: "Fliesenspiegel erneuern Kosten 2026: BauKostenRadar-Richtwert pro Küche, Rückbau, Untergrund, Fliesen, Steckdosen und Angebotsvergleich.",
    eyebrow: "Küchenwand 2026",
    intro: "Ein neuer Fliesenspiegel verändert die Küche ohne kompletten Möbeltausch. Kleine Flächen bedeuten jedoch nicht automatisch kleine Arbeitskosten, weil Rückbau, Zuschnitte und viele Steckdosenanschlüsse Zeit beanspruchen.",
    keyFact: "Fliesenspiegel erneuern etwa 800-2.500 € pro Küche in der BauKostenRadar-Datenbasis",
    priceHeading: "Was kostet Fliesenspiegel erneuern?",
    priceParagraphs: ["BauKostenRadar führt für Fliesenspiegel erneuern etwa 800 bis 2.500 Euro pro Küche als Richtwert. Die Spanne ist projektbezogen und hängt von Fläche, Material und Rückbau ab.", "Bei hochwertigen Fliesen, großformatigen Platten oder vielen Steckdosen kann der Aufwand deutlich anders ausfallen. Auch Arbeiten hinter vorhandener Küchenzeile müssen berücksichtigt werden."],
    factorsHeading: "Welche Faktoren beeinflussen den Küchen-Fliesenspiegel?",
    factorsIntro: "Viele kleine Detailanschlüsse können bei wenigen Quadratmetern einen hohen Arbeitsanteil erzeugen.",
    factors: ["Rückbau alter Fliesen", "Untergrund und Ausgleich", "Fliesenformat und Material", "Steckdosen und Ausschnitte", "Ecken, Nischen und Fenster", "Silikonfugen und Abschlussprofile"],
    compareHeading: "Fläche und Leistungsumfang gemeinsam vergleichen",
    compareParagraphs: ["Lassen Sie Fläche, Fliesenmaterial, Rückbau und Untergrundarbeiten im Angebot benennen. Ein Pauschalpreis ist sonst schwer mit einem anderen Küchenprojekt vergleichbar.", "Bei kompletter Küchenrenovierung kann der Fliesenspiegel sinnvoll mit Maler-, Boden- und Anschlussarbeiten gebündelt werden."],
    faqs: [
      { question: "Was kostet Fliesenspiegel erneuern 2026?", answer: "BauKostenRadar führt etwa 800 bis 2.500 Euro pro Küche als Richtwert." },
      { question: "Sind neue Fliesen enthalten?", answer: "Der konkrete Materialumfang muss im Angebot geprüft werden. Fliesenqualität und Format können das Projektbudget deutlich verändern." },
      { question: "Warum ist eine kleine Fläche trotzdem aufwendig?", answer: "Küchen-Fliesenspiegel haben oft viele Steckdosen, Ecken und Anschlüsse. Dadurch ist der Arbeitsaufwand pro Quadratmeter relativ hoch." },
    ],
    serviceSlug: "kueche", itemSlug: "fliesenspiegel-erneuern", itemLabel: "Fliesenspiegel erneuern", serviceLabel: "Küchenrenovierung", parentSlug: "kueche-10-qm-renovieren-kosten", parentLabel: "Küche 10 m² renovieren Kosten",
    relatedExtra: [{ label: "Fliesen verlegen Kosten", href: "/ratgeber/fliesen-verlegen-kosten-pro-qm" }],
  },
];

export const quaternaryOpportunityGuides: Guide[] = configs.map(createOpportunityGuide);
